export const landingVisualContent = {
    ru: {
        replay: 'Повторить',
        previewReady: 'Результат готов',
        humanEyebrow: 'ТЕХНОЛОГИЯ. ЧЕЛОВЕЧЕСКИЙ РАЗГОВОР.',
        humanTitle: 'Разговор, в котором\nвас понимают.',
        humanIntro: 'Клиент звонит, задаёт вопрос и получает помощь. На привычном языке, с учётом задачи и контекста вашей компании.',
        humanFeatures: [
            ['Узбекский и русский', 'Готовим сценарии и формулировки для ваших клиентов. Проверяем разговоры вместе с вашей командой.'],
            ['Знания вашего бизнеса', 'Ответы, правила и действия агента опираются на информацию вашей компании.'],
            ['Вместе с вашей командой', 'Определяем, какие вопросы решает AI, а когда разговор нужно передать сотруднику.'],
        ],
        humanAlt: 'Женщина разговаривает по телефону у окна',
        parkingContext: 'Городские сервисы', qwattContext: 'Аренда пауэрбанков',
        visualConversation: 'Разговор с клиентом',
        visualReturned: 'Возврат пауэрбанка', visualTranscript: 'Здравствуйте! Чем я могу вам помочь?',
    },
    en: {
        replay: 'Replay',
        previewReady: 'Result ready',
        humanEyebrow: 'TECHNOLOGY. HUMAN CONVERSATIONS.',
        humanTitle: 'A conversation that\nunderstands you.',
        humanIntro: 'Your customer calls, asks a question, and gets help. In a familiar language, with the context of your business.',
        humanFeatures: [
            ['Uzbek and Russian', 'We prepare scenarios and phrasing for your customers, then test conversations with your team.'],
            ['Your business knowledge', 'Answers, rules, and actions are grounded in the information your company provides.'],
            ['Alongside your team', 'We define what the AI handles and when a conversation should reach a member of your team.'],
        ],
        humanAlt: 'A woman talking on the phone beside a window',
        parkingContext: 'Urban services', qwattContext: 'Powerbank sharing',
        visualConversation: 'Customer conversation',
        visualReturned: 'Powerbank return', visualTranscript: 'Hello! How can I help you today?',
    },
    uz: {
        replay: 'Takrorlash',
        previewReady: 'Natija tayyor',
        humanEyebrow: 'TEXNOLOGIYA. SAMIMIY SUHBAT.',
        humanTitle: 'Sizni tushunadigan\nsuhbat.',
        humanIntro: 'Mijoz qo‘ng‘iroq qiladi, savol beradi va yordam oladi. O‘ziga tanish tilda, kompaniyangiz faoliyatini hisobga olgan holda.',
        humanFeatures: [
            ['O‘zbek va rus tillarida', 'Mijozlaringiz uchun ssenariy va iboralarni tayyorlaymiz. Suhbatlarni jamoangiz bilan birga sinaymiz.'],
            ['Biznesingiz bilimlari', 'Agent javoblari, qoidalari va harakatlari kompaniyangiz bergan ma’lumotlarga asoslanadi.'],
            ['Jamoangiz bilan birga', 'Qaysi savollarni AI hal qilishi va qachon suhbatni xodimga o‘tkazish kerakligini belgilaymiz.'],
        ],
        humanAlt: 'Deraza yonida telefonda gaplashayotgan ayol',
        parkingContext: 'Shahar xizmatlari', qwattContext: 'Pauerbank ijarasi',
        visualConversation: 'Mijoz bilan suhbat',
        visualReturned: 'Pauerbank qaytarilishi', visualTranscript: 'Assalomu alaykum! Qanday yordam bera olaman?',
    },
};
