// Only support offers a live agent. Collection and sales will each receive
// their own recording; leave them empty until the corresponding audio arrives.
export const demoScenarios = [
    { id: 'support', company: 'Poytaxt Parking', mode: 'live-or-recording', slug: import.meta.env?.VITE_DEMO_SUPPORT_SLUG || '', recording: '/poytaxt_incoming_uz.wav', recordingLanguage: 'uz', direction: 'incoming' },
    { id: 'collection', company: 'SyncallBank', mode: 'recording', recording: null, recordingLanguage: null, direction: 'outgoing' },
    { id: 'sales', company: 'Syncall', mode: 'recording', recording: null, recordingLanguage: null, direction: 'outgoing' },
];

export const landingContent = {
    ru: {
        recordingComingSoon: 'Запись скоро появится',
        recordingPending: 'Готовим аудиопример этого сценария. Обсудить его для вашей компании можно уже сейчас.',
        recordingNote: 'Послушайте, как агент ведёт разговор в этом сценарии.',
        eyebrow: 'ГОЛОСОВОЙ AI ДЛЯ БИЗНЕСА В УЗБЕКИСТАНЕ',
        title: ['Каждый звонок.', 'На вашем языке.'],
        intro: 'AI-агенты, которые отвечают клиентам, помогают возвращать задолженность и продают. На узбекском и русском. С пониманием вашего бизнеса.',
        tryAgent: 'Поговорить с AI-агентом', talkTeam: 'Обсудить мою задачу', languages: 'O‘zbekcha · Русский',
        heroNote: 'Услышьте, как это работает. Попробуйте сами.',
        trusted: 'Нам доверяют',
        demoEyebrow: 'СНАЧАЛА — ПОПРОБУЙТЕ', demoTitle: 'Хороший разговор\nговорит сам за себя.',
        demoIntro: 'Выберите задачу. Попробуйте live-демо Poytaxt Parking или послушайте запись разговора.',
        scenarios: [
            { title: 'Входящая поддержка', description: 'Вопросы о парковке, оплате и правилах. Агент отвечает клиенту и помогает разобраться.', tag: 'Входящие звонки', prompt: '«Как оплатить парковку?»' },
            { title: 'Soft Collection', description: 'Вежливое напоминание о платеже. Агент уточняет ситуацию и договаривается о следующем шаге.', tag: 'Демонстрационный банк', prompt: '«Можно оплатить завтра?»' },
            { title: 'Исходящие продажи', description: 'Знакомство с предложением, ответы на вопросы и передача заинтересованного клиента команде.', tag: 'Исходящие звонки', prompt: '«А как это поможет моей компании?»' },
        ],
        demoLanguage: 'Язык разговора', phone: 'Ваш номер телефона', phoneHint: 'Введите номер телефона, чтобы поговорить с ИИ-оператором.',
        recordingHint: 'Вы услышите запись разговора с AI-агентом.',
        recordingLabel: 'Пример входящего звонка', outgoingRecordingLabel: 'Пример исходящего звонка',
        sampleNote: 'Live-демо Poytaxt Parking сейчас недоступно. Послушайте запись разговора с агентом поддержки.',
        recording: 'Послушать запись', live: 'Начать разговор', checking: 'Проверяем доступность агента…', sampleBadge: 'Запись разговора',
        retryLive: 'Проверить live-демо', afterTitle: 'Теперь — для вашего бизнеса.', afterText: 'Расскажите о задаче. Мы свяжемся с вами и предложим вариант запуска.',
        saveError: 'Не удалось отправить номер. Попробуйте ещё раз.', saved: 'Номер отправлен. Включите запись и послушайте агента.',
        formTitle: 'Давайте дадим\nвашему бизнесу голос.', formIntro: 'Оставьте несколько деталей. Наша команда свяжется с вами, разберёт задачу и поможет запустить Syncall.',
        company: 'Название компании', companyPlaceholder: 'Как называется ваша компания?', useCase: 'Что хотите поручить агенту?',
        useCasePlaceholder: 'Например, поддержка клиентов или напоминания об оплате', volume: 'Примерный объём в месяц', calls: 'Звонков', minutes: 'Минут',
        submit: 'Обсудить запуск', submitting: 'Отправляем…', success: 'Спасибо! Мы получили вашу заявку и свяжемся с вами.',
        formNote: 'Отправляя заявку, вы соглашаетесь, что Syncall свяжется с вами по указанному номеру.',
        invalid: 'Заполните это поле.', invalidPhone: 'Введите корректный номер Узбекистана: +998 и 9 цифр.', invalidVolume: 'Укажите приблизительное количество от 1 до 1 000 000 000.',
        contactLink: 'Или напишите нам в Telegram',
        storiesEyebrow: 'ИСТОРИИ КЛИЕНТОВ', storiesTitle: 'Результат слышно.\nИ видно в цифрах.',
        storiesIntro: 'От парковок до аренды пауэрбанков — помогаем решать ежедневные задачи бизнеса.',
        parkingMetric: '8 из 10', parkingLabel: 'обращений решает AI без перевода на оператора',
        parkingBody: 'AI-агент Poytaxt Parking отвечает на входящие звонки. В исходящих разговорах — напоминает об оплате, уточняет ситуацию и фиксирует результат.',
        parkingTags: ['Поддержка клиентов', 'Soft Collection'],
        qwattMetric: '+42%', qwattLabel: 'к возвратам пауэрбанков в первую неделю после внедрения',
        qwattBody: 'AI-агент Qwatt звонит клиентам по поводу возврата пауэрбанков и помогает команде работать с задолженностью.',
        qwattTags: ['Исходящие звонки', 'Возврат пауэрбанков'],
        platformEyebrow: 'ОТ ПЕРВОГО СЦЕНАРИЯ ДО РЕАЛЬНЫХ ЗВОНКОВ', platformTitle: 'Вы знаете свой бизнес.\nМы знаем, как его услышать.',
        platformIntro: 'Наша команда настраивает агентов и аналитику под ваши задачи. Вы участвуете в тестировании и получаете понятный результат.',
        previewLabel: 'Схема работы · Syncall', previewNote: 'Иллюстрация процесса',
        tabs: [
            { label: 'Настройка', title: 'Ваши знания.\nГолос вашего бизнеса.', body: 'Собираем ответы, правила и действия агента. Определяем, где он помогает сам, а когда подключает сотрудника.', nodes: ['Входящий звонок', 'Понять вопрос', 'Найти ответ', 'Помочь клиенту'], panel: 'Знания компании', items: ['Вопросы и ответы', 'Правила разговора', 'Передача оператору'] },
            { label: 'Тестирование', title: 'Сначала проверяем.\nЗатем запускаем.', body: 'Проходим реальные ситуации на узбекском и русском. Проверяем ответы и действия, вносим правки вместе с вашей командой.', nodes: ['Тестовый разговор', 'Вопрос клиента', 'Ответ агента', 'Проверка результата'], panel: 'Тестирование агента', items: ['O‘zbekcha', 'Русский', 'Обратная связь'] },
            { label: 'Запуск', title: 'Готов к работе.\nНа вашей линии.', body: 'Подключаем телефонию и нужные системы. Запускаем входящую поддержку или исходящие звонки под конкретную задачу.', nodes: ['Ваша телефония', 'Syncall AI', 'Система компании', 'Результат разговора'], panel: 'Подключения', items: ['Входящие звонки', 'Исходящие звонки', 'Данные компании'] },
            { label: 'Качество', title: 'Каждый разговор —\nвозможность стать лучше.', body: 'Настраиваем критерии оценки: выполнение задачи, соблюдение правил, вопросы клиентов. Помогаем находить точки для улучшения.', nodes: ['Запись разговора', 'Расшифровка', 'Оценка по критериям', 'Обратная связь'], panel: 'Критерии качества', items: ['Соблюдение правил', 'Решение задачи', 'Работа с возражениями'] },
            { label: 'Аналитика', title: 'Из разговоров —\nв понятные решения.', body: 'Собираем темы обращений, итоги и оценки в единую картину. Аналитика работает и с разговорами ваших операторов.', nodes: ['Разговоры', 'Темы обращений', 'Итоги и оценки', 'Решения команды'], panel: 'Что вы узнаете', items: ['Причины обращений', 'Результаты разговоров', 'Качество обслуживания'] },
        ],
        productsEyebrow: 'ОДНА КОМАНДА. БОЛЬШЕ ВОЗМОЖНОСТЕЙ.', productsTitle: 'Голос — только начало.',
        productsIntro: 'Анализируйте звонки, отвечайте в чатах и работайте с речью в Studio.',
        products: [
            { title: 'Речевая аналитика', body: 'Узнайте, что происходит в разговорах с клиентами. Темы, итоги, качество работы AI и операторов.', label: 'Изучить аналитику', badge: 'Настроим с вашей командой', path: '/analytics' },
            { title: 'AI-чатботы', body: 'Ответы на вопросы и помощь клиентам в текстовых каналах. С учётом знаний и задач компании.', label: 'О чатботах', badge: 'Для ваших клиентов', path: '/chatbots' },
            { title: 'Речь в текст', body: 'Загрузите аудио и получите расшифровку. Работайте с узбекской и русской речью самостоятельно.', label: 'Открыть STT в Studio', badge: 'Self-service · Studio', path: '/cabinet/stt' },
            { title: 'Текст в речь', body: 'Превратите текст в голос. Создавайте озвучку на узбекском и русском прямо в Studio.', label: 'Открыть TTS в Studio', badge: 'Self-service · Studio', path: '/cabinet/tts' },
        ],
        faqTitle: 'Хорошие вопросы.\nПрямые ответы.',
        faq: [
            ['Как запустить голосового агента?', 'Сначала попробуйте демо и расскажите о своей задаче. Команда Syncall подготовит агента, поможет с подключениями, проведёт тестирование вместе с вами и запустит звонки.'],
            ['На каких языках можно попробовать демо?', 'Live-демо Poytaxt Parking поддерживает узбекский и русский. Если агент временно недоступен, можно послушать его запись. Для Soft Collection и продаж готовим отдельные аудиопримеры.'],
            ['Можно ли анализировать звонки наших операторов?', 'Да. Речевая аналитика — отдельный продукт. Мы поможем настроить обработку записей и критерии оценки под вашу задачу.'],
            ['Можно ли настроить всё самостоятельно?', 'Голосовых агентов и аналитику пока внедряет наша команда. Распознавание и синтез речи доступны для самостоятельной работы в Studio.'],
            ['Что происходит после демо?', 'Вы можете оставить название компании, задачу и приблизительный объём звонков или минут. Мы свяжемся с вами, чтобы обсудить подходящий вариант запуска.'],
        ],
    },
    en: {
        recordingComingSoon: 'Recording coming soon',
        recordingPending: 'We’re preparing an audio example of this scenario. You can discuss it for your business with us now.',
        recordingNote: 'Listen to how the agent handles this conversation.',
        eyebrow: 'VOICE AI FOR BUSINESS IN UZBEKISTAN', title: ['Every call.', 'In your language.'],
        intro: 'AI agents that support customers, follow up on payments, and sell. In Uzbek and Russian. With an understanding of your business.',
        tryAgent: 'Talk to an AI agent', talkTeam: 'Discuss my use case', languages: 'O‘zbekcha · Русский', heroNote: 'Hear how it works. Try it yourself.',
        trusted: 'Trusted by', demoEyebrow: 'TRY IT FIRST', demoTitle: 'A good conversation\nspeaks for itself.', demoIntro: 'Choose a use case. Try the Poytaxt Parking live demo or listen to a recorded conversation.',
        scenarios: [
            { title: 'Inbound support', description: 'Questions about parking, payments, and rules. The agent answers and helps the customer.', tag: 'Inbound calls', prompt: '“How do I pay for parking?”' },
            { title: 'Soft Collection', description: 'A considerate payment reminder. The agent understands the situation and discusses the next step.', tag: 'Demonstration bank', prompt: '“Can I pay tomorrow?”' },
            { title: 'Outbound sales', description: 'Introduce an offer, answer questions, and connect interested customers with your team.', tag: 'Outbound calls', prompt: '“How would this help my company?”' },
        ],
        demoLanguage: 'Conversation language', phone: 'Your phone number', phoneHint: 'Enter your phone number to talk to an AI operator.', recordingHint: 'You’ll hear a recorded conversation with an AI agent.',
        recordingLabel: 'Inbound call example', outgoingRecordingLabel: 'Outbound call example', sampleNote: 'The Poytaxt Parking live demo is currently unavailable. Listen to a recorded conversation with its support agent.',
        recording: 'Listen to a recording', live: 'Start conversation', checking: 'Checking agent availability…', sampleBadge: 'Recorded conversation', retryLive: 'Check live availability',
        afterTitle: 'Now, for your business.', afterText: 'Tell us what you need. We’ll get in touch to discuss your launch.', saveError: 'We couldn’t send your number. Please try again.', saved: 'Number sent. Play the recording to hear the agent.',
        formTitle: 'Let’s give your\nbusiness a voice.', formIntro: 'Leave a few details. Our team will get in touch, understand your use case, and help launch Syncall.',
        company: 'Company name', companyPlaceholder: 'What is your company called?', useCase: 'What should the agent handle?', useCasePlaceholder: 'For example, customer support or payment reminders', volume: 'Approximate monthly volume', calls: 'Calls', minutes: 'Minutes', submit: 'Discuss a launch', submitting: 'Sending…', success: 'Thank you! We received your request and will be in touch.',
        formNote: 'By submitting, you agree that Syncall may contact you at this number.', invalid: 'Please fill in this field.', invalidPhone: 'Enter a valid Uzbekistan number: +998 and 9 digits.', invalidVolume: 'Enter an approximate amount between 1 and 1,000,000,000.', contactLink: 'Or message us on Telegram',
        storiesEyebrow: 'CUSTOMER STORIES', storiesTitle: 'Results you can hear.\nAnd measure.', storiesIntro: 'From parking to powerbank rentals, we help businesses handle everyday conversations.',
        parkingMetric: '8 in 10', parkingLabel: 'calls resolved by AI without an operator transfer', parkingBody: 'Poytaxt Parking’s AI agent handles inbound calls. On outbound calls, it reminds customers about payments, discusses their situation, and captures the outcome.', parkingTags: ['Customer support', 'Soft Collection'],
        qwattMetric: '+42%', qwattLabel: 'increase in powerbank returns in the first week after integration', qwattBody: 'Qwatt’s AI agent contacts customers about returning powerbanks and helps the team manage collection.', qwattTags: ['Outbound calls', 'Powerbank returns'],
        platformEyebrow: 'FROM THE FIRST SCENARIO TO REAL CALLS', platformTitle: 'You know your business.\nWe help it find its voice.', platformIntro: 'Our team configures agents and analytics around your needs. You take part in testing and see the results.', previewLabel: 'How it works · Syncall', previewNote: 'Process illustration',
        tabs: [
            { label: 'Build', title: 'Your knowledge.\nYour business’s voice.', body: 'We bring together answers, rules, and actions. Define when the agent can help and when a person should take over.', nodes: ['Incoming call', 'Understand the question', 'Find an answer', 'Help the customer'], panel: 'Company knowledge', items: ['Questions and answers', 'Conversation rules', 'Human handoff'] },
            { label: 'Test', title: 'Test with confidence.\nThen go live.', body: 'Try real situations in Uzbek and Russian. Review answers and actions, and make improvements with your team.', nodes: ['Test conversation', 'Customer question', 'Agent response', 'Review the outcome'], panel: 'Test the agent', items: ['O‘zbekcha', 'Русский', 'Team feedback'] },
            { label: 'Deploy', title: 'Ready to work.\nOn your line.', body: 'We connect your telephony and business systems. Launch inbound support or outbound calls for a specific task.', nodes: ['Your telephony', 'Syncall AI', 'Business system', 'Call outcome'], panel: 'Connections', items: ['Inbound calls', 'Outbound calls', 'Business data'] },
            { label: 'Quality', title: 'Every conversation.\nA chance to improve.', body: 'Set criteria for task completion, rules, and customer questions. Find the areas where conversations can improve.', nodes: ['Call recording', 'Transcript', 'Evaluation', 'Feedback'], panel: 'Quality criteria', items: ['Following rules', 'Task completion', 'Handling objections'] },
            { label: 'Analytics', title: 'From conversations\nto clear decisions.', body: 'Bring topics, outcomes, and evaluations together. Analyze your human agents’ conversations, too.', nodes: ['Conversations', 'Topics', 'Outcomes and scores', 'Team decisions'], panel: 'What you learn', items: ['Reasons for calling', 'Conversation outcomes', 'Service quality'] },
        ],
        productsEyebrow: 'ONE TEAM. MORE POSSIBILITIES.', productsTitle: 'Voice is just the beginning.', productsIntro: 'Analyze calls, help customers in chat, and work with speech in Studio.',
        products: [
            { title: 'Speech analytics', body: 'Understand customer conversations: topics, outcomes, and the quality of AI and human agents.', label: 'Explore analytics', badge: 'Set up with your team', path: '/analytics' },
            { title: 'AI chatbots', body: 'Answers and customer support in text channels, built around your company’s knowledge and needs.', label: 'Explore chatbots', badge: 'For your customers', path: '/chatbots' },
            { title: 'Speech to text', body: 'Upload audio and get a transcript. Work with Uzbek and Russian speech yourself.', label: 'Open STT in Studio', badge: 'Self-service · Studio', path: '/cabinet/stt' },
            { title: 'Text to speech', body: 'Turn text into a voice. Create speech in Uzbek and Russian directly in Studio.', label: 'Open TTS in Studio', badge: 'Self-service · Studio', path: '/cabinet/tts' },
        ],
        faqTitle: 'Good questions.\nStraight answers.', faq: [
            ['How do I launch an agent?', 'Try the demo and tell us about your use case. Syncall’s team builds the agent, helps connect your systems, tests it with you, and launches the calls.'],
            ['Which languages are available in the demo?', 'The Poytaxt Parking live demo supports Uzbek and Russian, with a recording available when the agent is offline. Separate audio examples for Soft Collection and sales are coming soon.'],
            ['Can we analyze our operators’ calls?', 'Yes. Speech analytics is a separate product. We help configure recording processing and evaluation criteria for your needs.'],
            ['Can I set everything up myself?', 'Our team currently onboards voice agents and analytics. Speech recognition and speech generation are available as self-service tools in Studio.'],
            ['What happens after the demo?', 'Leave your company, use case, and approximate monthly calls or minutes. We’ll contact you to discuss a suitable launch.'],
        ],
    },
    uz: {
        recordingComingSoon: 'Yozuv tez orada paydo bo‘ladi',
        recordingPending: 'Bu ssenariy uchun audio namuna tayyorlayapmiz. Uni biznesingiz uchun hozirdanoq muhokama qilishingiz mumkin.',
        recordingNote: 'Agent bu ssenariyda suhbatni qanday olib borishini tinglang.',
        eyebrow: 'O‘ZBEKISTON BIZNESI UCHUN OVOZLI AI', title: ['Har bir qo‘ng‘iroq.', 'Sizning tilingizda.'],
        intro: 'Mijozlarga yordam beradigan, to‘lovlarni eslatadigan va sotadigan AI-agentlar. O‘zbek va rus tillarida. Biznesingizni tushungan holda.', tryAgent: 'AI-agent bilan gaplashish', talkTeam: 'Vazifamni muhokama qilish', languages: 'O‘zbekcha · Русский', heroNote: 'Qanday ishlashini eshiting. O‘zingiz sinab ko‘ring.', trusted: 'Bizga ishonishadi',
        demoEyebrow: 'AVVAL SINAB KO‘RING', demoTitle: 'Yaxshi suhbat\no‘zi uchun gapiradi.', demoIntro: 'Vazifani tanlang. Poytaxt Parking jonli demosini sinang yoki suhbat yozuvini tinglang.',
        scenarios: [
            { title: 'Kiruvchi qo‘ng‘iroqlar', description: 'Avtoturargoh, to‘lov va qoidalar haqidagi savollar. Agent javob beradi va mijozga yordam beradi.', tag: 'Kiruvchi qo‘ng‘iroqlar', prompt: '«Avtoturargoh uchun qanday to‘layman?»' },
            { title: 'Soft Collection', description: 'To‘lov haqida muloyim eslatma. Agent vaziyatni aniqlaydi va keyingi qadamni kelishadi.', tag: 'Namoyish uchun bank', prompt: '«Ertaga to‘lasam bo‘ladimi?»' },
            { title: 'Chiquvchi sotuvlar', description: 'Taklif bilan tanishtirish, savollarga javob berish va qiziqqan mijozni jamoaga yo‘naltirish.', tag: 'Chiquvchi qo‘ng‘iroqlar', prompt: '«Bu kompaniyamga qanday yordam beradi?»' },
        ],
        demoLanguage: 'Suhbat tili', phone: 'Telefon raqamingiz', phoneHint: 'AI-operator bilan gaplashish uchun telefon raqamingizni kiriting.', recordingHint: 'AI-agent bilan suhbat yozuvini eshitasiz.', recordingLabel: 'Kiruvchi qo‘ng‘iroq namunasi', outgoingRecordingLabel: 'Chiquvchi qo‘ng‘iroq namunasi', sampleNote: 'Poytaxt Parking jonli demosi hozir mavjud emas. Yordam agenti bilan suhbat yozuvini tinglang.', recording: 'Yozuvni tinglash', live: 'Suhbatni boshlash', checking: 'Agent mavjudligini tekshiryapmiz…', sampleBadge: 'Suhbat yozuvi', retryLive: 'Jonli demoni tekshirish', afterTitle: 'Endi — biznesingiz uchun.', afterText: 'Vazifangizni ayting. Bog‘lanib, ishga tushirishni muhokama qilamiz.', saveError: 'Raqam yuborilmadi. Qayta urinib ko‘ring.', saved: 'Raqam yuborildi. Agentni eshitish uchun yozuvni yoqing.',
        formTitle: 'Biznesingizga\novoz beraylik.', formIntro: 'Bir nechta ma’lumot qoldiring. Jamoamiz bog‘lanadi, vazifani o‘rganadi va Syncall’ni ishga tushirishga yordam beradi.', company: 'Kompaniya nomi', companyPlaceholder: 'Kompaniyangiz qanday nomlanadi?', useCase: 'Agentga qanday vazifa bermoqchisiz?', useCasePlaceholder: 'Masalan, mijozlarga yordam yoki to‘lovlarni eslatish', volume: 'Oyiga taxminiy hajm', calls: 'Qo‘ng‘iroqlar', minutes: 'Daqiqalar', submit: 'Ishga tushirishni muhokama qilish', submitting: 'Yuborilmoqda…', success: 'Rahmat! So‘rovingizni oldik, siz bilan bog‘lanamiz.', formNote: 'So‘rov yuborish orqali Syncall siz bilan ko‘rsatilgan raqamda bog‘lanishiga rozilik bildirasiz.', invalid: 'Ushbu maydonni to‘ldiring.', invalidPhone: 'O‘zbekiston raqamini kiriting: +998 va 9 ta raqam.', invalidVolume: '1 dan 1 000 000 000 gacha taxminiy miqdorni kiriting.', contactLink: 'Yoki Telegram orqali yozing',
        storiesEyebrow: 'MIJOZLARIMIZ TAJRIBASI', storiesTitle: 'Natijani eshiting.\nRaqamlarda ko‘ring.', storiesIntro: 'Avtoturargohlardan pauerbank ijarasigacha — biznesning kundalik vazifalarini hal qilishga yordam beramiz.', parkingMetric: '10 tadan 8 ta', parkingLabel: 'murojaatni AI operatorga o‘tkazmasdan hal qiladi', parkingBody: 'Poytaxt Parking AI-agenti kiruvchi qo‘ng‘iroqlarga javob beradi. Chiquvchi suhbatlarda to‘lovni eslatadi, vaziyatni aniqlaydi va natijani qayd etadi.', parkingTags: ['Mijozlarga yordam', 'Soft Collection'], qwattMetric: '+42%', qwattLabel: 'joriy etilgandan keyingi birinchi haftada pauerbank qaytarishlar o‘sishi', qwattBody: 'Qwatt AI-agenti pauerbanklarni qaytarish bo‘yicha mijozlarga qo‘ng‘iroq qiladi va jamoaga qarzdorlik bilan ishlashda yordam beradi.', qwattTags: ['Chiquvchi qo‘ng‘iroqlar', 'Pauerbanklarni qaytarish'],
        platformEyebrow: 'BIRINCHI SSENARIYDAN HAQIQIY QO‘NG‘IROQLARGACHA', platformTitle: 'Siz biznesingizni bilasiz.\nBiz unga ovoz beramiz.', platformIntro: 'Jamoamiz agentlar va tahlilni vazifangizga moslaydi. Siz sinovlarda qatnashasiz va natijalarni ko‘rasiz.', previewLabel: 'Ishlash jarayoni · Syncall', previewNote: 'Jarayon tasviri',
        tabs: [
            { label: 'Sozlash', title: 'Sizning bilimlaringiz.\nBiznesingizning ovozi.', body: 'Javoblar, qoidalar va amallarni birlashtiramiz. Agent qachon o‘zi yordam berishini, qachon xodimni ulashini belgilaymiz.', nodes: ['Kiruvchi qo‘ng‘iroq', 'Savolni tushunish', 'Javob topish', 'Mijozga yordam'], panel: 'Kompaniya bilimlari', items: ['Savollar va javoblar', 'Suhbat qoidalari', 'Operatorga o‘tkazish'] },
            { label: 'Sinash', title: 'Avval tekshiramiz.\nKeyin ishga tushiramiz.', body: 'O‘zbek va rus tillarida haqiqiy vaziyatlarni sinaymiz. Javob va amallarni tekshirib, jamoangiz bilan yaxshilaymiz.', nodes: ['Sinov suhbati', 'Mijoz savoli', 'Agent javobi', 'Natijani tekshirish'], panel: 'Agentni sinash', items: ['O‘zbekcha', 'Русский', 'Jamoa fikri'] },
            { label: 'Ishga tushirish', title: 'Ishlashga tayyor.\nSizning liniyangizda.', body: 'Telefoniya va kerakli tizimlarni ulaymiz. Aniq vazifa uchun kiruvchi yoki chiquvchi qo‘ng‘iroqlarni boshlaymiz.', nodes: ['Telefoniyangiz', 'Syncall AI', 'Kompaniya tizimi', 'Suhbat natijasi'], panel: 'Ulanishlar', items: ['Kiruvchi qo‘ng‘iroqlar', 'Chiquvchi qo‘ng‘iroqlar', 'Kompaniya ma’lumotlari'] },
            { label: 'Sifat', title: 'Har bir suhbat —\nyaxshilanish imkoniyati.', body: 'Vazifa bajarilishi, qoidalarga rioya va mijoz savollari bo‘yicha mezonlarni sozlaymiz. Yaxshilash nuqtalarini topamiz.', nodes: ['Suhbat yozuvi', 'Matn', 'Mezonlar bo‘yicha baho', 'Fikr-mulohaza'], panel: 'Sifat mezonlari', items: ['Qoidalarga rioya', 'Vazifani bajarish', 'E’tirozlar bilan ishlash'] },
            { label: 'Tahlil', title: 'Suhbatlardan —\naniq qarorlarga.', body: 'Murojaat mavzulari, natijalar va baholarni birlashtiramiz. Operatorlaringiz suhbatlarini ham tahlil qilamiz.', nodes: ['Suhbatlar', 'Murojaat mavzulari', 'Natija va baholar', 'Jamoa qarorlari'], panel: 'Nimalarni bilib olasiz', items: ['Murojaat sabablari', 'Suhbat natijalari', 'Xizmat sifati'] },
        ],
        productsEyebrow: 'BIR JAMOA. KO‘PROQ IMKONIYAT.', productsTitle: 'Ovoz — bu faqat boshlanishi.', productsIntro: 'Qo‘ng‘iroqlarni tahlil qiling, chatlarda javob bering va Studio’da nutq bilan ishlang.',
        products: [
            { title: 'Nutq tahlili', body: 'Mijozlar suhbatlaridagi mavzu, natijalar, AI va operatorlar ish sifatini tushuning.', label: 'Tahlilni o‘rganish', badge: 'Jamoangiz bilan sozlaymiz', path: '/analytics' },
            { title: 'AI-chatbotlar', body: 'Kompaniya bilimlari va vazifalariga mos savollarga javob va matnli yordam.', label: 'Chatbotlar haqida', badge: 'Mijozlaringiz uchun', path: '/chatbots' },
            { title: 'Nutqdan matnga', body: 'Audio yuklang va matn oling. O‘zbek va rus nutqi bilan mustaqil ishlang.', label: 'Studio’da STT ochish', badge: 'Mustaqil · Studio', path: '/cabinet/stt' },
            { title: 'Matndan ovozga', body: 'Matnni ovozga aylantiring. Studio’da o‘zbek va rus tillarida ovoz yarating.', label: 'Studio’da TTS ochish', badge: 'Mustaqil · Studio', path: '/cabinet/tts' },
        ],
        faqTitle: 'Yaxshi savollar.\nAniq javoblar.', faq: [
            ['Ovozli agentni qanday ishga tushiraman?', 'Demoni sinang va vazifangizni ayting. Syncall jamoasi agentni tayyorlaydi, tizimlarni ulashga yordam beradi, siz bilan sinaydi va qo‘ng‘iroqlarni ishga tushiradi.'],
            ['Demoni qaysi tillarda sinash mumkin?', 'Poytaxt Parking jonli demosi o‘zbek va rus tillarini qo‘llab-quvvatlaydi. Agent mavjud bo‘lmasa, uning yozuvini tinglash mumkin. Soft Collection va sotuvlar uchun alohida audio namunalar tayyorlayapmiz.'],
            ['Operatorlarimiz qo‘ng‘iroqlarini tahlil qilsak bo‘ladimi?', 'Ha. Nutq tahlili alohida mahsulot. Yozuvlarni qayta ishlash va baholash mezonlarini vazifangizga mos sozlaymiz.'],
            ['Barchasini o‘zim sozlasam bo‘ladimi?', 'Ovozli agentlar va tahlilni hozircha jamoamiz joriy etadi. Nutqni aniqlash va sintez qilish Studio’da mustaqil ishlash uchun mavjud.'],
            ['Demodan keyin nima bo‘ladi?', 'Kompaniya nomi, vazifa va oylik taxminiy qo‘ng‘iroq yoki daqiqalar hajmini qoldirasiz. Ishga tushirishni muhokama qilish uchun siz bilan bog‘lanamiz.'],
        ],
    },
};
