export const productPageContent = {
    ru: {
        products: ['Голосовые агенты', 'Речевая аналитика', 'AI-чатботы'],
        ecosystem: 'ВОЗМОЖНОСТИ SYNCALL',
        teamSetup: 'Настроим вместе с вашей командой',
        languages: 'Узбекский и русский',
        analyticsTitle: 'Каждый разговор.\nПонятные выводы.',
        analyticsIntro: 'Темы обращений, качество ответов и результат каждого звонка. Превращайте разговоры AI-агентов и сотрудников в понятную картину для бизнеса.',
        analyticsCta: 'Разобрать наши звонки',
        analyticsPreview: 'Посмотреть пример отчёта',
        analyticsCapabilities: 'Услышать больше.\nУвидеть главное.',
        reportEyebrow: 'ИЗ РАЗГОВОРА — В РЕШЕНИЕ',
        reportTitle: 'Вся картина.\nС деталями каждого звонка.',
        reportIntro: 'Переключайте разделы примера: оценка качества, темы обращения и итог разговора. Критерии настроим под вашу команду.',
        reportLabel: 'Иллюстрация отчёта',
        reportTabs: ['Качество', 'Темы', 'Итог'],
        quality: 'Качество разговора',
        scoreUnit: 'из 100',
        topics: ['Оплата парковки', 'Способы оплаты', 'Правила парковки'],
        topicNote: 'Что волнует клиентов',
        outcome: 'Вопрос решён',
        outcomeText: 'Клиент уточнил способы оплаты. Агент объяснил порядок действий и ответил на вопросы.',
        outcomeChecks: ['Причина обращения определена', 'Ответ клиенту дан', 'Следующий шаг согласован'],
        signalInput: 'Разговор', signalOutput: 'Понятный результат',
        deploymentTitle: 'Ваши данные.\nВаш формат работы.',
        deploymentText: 'Облако Syncall или ваша инфраструктура. Вместе определим, где хранятся записи, кто видит отчёты и как устроен доступ.',
        cloud: 'В облаке Syncall', cloudText: 'Поможем с настройкой и подключением. Ваша команда работает с готовым инструментом.',
        onprem: 'На ваших серверах', onpremText: 'Согласуем размещение, подключения и доступ с вашей технической командой.',
        analyticsEndTitle: 'Начнём с ваших\nразговоров.',
        chatTitle: 'На связи с клиентами.\nВ каждом сообщении.',
        chatIntro: 'AI-помощник отвечает по знаниям вашей компании, уточняет запрос и подключает сотрудника, когда нужна его помощь. На узбекском и русском.',
        chatCta: 'Обсудить чатбота',
        chatPreview: 'Посмотреть возможности',
        chatExample: 'Пример переписки',
        chatStatus: 'Знания вашей компании',
        chatMessages: ['Здравствуйте! Как оплатить парковку?', 'Здравствуйте! Выберите парковочную зону в приложении и укажите номер автомобиля.', 'А если нужна помощь с оплатой?', 'Помогу разобраться. Подскажите, на каком шаге возник вопрос?'],
        replay: 'Повторить пример',
        chatFoot: 'Знает ваш бизнес. Помогает вашим клиентам.',
        channels: ['Сайт', 'Telegram', 'Приложение'],
        chatCapabilities: 'Больше, чем\nготовые ответы.',
        chatDeploymentText: 'Облако Syncall или ваши серверы. Вместе определим, где хранятся знания компании и переписка, как устроены подключения и доступ сотрудников.',
        chatEndTitle: 'Ваш бизнес.\nВаш голос в переписке.',
        chatEndText: 'Расскажите, с какими вопросами приходят клиенты. Вместе подготовим знания, сценарии и первый запуск.',
    },
    en: {
        products: ['Voice agents', 'Speech analytics', 'AI chatbots'], ecosystem: 'SYNCALL PRODUCTS',
        teamSetup: 'Set up with your team', languages: 'Uzbek and Russian',
        analyticsTitle: 'Every conversation.\nClear insights.',
        analyticsIntro: 'Customer topics, answer quality, and the outcome of every call. Turn AI and human agents’ conversations into a clear picture for your business.',
        analyticsCta: 'Analyze our calls', analyticsPreview: 'Explore a sample report',
        analyticsCapabilities: 'Hear more.\nSee what matters.',
        reportEyebrow: 'FROM CONVERSATION TO ACTION', reportTitle: 'The full picture.\nDown to every call.',
        reportIntro: 'Explore the sample’s quality, topics, and outcome. We’ll configure the criteria around your team.',
        reportLabel: 'Illustrative report', reportTabs: ['Quality', 'Topics', 'Outcome'], quality: 'Conversation quality', scoreUnit: 'out of 100',
        topics: ['Parking payment', 'Payment methods', 'Parking rules'], topicNote: 'What matters to customers',
        outcome: 'Question resolved', outcomeText: 'The customer asked about payment methods. The agent explained the steps and answered their questions.',
        outcomeChecks: ['Reason for calling identified', 'Customer received an answer', 'Next step agreed'],
        signalInput: 'Conversation', signalOutput: 'A clear outcome',
        deploymentTitle: 'Your data.\nYour way of working.', deploymentText: 'Syncall Cloud or your infrastructure. Together, we define where recordings live, who sees reports, and how access works.',
        cloud: 'In Syncall Cloud', cloudText: 'We help with setup and integrations. Your team works with a ready-to-use tool.',
        onprem: 'On your servers', onpremText: 'We agree on hosting, integrations, and access with your technical team.',
        analyticsEndTitle: 'Start with your\nconversations.',
        chatTitle: 'There for your customers.\nIn every message.',
        chatIntro: 'An AI assistant that answers using your company’s knowledge, understands the request, and brings in a teammate when needed. In Uzbek and Russian.',
        chatCta: 'Discuss a chatbot', chatPreview: 'Explore capabilities', chatExample: 'Example conversation', chatStatus: 'Your company’s knowledge',
        chatMessages: ['Hello! How do I pay for parking?', 'Hello! Select your parking zone in the app and enter your vehicle’s registration number.', 'What if I need help with payment?', 'I can help. Which step are you having trouble with?'],
        replay: 'Replay example', chatFoot: 'Knows your business. Helps your customers.', channels: ['Website', 'Telegram', 'App'],
        chatCapabilities: 'More than\nready-made answers.', chatEndTitle: 'Your business.\nYour voice in every chat.',
        chatDeploymentText: 'Syncall Cloud or your servers. Together, we define where company knowledge and conversations live, how integrations work, and who has access.',
        chatEndText: 'Tell us what your customers ask. Together, we’ll prepare the knowledge, scenarios, and first launch.',
    },
    uz: {
        products: ['Ovozli agentlar', 'Nutq tahlili', 'AI-chatbotlar'], ecosystem: 'SYNCALL IMKONIYATLARI',
        teamSetup: 'Jamoangiz bilan birga sozlaymiz', languages: 'O‘zbek va rus tillarida',
        analyticsTitle: 'Har bir suhbat.\nAniq xulosalar.',
        analyticsIntro: 'Murojaat mavzulari, javoblar sifati va har bir qo‘ng‘iroq natijasi. AI-agentlar va xodimlar suhbatlarini biznesingiz uchun tushunarli ma’lumotga aylantiring.',
        analyticsCta: 'Qo‘ng‘iroqlarimizni tahlil qilish', analyticsPreview: 'Hisobot namunasini ko‘rish',
        analyticsCapabilities: 'Ko‘proq eshiting.\nMuhimini ko‘ring.',
        reportEyebrow: 'SUHBATDAN — QARORGA', reportTitle: 'Umumiy manzara.\nHar bir suhbat tafsilotlari.',
        reportIntro: 'Namunadagi sifat, mavzular va natijani ko‘ring. Mezonlarni jamoangizga moslab sozlaymiz.',
        reportLabel: 'Hisobot namunasi', reportTabs: ['Sifat', 'Mavzular', 'Natija'], quality: 'Suhbat sifati', scoreUnit: '100 dan',
        topics: ['Avtoturargoh to‘lovi', 'To‘lov usullari', 'Avtoturargoh qoidalari'], topicNote: 'Mijozlarni nima qiziqtiradi',
        outcome: 'Savol hal qilindi', outcomeText: 'Mijoz to‘lov usullarini so‘radi. Agent harakatlar tartibini tushuntirdi va savollarga javob berdi.',
        outcomeChecks: ['Murojaat sababi aniqlandi', 'Mijozga javob berildi', 'Keyingi qadam kelishildi'],
        signalInput: 'Suhbat', signalOutput: 'Aniq natija',
        deploymentTitle: 'Sizning ma’lumotlaringiz.\nSizga mos yechim.', deploymentText: 'Syncall buluti yoki o‘z infratuzilmangiz. Yozuvlar qayerda saqlanishi, hisobotlarni kim ko‘rishi va kirish tartibini birga belgilaymiz.',
        cloud: 'Syncall bulutida', cloudText: 'Sozlash va ulashga yordam beramiz. Jamoangiz tayyor vosita bilan ishlaydi.',
        onprem: 'Sizning serverlaringizda', onpremText: 'Joylashtirish, ulanishlar va kirishni texnik jamoangiz bilan kelishamiz.',
        analyticsEndTitle: 'Suhbatlaringizdan\nboshlaymiz.',
        chatTitle: 'Mijozlar bilan aloqada.\nHar bir xabarda.',
        chatIntro: 'Kompaniyangiz bilimlariga tayangan holda javob beradigan, so‘rovni aniqlaydigan va kerak bo‘lganda xodimni ulaydigan AI-yordamchi. O‘zbek va rus tillarida.',
        chatCta: 'Chatbotni muhokama qilish', chatPreview: 'Imkoniyatlarni ko‘rish', chatExample: 'Suhbat namunasi', chatStatus: 'Kompaniyangiz bilimlari',
        chatMessages: ['Assalomu alaykum! Avtoturargoh uchun qanday to‘layman?', 'Assalomu alaykum! Ilovada to‘xtash joyini tanlang va avtomobil raqamini kiriting.', 'To‘lov bo‘yicha yordam kerak bo‘lsa-chi?', 'Yordam beraman. Qaysi bosqichda savol tug‘ildi?'],
        replay: 'Namunani qayta ko‘rish', chatFoot: 'Biznesingizni biladi. Mijozlaringizga yordam beradi.', channels: ['Sayt', 'Telegram', 'Ilova'],
        chatCapabilities: 'Tayyor javoblardan\nko‘proq imkoniyat.', chatEndTitle: 'Sizning biznesingiz.\nHar bir chatda sizning ovozingiz.',
        chatDeploymentText: 'Syncall buluti yoki sizning serverlaringiz. Kompaniya bilimlari va yozishmalar qayerda saqlanishi, ulanishlar va xodimlar kirishini birga belgilaymiz.',
        chatEndText: 'Mijozlaringiz qanday savollar bilan murojaat qilishini ayting. Bilimlar, ssenariylar va birinchi ishga tushirishni birga tayyorlaymiz.',
    },
};
