import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const translations = {
    uz: {
        // Navbar
        home: "Bosh sahifa",
        features: "Nega biz",
        howItWorks: "Ishga tushirish",
        demo: "Demo",
        faq: "FAQ",
        contactSales: "Bog'lanish",

        // Hero
        heroBadge: "O'zbekiston uchun AI yechimlar",
        heroTitle: "Sizning aqlli AI koll-markazingiz 24/7. Tezroq, sifatliroq, arzonroq.",
        heroSubtitle: "O'zbek va rus tillarida qo'ng'iroqlarni bir zumda qayta ishlash. Katta xodimlar va o'qitish xarajatlarisiz rutinani avtomatlashtiring.",
        heroFeature1: "Ovozli agentlar",
        heroFeature2: "Chatbotlar",
        heroFeature3: "Har qanday telefoniya",
        tryDemo: "Demo tinglash",

        // Talk Bot
        talkBotTitle: "AI ovozli agentimiz bilan tanishing",
        talkBotSubtitle: "Ovozimiz qanchalik tabiiy ekanligini o'zingiz eshiting",
        talkBotButton: "Demo tinglash",

        // Partners
        partnersLabel: "Bizning hamkorlar",
        partnersSubtitle: "kompaniyalar bizga ishonadi",

        // Calllog
        calllogTitle: "Real qo'ng'iroqlarimizdan birini tinglang",
        calllogSubtitle: "AI agentimiz haqiqiy mijozlar so'rovlarini qanday hal qilishini eshiting",
        callIncoming: "Kiruvchi qo'ng'iroq",
        callOutgoing: "Chiquvchi qo'ng'iroq",

        // Visual Engine Pipeline
        engineTitle: "Syncall Voice Engine Ishlash Tizimi",
        engineSubtitle: "Bilingval qo'ng'iroqlarni qabul qilishdan boshlab brend ovozida javob qaytarishgacha bo'lgan to'liq avtomatlashtirilgan texnologik zanjir",
        engineCard1Title: "1. Bilingval audio oqim",
        engineCard1Desc: "O'zbek va rus tillarida kiruvchi yoki chiquvchi ovozli oqimni qabul qilish. Shovqinni to'suvchi Voice Isolation fon shovqinlarini to'liq filtrlaydi.",
        engineCard2Title: "2. Nutqni aniqlash (STT & NLU)",
        engineCard2Desc: "O'zbek nutqining lahja va slenglarini, tillar qorishmasini 98% aniqlikda matnga o'tkazish va mijoz niyatini (intent) aniqlash.",
        engineCard3Title: "3. CRM va Tizimlar bilan integratsiya",
        engineCard3Desc: "Delta M va kompaniyangiz CRM ma'lumotlar bazasi bilan xavfsiz On-Premise/Cloud integratsiya orqali mijoz statusini yangilash va tekshirish.",
        engineCard4Title: "4. Yuqori sifatli nutq sintezi (TTS)",
        engineCard4Desc: "Sizning eng yaxshi operatoringiz ovozi klonida, inson nutqidan farq qilmaydigan tabiiy ovoz bilan 0.5 soniyada javob qaytarish.",

        // Features
        featuresTitle: "Syncall ni nima ajratib turadi",
        feature1Stat: "1000+ qo'ng'iroq/min",
        heroLiveAnalysis: "Jonli qo'ng'iroq tahlili",
        voiceCloneMatch: "99.2% moslik",
        feature1TagDialect: "Lahja",
        feature1TagMix: "Aralash til",
        feature1TagSlang: "Sleng",
        feature1Title: "Jonli o'zbek nutqini tushunish",
        feature1Desc: "AI o'zbek tilining barcha lahjalarini va tillarning erkin aralashmasini tushunadi. Tizim murakkab so'zlashuv nutqi, sleng va aksentlarni 96% aniqlik bilan anglaydi.",
        feature2Title: "Tabiiy muloqot va shovqin izolyatsiyasi",
        feature2Desc: "Robotni istalgan vaqtda bo'lish mumkin — u darhol jim bo'ladi va tinglaydi. Shovqinni to'suvchi Voice Isolation texnologiyasi bilan har qanday ko'cha shovqinida ham mijoz ovozini aniq ajratib oladi.",
        feature3Title: "Ma'lumotlar to'liq xavfsizligi",
        feature3Desc: "Tizimni Syncall bulutida yoki o'z serverlaringizda (On-Premise) joylashtiring. Ma'lumotlar xavfsizligiga qat'iy talablarga ega bo'lgan banklar va moliya tashkilotlari uchun ideal yechim.",
        feature4Title: "Kompaniya ovozining klonlanishi",
        feature4Desc: "Biz eng yaxshi xodimingiz ovozining aniq raqamli nusxasini yaratishimiz mumkin. Sizning AI har bir mijoz uchun tanish, yoqimli va professional tarzda jaranglaydi.",
        feature5Title: "CRM & Delta M bilan tayyor integratsiya",
        feature5Desc: "Delta M va boshqa CRM tizimlar bilan tayyor integratsiya. Har bir qo'ng'iroqning batafsil AI-tahlilini oling va tizimingizda ma'lumotlarni avtomatik yangilang.",

        // Numbers
        numbersLabel: "Syncall AI raqamlarda",
        numbersTitle: "Syncall AI bilan biznes samaradorligini oshirish",
        numbersStat1Value: "80%",
        numbersStat1Label: "Birinchi qo'ng'iroqdayoq muammolarni to'liq hal qilish (FCR)",
        numbersStat2Value: "-70%",
        numbersStat2Label: "Koll-markaz operatsion xarajatlarining kamayishi",
        numbersStat3Value: "94%",
        numbersStat3Label: "Mijozlarning umumiy qoniqish ko'rsatkichi (CSAT)",
        numbersDesc: "Syncall AI ning ilg'or ovozli agentlari bilan avtomatlashtirish kuchini his eting — mijozlarga xizmat ko'rsatishni o'zgartiring, xarajatlarni kamaytiring va mijozlar mamnuniyatini oshiring.",
        getStarted: "Boshlash",

        // How
        howTitle: "Ishga tushirish bosqichlari",
        howStep1Title: "Biznes tahlil va mantiq loyihalash",
        howStep1Text: "Muvaffaqiyatli keyslaringiz va so'rovlar xususiyatini o'rganamiz. Tabiiy jaranglagan va biznes vazifalaringizga 100% mos o'zaro ta'sir tuzilmasini yaratamiz.",
        howStep2Title: "Neyrotarmoq modellarini sozlash",
        howStep2Text: "STT, LLM va TTS modellarini biznesingizga moslashtiramiz. Neyrotarmoqni aksentlar, maxsus atamalar va dialoglaringiz kontekstini tushunishga o'rgatamiz.",
        howStep3Title: "Avtomatlashtirilgan test va optimallash",
        howStep3Text: "«Test-bot» orqali bir necha daqiqada minglab qo'ng'iroqlarni simulyatsiya qilamiz. Aniqlik va bir zumda javob berishni kafolatlaymiz.",
        howStep4Title: "Ishga tushirish (Production)",
        howStep4Text: "AI-agentlarni telefoniyangizga ulaymiz. Endi tizim qo'ng'iroqlarni qayta ishlaydi, barcha tahlillar to'g'ridan-to'g'ri CRM tizimingizga tushadi.",

        // FAQ
        faqTitle: "Agentlarimiz haqida batafsil",
        faqQ1: "Kiruvchi va chiquvchi qo'ng'iroqlarni qo'llab-quvvatlaysizmi?",
        faqA1: "Ha, bizning AI ovozli agentlarimiz kiruvchi va chiquvchi qo'ng'iroq stsenariylarini boshqarish uchun mo'ljallangan. Mijozlarning so'rovlarini boshqarish, qo'llab-quvvatlash yoki targ'ibot kampaniyalarini o'tkazish kerakmi, bizning platformamiz operatsion talablaringizga muammosiz moslashadi.",
        faqQ2: "Har qanday turdagi telefoniya bilan integratsiya qilasizmi?",
        faqA2: "Albatta. Bizning platformamiz VoIP provayderlari, PBX tizimlari va bulutga asoslangan yechimlar kabi har qanday telefoniya tizimi bilan integratsiya qilish uchun yaratilgan. Provayderdan yoki texnologiya stekidan qat'i nazar, mavjud infrastrukturangiz bilan silliq muvofiqlikni ta'minlaymiz.",
        faqQ3: "Qaysi tillarni qo'llab-quvvatlaysiz?",
        faqA3: "Biz hozirda o'zbek, rus va ingliz tillarini qo'llab-quvvatlaymiz, har bir til uchun tabiiy aksent moslashuvi bilan. Bizning AI ovozli agentlarimiz mintaqaviy lahjalar va nozikliklarni tushunish uchun o'qitilgan, bu mijozlaringiz bilan haqiqiy va madaniy jihatdan mos suhbatlarni ta'minlaydi.",
        faqQ4: "Bir vaqtning o'zida nechta qo'ng'iroq qilishingiz mumkin?",
        faqA4: "Bizning tomonimizdan hech qanday cheklov yo'q — bizning AI infrastrukturamiz cheksiz miqyosda va har qanday qo'ng'iroqgacha bo'lgan hajmni boshqarish uchun mo'ljallangan. Yagona cheklov telefoniya provayderingizning quvvati bo'lishi mumkin.",
        faqQ5: "Qo'ng'iroq tahlilini taqdim etasizmi?",
        faqA5: "Ha, biz sizga aloqa markazi faoliyatingiz haqida chuqur tushunchalar beradigan keng qamrovli real vaqt qo'ng'iroq tahlilini taklif qilamiz.",
        faqQ6: "Sinov davringiz bormi?",
        faqA6: "Ha, biz aloqa markazingizga transformatsion ta'sirni ko'rsatish uchun bepul sinov taklif qilamiz. Biz sizning biznes ehtiyojlaringizga moslashtirilgan maxsus AI agentini o'qitamiz va uni 1000 qo'ng'iroqgacha bepul sinab ko'rishingiz mumkin.",

        // ===== Product nav (tabs) =====
        navVoiceAgents: "Ovozli agentlar",
        navAnalytics: "Analitika",
        navStt: "STT",
        navTts: "TTS",

        // ===== Products strip =====
        pnLabel: "Syncall AI platformasi",
        pnTitle: "Bitta platforma — to'rtta mahsulot",
        pnSubtitle: "Ovozli agentlardan tortib alohida nutq API'larigacha. Asosiy yo'nalish — Voice Agents, qolganlari esa shu texnologiya ustiga quriladi.",
        pnKindProduct: "Mahsulot",
        pnKindApi: "API",
        pnYouAreHere: "Shu yerda",
        pnVoiceName: "Voice Agents",
        pnVoiceDesc: "Jonli operatordan farq qilmaydigan ovozli AI agentlar — kiruvchi va chiquvchi qo'ng'iroqlar 24/7.",
        pnVoiceStat: "< 1.5s javob · 24/7",
        pnAnalyticsName: "Analytics",
        pnAnalyticsDesc: "Har bir qo'ng'iroqning 100% sifat nazorati — operatorlarni baholash va rahbarga hisobot.",
        pnAnalyticsStat: "100% qamrov",
        pnSttName: "STT",
        pnSttDesc: "O'zbek lahjalari va aralash til uchun nutqni matnga o'tkazish API'si.",
        pnSttStat: "98% aniqlik",
        pnTtsName: "TTS",
        pnTtsDesc: "Tabiiy, inson ovozidan farqsiz nutq sintezi va ovoz klonlash API'si.",
        pnTtsStat: "< 200ms",

        // ===== Shared demo =====
        demoModeLive: "Jonli API",
        demoModeSample: "Demo rejimi",
        demoMicError: "Mikrofondan foydalanib bo'lmadi. Ruxsatni tekshiring.",
        demoApiError: "So'rov bajarilmadi. Birozdan so'ng qayta urinib ko'ring.",
        demoSampleNote: "Bu demo namunaviy natijani ko'rsatmoqda. Jonli API'ni ulash uchun biz bilan bog'laning.",
        demoCtaSecondary: "API'ga ruxsat olish",

        // ===== Analytics page =====
        anBadge: "Analytics — sifat nazorati",
        anHeroTitle: "Sifat bo'limini kengaytirmasdan 100% qo'ng'iroqlarni nazorat qiling",
        anHeroSubtitle: "Syncall Analytics har bir qo'ng'iroqni avtomatik tinglaydi, skript bo'yicha tekshiradi, operatorlarni baholaydi va rahbarga tayyor hisobot beradi.",
        anHeroCta: "Bepul pilotni boshlash",
        anHeroCta2: "Qanday ishlashini ko'rish",
        anScoreCardTitle: "Qo'ng'iroq bahosi",
        anScoreRow1: "Skriptga rioya",
        anScoreRow2: "Muloqot odobi",
        anScoreRow3: "Muammoni hal qilish",
        anScoreRow4: "Sotuv imkoniyati",
        anScoreTagOk: "Salomlashish bajarildi",
        anScoreTagWarn: "E'tirozga javob berilmadi",
        anStat1: "qo'ng'iroqlar nazorati",
        anStat2: "sifat tekshiruvi xarajati",
        anStat3: "uch tilda tahlil",
        anProblemLabel: "Muammo",
        anProblemTitlePre: "Hozir siz faqat",
        anProblemTitlePost: "qo'ng'iroqlarni eshitasiz",
        anProb1Title: "Operator xatolari",
        anProb1Desc: "Tanlab tinglashda ko'pchilik xato va qo'pol javoblar e'tibordan chetda qoladi.",
        anProb2Title: "Yashirin «sotuvsiz»",
        anProb2Desc: "Mijoz nega sotib olmaganini hech kim tahlil qilmaydi va sabablari yo'qoladi.",
        anProb3Title: "Kim haqiqatan ishlaydi?",
        anProb3Desc: "Operatorlarning real samaradorligini ob'ektiv o'lchash imkoni yo'q.",
        anProb4Title: "Sub'ektiv o'qitish",
        anProb4Desc: "Trening shaxsiy taassurotga asoslanadi, aniq ma'lumotlarga emas.",
        anProb5Title: "Shikoyatlar kech keladi",
        anProb5Desc: "Muammoli qo'ng'iroqlar mijoz ketganidan keyin ma'lum bo'ladi.",
        anProb6Title: "Rahbar ko'rmaydi",
        anProb6Desc: "Boshqaruvda real ko'rsatkichlar emas, faqat umumiy taxminlar bor.",
        anPipeLabel: "Jarayon",
        anPipeTitle: "Qo'ng'iroqdan rahbar hisobotigacha — bir necha daqiqada",
        anPipeSubtitle: "To'liq avtomatik tahlil zanjiri, qo'lda tinglashsiz.",
        anPipe1Title: "Qo'ng'iroq",
        anPipe1Desc: "Telefoniya yoki yozuvlardan audio avtomatik yuklanadi.",
        anPipe2Title: "Rasshifrovka",
        anPipe2Desc: "Nutq aniq matnga o'tkaziladi (uzb/rus/ing).",
        anPipe3Title: "Skript bo'yicha tekshirish",
        anPipe3Desc: "Salomlashish, skript va majburiy bosqichlar tekshiriladi.",
        anPipe4Title: "Operator bahosi",
        anPipe4Desc: "Har bir qo'ng'iroq ob'ektiv ball bilan baholanadi.",
        anPipe5Title: "Rahbar hisoboti",
        anPipe5Desc: "Tayyor xulosa va ko'rsatkichlar dashboardga tushadi.",
        anResultsLabel: "Natijalar",
        anResultsTitle: "Tanlama nazoratdan — to'liq va o'lchanadigan nazoratga",
        anResult1: "sifat ballining o'sishi",
        anResult2: "shikoyatlarning kamayishi",
        anResult3: "ko'proq tekshirilgan qo'ng'iroqlar",
        anCtaTitle: "Qo'ng'iroqlaringizning haqiqiy holatini ko'ring",
        anCtaSubtitle: "5–7 kun ichida 500–1000 qo'ng'iroq bo'yicha hisobot tayyorlaymiz: operatorlar, mavzular, xatolar va sifat.",

        // ===== STT page =====
        sttBadge: "Speech-to-Text API",
        sttHeroTitle: "O'zbek nutqini matnga o'giradigan eng aniq STT",
        sttHeroSubtitle: "Lahjalar, sleng va o'zbek-rus aralash nutqi bilan ishlaydigan nutqni aniqlash API'si. Real qo'ng'iroq yozuvlarida o'rgatilgan.",
        sttHeroCta: "API kalitini olish",
        sttSpec1: "aniqlik (lahjalar bilan)",
        sttSpec2: "kechikish (real-time)",
        sttSpec3: "qo'llab-quvvatlanadigan tillar",
        sttSpec4: "uzluksiz oqim",
        sttCapsLabel: "Imkoniyatlar",
        sttCapsTitle: "Mahalliy nutq uchun yaratilgan",
        sttCap1Title: "Lahjalar va aralash til",
        sttCap1Desc: "O'zbek lahjalari, sleng va bir gap ichida o'zbek-rus almashinuvini tushunadi.",
        sttCap2Title: "Shovqinni to'sish",
        sttCap2Desc: "Ko'cha shovqini, musiqa va fon ovozlarini filtrlab, faqat nutqni ajratadi.",
        sttCap3Title: "So'z darajasidagi vaqt belgilari",
        sttCap3Desc: "Har bir so'z uchun aniqlik va vaqt belgisi — analitika va subtitrlar uchun.",
        sttCap4Title: "Streaming va batch",
        sttCap4Desc: "Real vaqtli oqim yoki katta hajmli yozuvlarni ommaviy qayta ishlash.",
        sttUseLabel: "Qo'llanilishi",
        sttUseTitle: "Jamoalar STT'dan qanday foydalanadi",
        sttUse1Title: "Qo'ng'iroqlar tahlili",
        sttUse1Desc: "Yozuvlarni matnga o'girib, sifat va mavzularni avtomatik tahlil qiling.",
        sttUse2Title: "Real-time subtitr",
        sttUse2Desc: "Jonli qo'ng'iroq va uchrashuvlarga bir zumda transkripsiya qo'shing.",
        sttUse3Title: "Ovozli agentlar",
        sttUse3Desc: "Voice Agents uchun tushunish bosqichi — past kechikish bilan.",
        sttCtaTitle: "Nutqni aniq matnga o'giring",
        sttCtaSubtitle: "Audio yuboring, biz aniqlikni o'z ma'lumotlaringizda ko'rsatamiz. API kaliti va narxlar uchun bog'laning.",
        sttDemoTitle: "STT demosini sinab ko'ring",
        sttDemoSubtitle: "Audio yozing, yuklang yoki namunani tanlang — matnga o'giriladi.",
        sttLangLabel: "Til",
        sttInputLabel: "Audio kiriting",
        sttRecord: "Yozib olish",
        sttStop: "To'xtatish",
        sttUpload: "Fayl yuklash",
        sttSample: "Namuna",
        sttRun: "Matnga o'girish",
        sttRunning: "Qayta ishlanmoqda...",
        sttResultLabel: "Transkripsiya",
        sttConfidence: "ishonch",

        // ===== TTS page =====
        ttsBadge: "Text-to-Speech API",
        ttsHeroTitle: "Inson ovozidan farqsiz tabiiy nutq sintezi",
        ttsHeroSubtitle: "Matnni tabiiy ovozga aylantiring yoki eng yaxshi operatoringiz ovozini klonlang. O'zbek, rus va ingliz tillarida past kechikish bilan.",
        ttsHeroCta: "API kalitini olish",
        ttsSpec1: "sintez kechikishi",
        ttsSpec2: "ovoz klonlash mosligi",
        ttsSpec3: "audio sifati",
        ttsSpec4: "tillar",
        ttsCapsLabel: "Imkoniyatlar",
        ttsCapsTitle: "Brendingiz ovozi bilan gapiring",
        ttsCap1Title: "Ovoz klonlash",
        ttsCap1Desc: "30 daqiqalik toza yozuvdan operatoringizning aniq raqamli ovoz nusxasini yaratadi.",
        ttsCap2Title: "Tabiiy intonatsiya",
        ttsCap2Desc: "Inson nutqiga xos urg'u, pauza va ohang bilan jonli jaranglaydi.",
        ttsCap3Title: "Nutqni boshqarish",
        ttsCap3Desc: "Tezlik, ohang va talaffuzni boshqaring — raqamlar va atamalar to'g'ri o'qiladi.",
        ttsCap4Title: "Past kechikishli streaming",
        ttsCap4Desc: "Real vaqtli dialoglar uchun audio oqim — javob 200ms ichida boshlanadi.",
        ttsUseLabel: "Qo'llanilishi",
        ttsUseTitle: "Jamoalar TTS'dan qanday foydalanadi",
        ttsUse1Title: "Ovozli agentlar",
        ttsUse1Desc: "Voice Agents javoblarini tabiiy ovozda sintez qiladi.",
        ttsUse2Title: "IVR va e'lonlar",
        ttsUse2Desc: "Dinamik IVR menyu va xabarnomalarni real vaqtda yarating.",
        ttsUse3Title: "Kontent ovozi",
        ttsUse3Desc: "Audiogid, ta'lim va marketing kontenti uchun ovoz.",
        ttsCtaTitle: "Brendingizga ovoz bering",
        ttsCtaSubtitle: "Ovozni klonlash va API integratsiyasi uchun biz bilan bog'laning.",
        ttsDemoTitle: "TTS demosini sinab ko'ring",
        ttsDemoSubtitle: "Matn kiriting, ovozni tanlang — nutqqa aylantiramiz.",
        ttsVoiceLabel: "Ovoz",
        ttsVoiceAziza: "Aziza",
        ttsVoiceJahongir: "Jahongir",
        ttsVoiceDmitry: "Dmitriy",
        ttsVoiceEmma: "Emma",
        ttsTextLabel: "Matn",
        ttsUseSample: "Namuna matn",
        ttsRun: "Ovozga aylantirish",
        ttsRunning: "Sintez qilinmoqda...",
        ttsSampleUz: "Assalomu alaykum! Syncall AI bilan bog'langaningiz uchun rahmat. Sizga qanday yordam bera olaman?",
        ttsSampleRu: "Здравствуйте! Спасибо за обращение в Syncall AI. Чем я могу вам помочь?",
        ttsSampleEn: "Hello! Thanks for contacting Syncall AI. How can I help you today?",

        // Footer
        footerRights: "Barcha huquqlar himoyalangan",
    },
    ru: {
        // Navbar
        home: "Главная",
        features: "Почему мы",
        howItWorks: "Этапы запуска",
        demo: "Демо",
        faq: "FAQ",
        contactSales: "Связаться",

        // Hero
        heroBadge: "AI решения для Узбекистана",
        heroTitle: "Ваш умный AI колл-центр 24/7. Быстрее, качественнее, дешевле.",
        heroSubtitle: "Мгновенная обработка звонков на узбекском и русском языках. Автоматизируйте рутину без затрат на огромный штат и обучение.",
        heroFeature1: "Голосовые агенты",
        heroFeature2: "Чатботы",
        heroFeature3: "Любая телефония",
        tryDemo: "Послушать демо",

        // Talk Bot
        talkBotTitle: "Познакомьтесь с нашим AI голосовым агентом",
        talkBotSubtitle: "Послушайте сами, насколько естественно звучит наш AI",
        talkBotButton: "Послушать демо",

        // Partners
        partnersLabel: "Наши партнёры",
        partnersSubtitle: "компаний нам доверяют",

        // Calllog
        calllogTitle: "Послушайте реальный звонок нашего AI",
        calllogSubtitle: "Услышьте, как наш AI агент решает настоящие проблемы и вопросы клиентов",
        callIncoming: "Входящий звонок",
        callOutgoing: "Исходящий звонок",

        // Visual Engine Pipeline
        engineTitle: "Технологический Стек Голосового Движка Syncall",
        engineSubtitle: "Автоматизированный цикл обработки звонка: от аудиопотока до генерации ответа бренд войсом",
        engineCard1Title: "1. Двусторонний аудиопоток",
        engineCard1Desc: "Приём входящего или осуществление исходящего звонка. Встроенная технология Voice Isolation мгновенно фильтрует фоновые шумы и музыку.",
        engineCard2Title: "2. Распознавание и Анализ (STT & NLU)",
        engineCard2Desc: "Перевод двуязычной речи (рус/узб) с учётом диалектов, акцентов и разговорного сленга в текст с точностью 98% и распознавание намерений.",
        engineCard3Title: "3. Интеграция с CRM и Delta M",
        engineCard3Desc: "Безопасное соединение (On-Premise или защищенное облако) с базами данных вашей CRM для проверки статусов и автоматического обновления записей.",
        engineCard4Title: "4. Естественный синтез голоса (TTS)",
        engineCard4Desc: "Генерация ответа за 0.5 секунды цифровым клоном вашего лучшего оператора. Голос звучит абсолютно естественно и дружелюбно.",

        // Features
        featuresTitle: "Что делает Syncall особенным",
        feature1Stat: "1000+ звонков/мин",
        heroLiveAnalysis: "Анализ звонков",
        voiceCloneMatch: "99.2% схожесть",
        feature1TagDialect: "Диалекты",
        feature1TagMix: "Микс языков",
        feature1TagSlang: "Сленг",
        feature1Title: "Понимание живой узбекской и русской речи",
        feature1Desc: "ИИ понимает все диалекты узбекского и свободное смешивание языков (узб/рус). Система распознаёт разговорную речь, сленг и акценты с точностью до 96%.",
        feature2Title: "Естественный диалог и шумоподавление",
        feature2Desc: "Робота можно перебивать в любой момент — он мгновенно замолкает и слушает. Благодаря встроенной Voice Isolation, ИИ игнорирует уличный шум, концентрируясь только на голосе клиента.",
        feature3Title: "Абсолютная безопасность данных",
        feature3Desc: "Возможность локального развертывания на ваших серверах (On-Premise) или в защищенном облаке Syncall. Идеальное решение для банков и финтех-компаний с жесткими требованиями к безопасности.",
        feature4Title: "Клонирование голоса бренда",
        feature4Desc: "Мы создаем точную цифровую копию голоса вашего лучшего сотрудника. Ваш ИИ-агент звучит привычно, дружелюбно и на 100% профессионально для каждого клиента.",
        feature5Title: "Готовая интеграция с CRM и Delta M",
        feature5Desc: "Готовая интеграция с Delta M и другими CRM. Автоматически получайте подробный ИИ-анализ каждого звонка и мгновенно обновляйте данные в вашей системе.",

        // Numbers
        numbersLabel: "Syncall AI в цифрах",
        numbersTitle: "Ускорение бизнес-показателей с Syncall AI",
        numbersStat1Value: "80%",
        numbersStat1Label: "Уровень успешного решения вопросов при первом контакте (FCR)",
        numbersStat2Value: "-70%",
        numbersStat2Label: "Снижение расходов на поддержку клиентов",
        numbersStat3Value: "94%",
        numbersStat3Label: "Средний показатель CSAT после внедрения Syncall",
        numbersDesc: "Ощутите силу автоматизации с продвинутыми голосовыми агентами Syncall AI — трансформируйте клиентскую поддержку, снизьте затраты и повысьте удовлетворённость клиентов.",
        getStarted: "Начать",

        // How
        howTitle: "Этапы запуска",
        howStep1Title: "Анализ процессов и проектирование логики",
        howStep1Text: "Изучаем ваши успешные кейсы и специфику запросов. Создаем структуру взаимодействия, которая звучит естественно и на 100% соответствует бизнес-задачам.",
        howStep2Title: "Настройка и адаптация нейросетей",
        howStep2Text: "Адаптируем STT, LLM и TTS модели под ваш бизнес. Тренируем нейросеть понимать акценты, специфические термины и контекст ваших диалогов.",
        howStep3Title: "Автоматизированное стресс-тестирование",
        howStep3Text: "Имитируем тысячи звонков за минуты через тестовых ботов. Гарантируем стабильность, точность ответов и нулевую задержку.",
        howStep4Title: "Запуск в продакшн",
        howStep4Text: "Подключаем AI-агентов к вашей телефонии. Теперь система обрабатывает звонки, а вся аналитика сразу падает в вашу CRM.",

        // FAQ
        faqTitle: "Всё о наших агентах",
        faqQ1: "Поддерживаете ли вы входящие и исходящие звонки?",
        faqA1: "Да, наши AI голосовые агенты разработаны для обработки как входящих, так и исходящих звонков. Нужно ли вам управлять запросами клиентов, предоставлять поддержку или проводить кампании по привлечению клиентов, наша платформа легко адаптируется к вашим операционным требованиям.",
        faqQ2: "Вы интегрируетесь с любым типом телефонии?",
        faqA2: "Абсолютно. Наша платформа создана для интеграции с любой телефонной системой, включая VoIP-провайдеров, PBX-системы и облачные решения. Мы обеспечиваем плавную совместимость с вашей существующей инфраструктурой, независимо от провайдера или технологического стека.",
        faqQ3: "Какие языки вы поддерживаете?",
        faqA3: "В настоящее время мы поддерживаем узбекский, русский и английский языки с естественной адаптацией акцента для каждого языка. Наши AI голосовые агенты обучены понимать региональные диалекты и нюансы.",
        faqQ4: "Сколько звонков вы можете совершать одновременно?",
        faqA4: "С нашей стороны нет ограничений — наша AI-инфраструктура разработана для бесконечного масштабирования и обработки любого объёма звонков. Единственным ограничением может быть пропускная способность вашего телефонного провайдера.",
        faqQ5: "Предоставляете ли вы аналитику звонков?",
        faqA5: "Да, мы предлагаем комплексную аналитику звонков в реальном времени, которая даёт вам глубокое понимание работы вашего контакт-центра.",
        faqQ6: "У вас есть тестовый период?",
        faqA6: "Да, мы предлагаем бесплатную пробную версию. Мы обучим индивидуального AI-агента, адаптированного к потребностям вашего бизнеса, и вы сможете протестировать его бесплатно на 1000 звонков.",

        // ===== Product nav (tabs) =====
        navVoiceAgents: "Голосовые агенты",
        navAnalytics: "Аналитика",
        navStt: "STT",
        navTts: "TTS",

        // ===== Products strip =====
        pnLabel: "Платформа Syncall AI",
        pnTitle: "Одна платформа — четыре продукта",
        pnSubtitle: "От голосовых агентов до отдельных речевых API. Главный фокус — Voice Agents, остальные продукты строятся на той же технологии.",
        pnKindProduct: "Продукт",
        pnKindApi: "API",
        pnYouAreHere: "Вы здесь",
        pnVoiceName: "Voice Agents",
        pnVoiceDesc: "Голосовые ИИ-агенты, неотличимые от живого оператора — входящие и исходящие звонки 24/7.",
        pnVoiceStat: "ответ < 1.5с · 24/7",
        pnAnalyticsName: "Analytics",
        pnAnalyticsDesc: "Контроль качества 100% звонков — оценка операторов и готовый отчёт руководителю.",
        pnAnalyticsStat: "100% охват",
        pnSttName: "STT",
        pnSttDesc: "API распознавания речи для узбекских диалектов и смешанной речи.",
        pnSttStat: "98% точность",
        pnTtsName: "TTS",
        pnTtsDesc: "API синтеза речи и клонирования голоса, неотличимого от человеческого.",
        pnTtsStat: "< 200мс",

        // ===== Shared demo =====
        demoModeLive: "Live API",
        demoModeSample: "Демо-режим",
        demoMicError: "Не удалось получить доступ к микрофону. Проверьте разрешения.",
        demoApiError: "Запрос не выполнен. Попробуйте ещё раз.",
        demoSampleNote: "Демо показывает образец результата. Для подключения live API свяжитесь с нами.",
        demoCtaSecondary: "Получить доступ к API",

        // ===== Analytics page =====
        anBadge: "Analytics — контроль качества",
        anHeroTitle: "Контроль 100% звонков без расширения отдела качества",
        anHeroSubtitle: "Syncall Analytics автоматически прослушивает каждый звонок, проверяет по скрипту, оценивает операторов и формирует готовый отчёт руководителю.",
        anHeroCta: "Запустить бесплатный пилот",
        anHeroCta2: "Посмотреть, как работает",
        anScoreCardTitle: "Оценка звонка",
        anScoreRow1: "Соблюдение скрипта",
        anScoreRow2: "Культура общения",
        anScoreRow3: "Решение вопроса",
        anScoreRow4: "Потенциал продажи",
        anScoreTagOk: "Приветствие выполнено",
        anScoreTagWarn: "Возражение не отработано",
        anStat1: "контроль звонков",
        anStat2: "стоимость проверки качества",
        anStat3: "анализ на трёх языках",
        anProblemLabel: "Проблема",
        anProblemTitlePre: "Сейчас вы слышите только",
        anProblemTitlePost: "звонков",
        anProb1Title: "Ошибки операторов",
        anProb1Desc: "При выборочном прослушивании большинство ошибок и грубостей остаются незамеченными.",
        anProb2Title: "Скрытые «не купил»",
        anProb2Desc: "Никто не разбирает, почему клиент не купил — причины теряются.",
        anProb3Title: "Кто реально работает?",
        anProb3Desc: "Нет объективной метрики реальной эффективности операторов.",
        anProb4Title: "Субъективное обучение",
        anProb4Desc: "Тренинг строится на личных впечатлениях, а не на данных.",
        anProb5Title: "Жалобы приходят поздно",
        anProb5Desc: "О проблемных звонках узнают уже после ухода клиента.",
        anProb6Title: "Руководитель не видит",
        anProb6Desc: "В управлении только общие догадки вместо реальных показателей.",
        anPipeLabel: "Процесс",
        anPipeTitle: "От звонка до отчёта руководителю — за минуты",
        anPipeSubtitle: "Полностью автоматический конвейер анализа, без ручного прослушивания.",
        anPipe1Title: "Звонок",
        anPipe1Desc: "Аудио автоматически загружается из телефонии или записей.",
        anPipe2Title: "Расшифровка",
        anPipe2Desc: "Речь переводится в точный текст (узб/рус/англ).",
        anPipe3Title: "Проверка по скрипту",
        anPipe3Desc: "Проверяются приветствие, скрипт и обязательные этапы.",
        anPipe4Title: "Оценка оператора",
        anPipe4Desc: "Каждый звонок получает объективный балл.",
        anPipe5Title: "Отчёт руководителю",
        anPipe5Desc: "Готовые выводы и метрики попадают в дашборд.",
        anResultsLabel: "Результаты",
        anResultsTitle: "Из выборочного контроля — в сплошной и измеримый",
        anResult1: "рост балла качества",
        anResult2: "снижение жалоб",
        anResult3: "больше проверенных звонков",
        anCtaTitle: "Увидьте реальную картину ваших звонков",
        anCtaSubtitle: "За 5–7 дней подготовим отчёт по 500–1000 звонкам: операторы, темы, ошибки и качество.",

        // ===== STT page =====
        sttBadge: "Speech-to-Text API",
        sttHeroTitle: "Самое точное распознавание узбекской речи",
        sttHeroSubtitle: "API распознавания речи, которое работает с диалектами, сленгом и узбекско-русским код-свитчингом. Обучено на реальных записях звонков.",
        sttHeroCta: "Получить API-ключ",
        sttSpec1: "точность (с диалектами)",
        sttSpec2: "задержка (real-time)",
        sttSpec3: "поддерживаемые языки",
        sttSpec4: "непрерывный поток",
        sttCapsLabel: "Возможности",
        sttCapsTitle: "Создано для живой речи",
        sttCap1Title: "Диалекты и смешанная речь",
        sttCap1Desc: "Понимает узбекские диалекты, сленг и переключение узб/рус внутри одной фразы.",
        sttCap2Title: "Шумоподавление",
        sttCap2Desc: "Отсекает уличный шум, музыку и фон, выделяя только голос.",
        sttCap3Title: "Тайм-коды на уровне слов",
        sttCap3Desc: "Точность и временная метка для каждого слова — для аналитики и субтитров.",
        sttCap4Title: "Streaming и batch",
        sttCap4Desc: "Поток в реальном времени или массовая обработка больших объёмов записей.",
        sttUseLabel: "Применение",
        sttUseTitle: "Как команды используют STT",
        sttUse1Title: "Аналитика звонков",
        sttUse1Desc: "Переводите записи в текст и автоматически анализируйте качество и темы.",
        sttUse2Title: "Субтитры в реальном времени",
        sttUse2Desc: "Добавляйте мгновенную транскрипцию к живым звонкам и встречам.",
        sttUse3Title: "Голосовые агенты",
        sttUse3Desc: "Этап понимания для Voice Agents с минимальной задержкой.",
        sttCtaTitle: "Превратите речь в точный текст",
        sttCtaSubtitle: "Пришлите аудио — покажем точность на ваших данных. Свяжитесь для API-ключа и цен.",
        sttDemoTitle: "Попробуйте STT-демо",
        sttDemoSubtitle: "Запишите, загрузите аудио или выберите образец — переведём в текст.",
        sttLangLabel: "Язык",
        sttInputLabel: "Аудио на входе",
        sttRecord: "Записать",
        sttStop: "Стоп",
        sttUpload: "Загрузить файл",
        sttSample: "Образец",
        sttRun: "Распознать",
        sttRunning: "Обработка...",
        sttResultLabel: "Транскрипция",
        sttConfidence: "уверенность",

        // ===== TTS page =====
        ttsBadge: "Text-to-Speech API",
        ttsHeroTitle: "Синтез речи, неотличимый от человеческого голоса",
        ttsHeroSubtitle: "Превращайте текст в естественную речь или клонируйте голос вашего лучшего оператора. Узбекский, русский и английский с низкой задержкой.",
        ttsHeroCta: "Получить API-ключ",
        ttsSpec1: "задержка синтеза",
        ttsSpec2: "схожесть клона голоса",
        ttsSpec3: "качество аудио",
        ttsSpec4: "языки",
        ttsCapsLabel: "Возможности",
        ttsCapsTitle: "Говорите голосом вашего бренда",
        ttsCap1Title: "Клонирование голоса",
        ttsCap1Desc: "Создаёт точную цифровую копию голоса оператора из 30 минут чистой записи.",
        ttsCap2Title: "Естественная интонация",
        ttsCap2Desc: "Живое звучание с ударениями, паузами и интонацией, как у человека.",
        ttsCap3Title: "Управление речью",
        ttsCap3Desc: "Контроль скорости, тона и произношения — числа и термины читаются верно.",
        ttsCap4Title: "Streaming с низкой задержкой",
        ttsCap4Desc: "Поток аудио для диалогов в реальном времени — ответ стартует за 200мс.",
        ttsUseLabel: "Применение",
        ttsUseTitle: "Как команды используют TTS",
        ttsUse1Title: "Голосовые агенты",
        ttsUse1Desc: "Синтезирует ответы Voice Agents естественным голосом.",
        ttsUse2Title: "IVR и оповещения",
        ttsUse2Desc: "Создавайте динамические IVR-меню и уведомления в реальном времени.",
        ttsUse3Title: "Озвучка контента",
        ttsUse3Desc: "Голос для аудиогидов, обучения и маркетингового контента.",
        ttsCtaTitle: "Дайте вашему бренду голос",
        ttsCtaSubtitle: "Свяжитесь с нами для клонирования голоса и интеграции API.",
        ttsDemoTitle: "Попробуйте TTS-демо",
        ttsDemoSubtitle: "Введите текст, выберите голос — озвучим.",
        ttsVoiceLabel: "Голос",
        ttsVoiceAziza: "Азиза",
        ttsVoiceJahongir: "Жахонгир",
        ttsVoiceDmitry: "Дмитрий",
        ttsVoiceEmma: "Эмма",
        ttsTextLabel: "Текст",
        ttsUseSample: "Образец текста",
        ttsRun: "Озвучить",
        ttsRunning: "Синтез...",
        ttsSampleUz: "Assalomu alaykum! Syncall AI bilan bog'langaningiz uchun rahmat. Sizga qanday yordam bera olaman?",
        ttsSampleRu: "Здравствуйте! Спасибо за обращение в Syncall AI. Чем я могу вам помочь?",
        ttsSampleEn: "Hello! Thanks for contacting Syncall AI. How can I help you today?",

        // Footer
        footerRights: "Все права защищены",
    },
    en: {
        // Navbar
        home: "Home",
        features: "Why us",
        howItWorks: "Launch",
        demo: "Demo",
        faq: "FAQ",
        contactSales: "Contact",

        // Hero
        heroBadge: "AI Solutions for Uzbekistan",
        heroTitle: "Your smart AI call center 24/7. Faster, better, cheaper.",
        heroSubtitle: "Instant call handling in Uzbek and Russian. Automate routine without the costs of a large staff and training.",
        heroFeature1: "Voice Agents",
        heroFeature2: "Chatbots",
        heroFeature3: "Any Telephony",
        tryDemo: "Listen to Demo",

        // Talk Bot
        talkBotTitle: "Experience our AI Voice Agent",
        talkBotSubtitle: "Hear for yourself how natural our AI sounds",
        talkBotButton: "Listen to Demo",

        // Partners
        partnersLabel: "Our Partners",
        partnersSubtitle: "companies trust us",

        // Calllog
        calllogTitle: "Listen to one of our AI calls",
        calllogSubtitle: "Hear how our AI agent handles real-life customer inquiries and problems",
        callIncoming: "Incoming call",
        callOutgoing: "Outgoing call",

        // Visual Engine Pipeline
        engineTitle: "Syncall Voice Engine Technology Stack",
        engineSubtitle: "An automated end-to-end call processing system: from bilateral audio stream to branded speech synthesis",
        engineCard1Title: "1. Dual Audio Stream",
        engineCard1Desc: "Receives inbound or performs outbound calls. Integrated Voice Isolation automatically filters out background music and noise.",
        engineCard2Title: "2. Recognition & Analysis (STT & NLU)",
        engineCard2Desc: "Transcribes bilingual speech (Uzbek/Russian) accounting for local dialects and mixed-language slang with 98% accuracy.",
        engineCard3Title: "3. CRM & Delta M Integration",
        engineCard3Desc: "Secure connection (On-Premise or Private Cloud) with your CRM database to retrieve profiles and instantly update records.",
        engineCard4Title: "4. Human-like Speech Synthesis (TTS)",
        engineCard4Desc: "Generates high-fidelity voice responses under 0.5s cloned from your top agent, creating comfortable and natural customer experiences.",

        // Features
        featuresTitle: "What makes Syncall special",
        feature1Stat: "1000+ calls/min",
        heroLiveAnalysis: "Live call analysis",
        voiceCloneMatch: "99.2% match",
        feature1TagDialect: "Dialects",
        feature1TagMix: "Language mix",
        feature1TagSlang: "Slang",
        feature1Title: "Native speech understanding",
        feature1Desc: "Our AI understands all Uzbek dialects and free bilingual mixing (Uzbek/Russian). It parses slang, accent variations, and colloquialisms with 96% accuracy.",
        feature2Title: "Natural conversation and interruption handling",
        feature2Desc: "Customers can interrupt the AI agent at any point — it immediately stops speaking to listen. Armed with Voice Isolation, it filters street noises to focus solely on the user.",
        feature3Title: "Enterprise-grade data security",
        feature3Desc: "Deploy in Syncall's secured cloud environment or completely on your own servers (On-Premise). Perfect for banks, fintech, and large enterprises with tight data privacy guidelines.",
        feature4Title: "Branded voice cloning",
        feature4Desc: "We create an identical digital voice clone of your top agent. Your AI sounds familiar, welcoming, and 100% professional to every customer.",
        feature5Title: "Turnkey CRM & Delta M integration",
        feature5Desc: "Ready-made integrations with Delta M and popular CRM software. Automatically receive detailed AI-summarized insights and update records on every call.",

        // Numbers
        numbersLabel: "Syncall AI in Numbers",
        numbersTitle: "Accelerating Success with Syncall AI",
        numbersStat1Value: "80%",
        numbersStat1Label: "First Contact Resolution (FCR) rate achieved by our AI",
        numbersStat2Value: "-70%",
        numbersStat2Label: "Reduction in customer support operational overhead",
        numbersStat3Value: "94%",
        numbersStat3Label: "Average Customer Satisfaction (CSAT) rating after implementation",
        numbersDesc: "Leverage the power of automation with Syncall AI's advanced voice agents — transform customer support, cut costs, and boost customer satisfaction.",
        getStarted: "Get Started",

        // How
        howTitle: "Launch steps",
        howStep1Title: "Process analysis and workflow design",
        howStep1Text: "We analyze your top customer workflows and historical calls. We map a conversation flow that is completely natural and 100% matches your business rules.",
        howStep2Title: "Neural model tuning & adaptation",
        howStep2Text: "We customize STT, LLM, and TTS models for your business. We train the models on dialects, product names, accents, and context.",
        howStep3Title: "Automated simulation & stress-test",
        howStep3Text: "We simulate thousands of concurrent calls within minutes using virtual test agents to ensure zero delay and absolute reliability.",
        howStep4Title: "Production launch",
        howStep4Text: "We connect our AI agents directly to your phone lines. The system starts taking calls, and structured logs flow straight into your CRM.",

        // FAQ
        faqTitle: "Everything About Our Agents",
        faqQ1: "Do you support both incoming and outgoing calls?",
        faqA1: "Yes, our AI voice agents are designed to handle both inbound and outbound call scenarios. Whether you need to manage customer inquiries, provide support, or conduct outreach campaigns, our platform seamlessly adapts to your operational requirements.",
        faqQ2: "Do you integrate with any type of telephony?",
        faqA2: "Absolutely. Our platform is built to integrate with any telephony system, including VoIP providers, PBX systems, and cloud-based solutions. We ensure smooth compatibility with your existing infrastructure, regardless of the provider or technology stack.",
        faqQ3: "What languages do you support?",
        faqA3: "We currently support Uzbek, Russian, and English, with natural accent adaptation for each language. Our AI voice agents are trained to understand regional dialects and nuances.",
        faqQ4: "How many calls can you make simultaneously?",
        faqA4: "There are no limitations on our end — our AI infrastructure is designed to scale infinitely and handle any call volume. The only constraint would be your telephony provider's capacity.",
        faqQ5: "Do you provide call analytics?",
        faqA5: "Yes, we offer comprehensive real-time call analytics that give you deep insights into your call center operations.",
        faqQ6: "Do you have a test period?",
        faqA6: "Yes, we offer a complimentary trial. We'll train a custom AI agent tailored to your business needs, and you can test it free of charge for up to 1,000 calls.",

        // ===== Product nav (tabs) =====
        navVoiceAgents: "Voice Agents",
        navAnalytics: "Analytics",
        navStt: "STT",
        navTts: "TTS",

        // ===== Products strip =====
        pnLabel: "The Syncall AI platform",
        pnTitle: "One platform — four products",
        pnSubtitle: "From voice agents to standalone speech APIs. Voice Agents is the main focus; the rest are built on the same technology stack.",
        pnKindProduct: "Product",
        pnKindApi: "API",
        pnYouAreHere: "You're here",
        pnVoiceName: "Voice Agents",
        pnVoiceDesc: "Voice AI agents indistinguishable from a live operator — inbound and outbound calls, 24/7.",
        pnVoiceStat: "< 1.5s reply · 24/7",
        pnAnalyticsName: "Analytics",
        pnAnalyticsDesc: "Quality control on 100% of calls — operator scoring and a ready report for managers.",
        pnAnalyticsStat: "100% coverage",
        pnSttName: "STT",
        pnSttDesc: "Speech-to-text API for Uzbek dialects and mixed-language speech.",
        pnSttStat: "98% accuracy",
        pnTtsName: "TTS",
        pnTtsDesc: "Speech synthesis and voice-cloning API, indistinguishable from a human voice.",
        pnTtsStat: "< 200ms",

        // ===== Shared demo =====
        demoModeLive: "Live API",
        demoModeSample: "Demo mode",
        demoMicError: "Couldn't access the microphone. Check your permissions.",
        demoApiError: "Request failed. Please try again.",
        demoSampleNote: "This demo shows a sample result. Contact us to connect the live API.",
        demoCtaSecondary: "Request API access",

        // ===== Analytics page =====
        anBadge: "Analytics — quality control",
        anHeroTitle: "Control 100% of calls without growing your QA team",
        anHeroSubtitle: "Syncall Analytics automatically listens to every call, checks it against your script, scores operators, and delivers a ready-made report to managers.",
        anHeroCta: "Start a free pilot",
        anHeroCta2: "See how it works",
        anScoreCardTitle: "Call score",
        anScoreRow1: "Script adherence",
        anScoreRow2: "Communication",
        anScoreRow3: "Issue resolution",
        anScoreRow4: "Sales potential",
        anScoreTagOk: "Greeting completed",
        anScoreTagWarn: "Objection not handled",
        anStat1: "of calls controlled",
        anStat2: "cost of quality checks",
        anStat3: "analysis in three languages",
        anProblemLabel: "The problem",
        anProblemTitlePre: "Right now you only hear",
        anProblemTitlePost: "of calls",
        anProb1Title: "Operator mistakes",
        anProb1Desc: "With sampling, most errors and rude replies go completely unnoticed.",
        anProb2Title: "Hidden \"no sale\"",
        anProb2Desc: "Nobody reviews why a customer didn't buy — the reasons are lost.",
        anProb3Title: "Who actually performs?",
        anProb3Desc: "There's no objective metric for operators' real effectiveness.",
        anProb4Title: "Subjective training",
        anProb4Desc: "Coaching is based on personal impressions, not data.",
        anProb5Title: "Complaints arrive late",
        anProb5Desc: "You learn about problem calls only after the customer is gone.",
        anProb6Title: "Managers can't see",
        anProb6Desc: "Leadership runs on guesses instead of real metrics.",
        anPipeLabel: "The process",
        anPipeTitle: "From call to a manager's report — in minutes",
        anPipeSubtitle: "A fully automated analysis pipeline, with no manual listening.",
        anPipe1Title: "Call",
        anPipe1Desc: "Audio is loaded automatically from telephony or recordings.",
        anPipe2Title: "Transcription",
        anPipe2Desc: "Speech is converted to accurate text (Uzbek/Russian/English).",
        anPipe3Title: "Script check",
        anPipe3Desc: "Greeting, script, and mandatory steps are verified.",
        anPipe4Title: "Operator scoring",
        anPipe4Desc: "Every call gets an objective score.",
        anPipe5Title: "Manager report",
        anPipe5Desc: "Ready conclusions and metrics land in the dashboard.",
        anResultsLabel: "Results",
        anResultsTitle: "From sampled control to full and measurable coverage",
        anResult1: "rise in quality score",
        anResult2: "fewer complaints",
        anResult3: "more calls reviewed",
        anCtaTitle: "See the real picture of your calls",
        anCtaSubtitle: "In 5–7 days we'll prepare a report on 500–1000 calls: operators, topics, mistakes, and quality.",

        // ===== STT page =====
        sttBadge: "Speech-to-Text API",
        sttHeroTitle: "The most accurate Uzbek speech recognition",
        sttHeroSubtitle: "A speech recognition API that handles dialects, slang, and Uzbek-Russian code-switching. Trained on real call-center recordings.",
        sttHeroCta: "Get an API key",
        sttSpec1: "accuracy (with dialects)",
        sttSpec2: "latency (real-time)",
        sttSpec3: "supported languages",
        sttSpec4: "continuous streaming",
        sttCapsLabel: "Capabilities",
        sttCapsTitle: "Built for real-world speech",
        sttCap1Title: "Dialects & code-switching",
        sttCap1Desc: "Understands Uzbek dialects, slang, and Uzbek-Russian switching within a single sentence.",
        sttCap2Title: "Voice isolation",
        sttCap2Desc: "Strips out street noise, music, and background to capture just the voice.",
        sttCap3Title: "Word-level timestamps",
        sttCap3Desc: "Confidence and a timestamp for every word — for analytics and subtitles.",
        sttCap4Title: "Streaming & batch",
        sttCap4Desc: "Real-time streaming or bulk processing of large recording volumes.",
        sttUseLabel: "Use cases",
        sttUseTitle: "How teams use STT",
        sttUse1Title: "Call analytics",
        sttUse1Desc: "Turn recordings into text and analyze quality and topics automatically.",
        sttUse2Title: "Real-time captions",
        sttUse2Desc: "Add instant transcription to live calls and meetings.",
        sttUse3Title: "Voice agents",
        sttUse3Desc: "The understanding stage for Voice Agents, with minimal latency.",
        sttCtaTitle: "Turn speech into accurate text",
        sttCtaSubtitle: "Send us audio and we'll show accuracy on your own data. Contact us for an API key and pricing.",
        sttDemoTitle: "Try the STT demo",
        sttDemoSubtitle: "Record, upload audio, or pick a sample — we'll transcribe it.",
        sttLangLabel: "Language",
        sttInputLabel: "Audio input",
        sttRecord: "Record",
        sttStop: "Stop",
        sttUpload: "Upload file",
        sttSample: "Sample",
        sttRun: "Transcribe",
        sttRunning: "Processing...",
        sttResultLabel: "Transcript",
        sttConfidence: "confidence",

        // ===== TTS page =====
        ttsBadge: "Text-to-Speech API",
        ttsHeroTitle: "Speech synthesis indistinguishable from a human voice",
        ttsHeroSubtitle: "Turn text into natural speech, or clone your best operator's voice. Uzbek, Russian, and English with low latency.",
        ttsHeroCta: "Get an API key",
        ttsSpec1: "synthesis latency",
        ttsSpec2: "voice-clone similarity",
        ttsSpec3: "audio quality",
        ttsSpec4: "languages",
        ttsCapsLabel: "Capabilities",
        ttsCapsTitle: "Speak in your brand's voice",
        ttsCap1Title: "Voice cloning",
        ttsCap1Desc: "Creates an exact digital copy of your operator's voice from 30 minutes of clean audio.",
        ttsCap2Title: "Natural prosody",
        ttsCap2Desc: "Lifelike delivery with stress, pauses, and intonation like a human speaker.",
        ttsCap3Title: "Speech control",
        ttsCap3Desc: "Control speed, tone, and pronunciation — numbers and terms read correctly.",
        ttsCap4Title: "Low-latency streaming",
        ttsCap4Desc: "Audio streaming for real-time dialogue — the reply starts within 200ms.",
        ttsUseLabel: "Use cases",
        ttsUseTitle: "How teams use TTS",
        ttsUse1Title: "Voice agents",
        ttsUse1Desc: "Synthesizes Voice Agents' replies in a natural voice.",
        ttsUse2Title: "IVR & notifications",
        ttsUse2Desc: "Build dynamic IVR menus and notifications in real time.",
        ttsUse3Title: "Content voiceover",
        ttsUse3Desc: "Voice for audio guides, training, and marketing content.",
        ttsCtaTitle: "Give your brand a voice",
        ttsCtaSubtitle: "Contact us for voice cloning and API integration.",
        ttsDemoTitle: "Try the TTS demo",
        ttsDemoSubtitle: "Enter text, pick a voice — we'll speak it.",
        ttsVoiceLabel: "Voice",
        ttsVoiceAziza: "Aziza",
        ttsVoiceJahongir: "Jahongir",
        ttsVoiceDmitry: "Dmitry",
        ttsVoiceEmma: "Emma",
        ttsTextLabel: "Text",
        ttsUseSample: "Sample text",
        ttsRun: "Speak it",
        ttsRunning: "Synthesizing...",
        ttsSampleUz: "Assalomu alaykum! Syncall AI bilan bog'langaningiz uchun rahmat. Sizga qanday yordam bera olaman?",
        ttsSampleRu: "Здравствуйте! Спасибо за обращение в Syncall AI. Чем я могу вам помочь?",
        ttsSampleEn: "Hello! Thanks for contacting Syncall AI. How can I help you today?",

        // Footer
        footerRights: "All rights reserved",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('ru');

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
