import React, { createContext, useCallback, useContext, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { getLocaleFromPath, localizePath, stripLocalePrefix } from '../lib/i18n.js';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const translations = {
    uz: {
        // Navbar
        home: "Bosh sahifa",
        features: "Nega biz",
        howItWorks: "Ishga tushirish",
        demo: "Demo",
        faq: "FAQ",
        contactSales: "Bog'lanish",
        creatorStudio: "Studiya",

        // Hero
        heroBadge: "Mijozlar bilan telefon orqali ishlaydigan kompaniyalar uchun",
        heroTitle: "Mijozlaringiz bilan telefonda gaplashadigan robot.",
        heroSubtitle: "Syncall sotuv uchun qo‘ng‘iroq qiladi, qarzdorlikni muhokama qiladi va kiruvchi qo‘ng‘iroqlarga javob beradi. Suhbatda kompaniyangiz tizimlaridagi ma’lumotlardan foydalanadi.",
        heroFeature1: "Kiruvchi va chiquvchi qo‘ng‘iroqlar",
        heroFeature2: "O‘zbek va rus tillari",
        heroFeature3: "Telefoniyangiz va CRM",
        tryDemo: "Yozuvni tinglash",
        ctaDemo: "Biz bilan bog‘lanish",
        ctaTrial: "Kompaniyam uchun sinash",
        ctaTelegram: "Telegram orqali yozish",
        navMarketingFeatures: "Nima qila oladi",
        navUseCases: "Misollar",
        navIntegrations: "Telefoniya va dasturlar",
        navPricing: "Narxlar",
        navAbout: "Kompaniya haqida",
        navMenu: "Navigatsiyani ochish",
        navClose: "Navigatsiyani yopish",
        primaryNavigation: "Asosiy navigatsiya",
        languageSelectorLabel: "Til tanlash",
        switchLightTheme: "Yorug' mavzuga o'tish",
        switchDarkTheme: "Qorong'i mavzuga o'tish",
        skipToContent: "Asosiy kontentga o'tish",
        loading: "Yuklanmoqda…",
        footerProducts: "Mahsulotlar",
        footerCompany: "Kompaniya",
        useCaseBanking: "Banklar",
        useCaseDebt: "Qarz undirish",
        useCaseReminders: "Uchrashuv eslatmalari",
        useCaseSurveys: "So'rovnomalar",
        useCaseLeads: "Lidlarni saralash",
        caseStudies: "Ishlash misollari",
        contactTitle: "Kompaniyangiz vazifasini muhokama qilaylik",
        contactSubtitle: "Telefon yoki email qoldiring. Bog‘lanib, savollaringizga javob beramiz.",
        contactName: "Ism",
        contactCompany: "Kompaniya",
        contactEmail: "Email",
        contactPhone: "Telefon",
        contactVolume: "Oyiga qo‘ng‘iroqlar (ixtiyoriy)",
        contactLanguages: "Kerakli tillar (ixtiyoriy)",
        contactMessage: "Vazifangizni ayting (ixtiyoriy)",
        contactSubmit: "So'rov yuborish",
        contactSubmitting: "Yuborilmoqda…",
        contactSuccess: "Rahmat. Qoldirgan kontaktingiz orqali bog‘lanamiz.",
        contactError: "So'rov yuborilmadi. Qayta urinib ko'ring yoki Telegram orqali yozing.",
        contactConfigError: "Forma manzili hali sozlanmagan. Hozircha Telegram orqali yozing.",
        contactRequired: "Majburiy maydonlarni to‘ldiring.",
        contactEmailInvalid: "To‘g‘ri email manzilini kiriting.",
        trustTitle: "Real natijalar uchun tayyorlangan ishonch bloki",
        trustPlaceholder: "PLACEHOLDER — haqiqiy ma'lumot kerak",
        metricMethodology: "Ko'rsatkichlarni qanday o'lchaymiz",
        metricMethodologyNote: "Ko'rsatkichlar sun'iy testlarda emas, real Syncall joriy etishlarida o'lchangan. Natijalar foydalanish ssenariysiga bog'liq.",
        metricResolution: "Operatorga o'tkazmasdan AI-agent tomonidan hal qilingan murojaatlar",
        metricCost: "Operatsion xarajatlarni kamaytirish",
        metricScale: "Daqiqasiga qo'ng'iroqlar",

        // Talk Bot
        talkBotTitle: "AI ovozli agentimiz bilan tanishing",
        talkBotSubtitle: "Ovozimiz qanchalik tabiiy ekanligini o'zingiz eshiting",
        talkBotButton: "Demo tinglash",

        // Partners
        partnersLabel: "Bizning hamkorlar",

        // Calllog
        calllogTitle: "Qanday gaplashishini tinglang",
        calllogSubtitle: "O‘zbek tilidagi ikkita yozuv: robot qo‘ng‘iroqqa javob beradi va o‘zi qo‘ng‘iroq qiladi.",
        callIncoming: "Qo‘ng‘iroqqa javob beradi",
        callOutgoing: "Mijozga qo‘ng‘iroq qiladi",

        // Visual Engine Pipeline
        engineTitle: "Syncall Voice Engine Ishlash Tizimi",
        engineSubtitle: "Bilingval qo'ng'iroqlarni qabul qilishdan boshlab brend ovozida javob qaytarishgacha bo'lgan to'liq avtomatlashtirilgan texnologik zanjir",
        engineCard1Title: "1. Bilingval audio oqim",
        engineCard1Desc: "O'zbek va rus tillarida kiruvchi yoki chiquvchi ovozli oqimni qabul qilish. Shovqinni to'suvchi Voice Isolation fon shovqinlarini to'liq filtrlaydi.",
        engineCard2Title: "2. Nutqni aniqlash (STT & LLM)",
        engineCard2Desc: "O'zbek nutqining lahja va slenglarini, tillar qorishmasini 95% aniqlikda matnga o'tkazish va mijoz niyatini (intent) aniqlash.",
        engineCard3Title: "3. CRM va Tizimlar bilan integratsiya",
        engineCard3Desc: "Kompaniyangiz CRM ma'lumotlar bazasi bilan xavfsiz On-Premise/Cloud integratsiya orqali mijoz statusini yangilash va tekshirish.",
        engineCard4Title: "4. Yuqori sifatli nutq sintezi (TTS)",
        engineCard4Desc: "Sizning eng yaxshi operatoringiz ovozi klonida, inson nutqidan farq qilmaydigan tabiiy ovoz bilan 0.5 soniyada javob qaytarish.",

        // Features
        featuresTitle: "Robotga qanday qo‘ng‘iroqlarni topshirish mumkin",
        feature1Stat: "1000+ qo'ng'iroq/min",
        heroLiveAnalysis: "Jonli qo'ng'iroq tahlili",
        callWidgetTitle: "Gaplashib ko‘ring",
        callWidgetSubtitle: "Raqamingizni tasdiqlang. Suhbat uchun mikrofon kerak.",
        callWidgetCta: "Suhbatni boshlash",
        callWidgetTelegramCta: "Raqamni tasdiqlash va gaplashish",
        callWidgetTelegramVerifying: "Telegram orqali tasdiqlanmoqda",
        callWidgetTelegramVerifyingSub: "Davom etish uchun Telegram oynasida telefon raqamingizni ulashishga ruxsat bering.",
        callWidgetDialing: "Ulanmoqda",
        callWidgetConnecting: "AI-agent bilan ulanmoqda",
        callWidgetErrorTitle: "Ulanib bo'lmadi",
        callWidgetErrorSubtitle: "Quyidagi yozuvlarda robot qanday gaplashishini tinglashingiz mumkin.",
        callWidgetDemoCta: "Yozuvni tinglash",
        callWidgetRetry: "Qayta urinish",
        callWidgetInvalidPhone: "To'g'ri raqam kiriting",
        callWidgetConsent: "Demo suhbat yozib olinadi.",
        callWidgetTelegramConsent: "Telegram raqamingizni tasdiqlaydi. Demo suhbat yozib olinadi.",
        callWidgetQueued: "Siz navbatdasiz",
        callWidgetQueuedSub: "Navbatdagi o'rningiz: ",
        callWidgetMicTitle: "Mikrofonga ruxsat bering",
        callWidgetMicSub: "AI-agent bilan gaplashish uchun mikrofon kerak",
        callWidgetLive: "Suhbat davom etmoqda",
        callWidgetLiveSub: "Gapiring — agent sizni eshitmoqda",
        callWidgetEndedTitle: "Qo'ng'iroq yakunlandi",
        callWidgetEndedSub: "Rahmat! Yana urinib ko'ring yoki demo qo'ng'iroqlarni tinglang",
        callWidgetCancel: "Bekor qilish",
        callWidgetYou: "Siz",
        callWidgetAgent: "Agent",
        callWidgetTranscript: "Suhbat matni",
        callWidgetMute: "Mikrofonni o'chirish",
        callWidgetUnmute: "Mikrofonni yoqish",
        callWidgetLanguage: "Tilni tanlang",
        callWidgetUnavailable: "Hozir gaplashib bo‘lmaydi",
        callWidgetErrVerify: "Tekshiruvdan o'ting va qayta urinib ko'ring",
        callWidgetErrTelegram: "Telegram orqali tasdiqlash amalga oshmadi. Qayta urinib ko'ring",
        callWidgetErrPhoneMismatch: "Telegram raqami kiritilgan raqamga mos kelmadi",
        callWidgetErrMic: "Ovozli demo uchun mikrofonga ruxsat kerak",
        callWidgetErrConflict: "Sizda allaqachon faol demo-sessiya bor",
        callWidgetErrLimit: "Demo limitiga yetdingiz. Keyinroq urinib ko'ring",
        callWidgetErrBusy: "Demo hozir band. Keyinroq urinib ko'ring",
        callWidgetErrQueueExpired: "Navbat kutish vaqti tugadi. Qayta urinib ko'ring",
        callWidgetErrWindowExpired: "Ulanish oynasi yopildi. Qaytadan boshlang",
        callWidgetErrOrigin: "Bu sayt manzilida demo mavjud emas. Keyinroq urinib ko‘ring.",
        callWidgetErrGeneric: "Demo ishga tushmadi. Keyinroq urinib ko'ring",
        voiceCloneMatch: "99.2% moslik",
        feature1TagDialect: "Lahja",
        feature1TagMix: "Aralash til",
        feature1TagSlang: "Sleng",
        feature1Title: "Savolni tushunish",
        feature1Desc: "Mijozlar o‘zbekcha, ruscha yoki tillarni aralashtirib gapiradi. Pilotda ularning aksenti va ishlatadigan iboralarini tekshiramiz.",
        feature2Title: "Ma’lumotingiz asosida javob berish",
        feature2Desc: "Agent siz bergan ko‘rsatmalar va bilimlar bazasidan foydalanadi. Mijoz uni to‘xtatib, savolga aniqlik kiritishi mumkin.",
        feature3Title: "Jamoangizga murojaatni o‘tkazish",
        feature3Desc: "Qachon qo‘ng‘iroqni operatorga o‘tkazish yoki qayta aloqa so‘rovini qoldirishni kelishamiz. Ssenariydan tashqari savollarni xodimlar hal qiladi.",
        feature4Title: "Brend ovozini tanlash",
        feature4Desc: "Ovoz tanlang yoki diktorning roziligi bilan uning ovozini klonlashni muhokama qiling.",
        feature5Title: "Natijani CRM’da saqlash",
        feature5Desc: "Jamoangiz qo‘ng‘iroq natijasini ko‘rishi va mijoz bilan ishlashni davom ettirishi uchun kerakli maydon va amallarni ulaymiz.",
        featureInterrupted: "Suhbat bo'lindi",
        featureNoiseCanceled: "Shovqin filtrlandi",
        featureOr: "yoki",
        featureAutoSync: "Avtomatik sinxronlash",
        engineDialingLabel: "Raqam terilmoqda",
        engineSttMapping: "STT xaritalash",
        engineCrmSync: "CRM sinxronlash",
        engineSecureSync: "Himoyalangan yadro sinxronlash",
        enginePerformanceTitle: "SYNCALL UNUMDORLIK KO'RSATKICHLARI",
        engineDiagnosticsOnline: "DIAGNOSTIKA: ONLAYN",

        // Numbers
        numbersLabel: "Syncall AI raqamlarda",
        numbersTitle: "Syncall AI bilan biznes samaradorligini oshirish",
        numbersStat1Value: "80%",
        numbersStat1Label: "Birinchi qo'ng'iroqdayoq muammolarni to'liq hal qilish (FCR)",
        numbersStat2Value: "-70%",
        numbersStat2Label: "Koll-markaz operatsion xarajatlarining kamayishi",
        numbersStat3Value: "94%",
        numbersStat3Label: "Mijozlarning umumiy qoniqish ko'rsatkichi (CSAT)",
        numbersDesc: "Syncall AI ning ilg'or ovozli agentlari bilan avtomatlashtirish kuchini his eting — mijozlarga xizmat ko'rsatishni o'zgartiring, xarajatlarni kamaytiring va mijozlar mamnuniyatini oshiring.",
        getStarted: "Boshlash",

        // How
        howTitle: "Qanday ulash mumkin",
        howStep1Title: "Mijozlar nima so‘rashini ayting",
        howStep1Text: "Ko‘p beriladigan savollar va mijozlar eshitishi kerak bo‘lgan javoblarni yuboring.",
        howStep2Title: "Robot bilan o‘zingiz gaplashing",
        howStep2Text: "Biz robotni tayyorlaymiz. Siz javoblarini tekshirib, nimani o‘zgartirish kerakligini aytasiz.",
        howStep3Title: "Telefon raqamingizga ulang",
        howStep3Text: "Telefoniyangizni tekshirib, narxni kelishamiz. Keyin robot qo‘ng‘iroqlarga javob bera boshlaydi.",
        howStep4Title: "Ishga tushiring va yaxshilang",
        howStep4Text: "Kelishilgan ssenariydan boshlang. Jamoangiz bilan natijalarni ko‘rib chiqib, agentni takomillashtiring.",

        // FAQ
        faqTitle: "Ko‘p beriladigan savollar",
        faqQ1: "Bu yozuvmi yoki gaplashsa bo‘ladimi?",
        faqA1: "Gaplashsa bo‘ladi. Robot savolingizni tinglaydi va javob beradi. Sahifaning yuqorisida sinab ko‘ring.",
        faqQ2: "Javoblarni qayerdan biladi?",
        faqA2: "Siz kompaniya haqida ma’lumot berasiz: ish vaqti, xizmatlar, narxlar va ko‘p beriladigan savollar javoblari. Ishga tushirishdan oldin javoblarini tekshirasiz.",
        faqQ3: "Robot javob bera olmasa-chi?",
        faqA3: "Bunday holatda nima qilishni oldindan kelishamiz. Telefoniyangizga qarab, robot qo‘ng‘iroqni xodimga o‘tkazadi yoki qayta qo‘ng‘iroq qilish so‘rovini oladi.",
        faqQ4: "Telefon raqamini almashtirish kerakmi?",
        faqA4: "Avval robotni mavjud raqam va telefoniyangizga ulash mumkinligini tekshiramiz. O‘zgarish kerak bo‘lsa, boshlashdan oldin tushuntiramiz.",
        faqQ5: "Qaysi tillarda gapiradi?",
        faqA5: "O‘zbek, rus va ingliz tillarida. Ishga tushirishdan oldin mijozlar nutqi va mahsulot yoki xizmat nomlarini qanday tushunishini tekshirishingiz mumkin.",
        faqQ6: "Narxi qancha?",
        faqA6: "Narx qo‘ng‘iroqlar soni, davomiyligi va sozlash ishlariga bog‘liq. Xarajatlarni oldindan kelishamiz. 1 000 tagacha qo‘ng‘iroq bilan bepul sinov so‘rashingiz mumkin — jamoamiz shartlarini tushuntiradi.",

        // ===== Product nav (tabs) =====
        navVoiceAgents: "Telefon yordamchisi",
        navAnalytics: "Qo‘ng‘iroqlarni tekshirish",
        navStt: "Nutqdan matnga · Studiya",
        navTts: "Matndan ovozga · Studiya",

        // ===== Products strip =====
        pnLabel: "Syncall’ning boshqa imkoniyatlari",
        pnTitle: "Qo‘ng‘iroq va xabarlarda yordam",
        pnSubtitle: "",
        pnKindProduct: "Mahsulot",
        pnKindApi: "API",
        pnYouAreHere: "Shu yerda",
        pnVoiceName: "Qo‘ng‘iroqlarga javob berish",
        pnVoiceDesc: "Yordamchi mijozlar bilan telefonda gaplashadi va savollariga javob beradi.",
        pnVoiceStat: "< 1.5s javob · 24/7",
        pnAnalyticsName: "Xodimlar suhbatlarini tekshirish",
        pnAnalyticsDesc: "Qo‘ng‘iroq yozuvlarida xato va javobsiz savollarni topadi. Hammasini o‘zingiz tinglashingiz shart emas.",
        pnAnalyticsStat: "100% qamrov",
        pnSttName: "STT",
        pnSttDesc: "O'zbek lahjalari va aralash til uchun nutqni matnga o'tkazish API'si.",
        pnSttStat: "95% aniqlik",
        pnTtsName: "TTS",
        pnTtsDesc: "Tabiiy, inson ovozidan farqsiz nutq sintezi va ovoz klonlash API'si.",
        pnTtsStat: "< 200ms",

        // ===== Shared demo =====
        demoModeLive: "Jonli API",
        demoModeSample: "Demo rejimi",
        demoMicError: "Mikrofondan foydalanib bo'lmadi. Ruxsatni tekshiring.",
        demoApiError: "So'rov bajarilmadi. Birozdan so'ng qayta urinib ko'ring.",
        demoSampleNote: "Bu demo namunaviy natijani ko'rsatmoqda. Jonli API'ni ulash uchun biz bilan bog'laning.",
        demoCtaSecondary: "API'ga ruxsat olish",

        // ===== Analytics page =====
        anBadge: "Qo‘ng‘iroqlarni tekshirish",
        anHeroTitle: "Xodimlar mijozlar bilan qanday gaplashishini biling.",
        anHeroSubtitle: "Syncall qo‘ng‘iroq yozuvlarini tekshirib, xato va javobsiz savollarni belgilaydi. Qaysi suhbatlarni batafsil ko‘rish kerakligini bilasiz.",
        anHeroCta: "Yozuvlarimizni tekshirish",
        anHeroCta2: "Hisobot namunasini ko‘rish",
        anScoreCardTitle: "Qo'ng'iroq bahosi",
        anScoreRow1: "Skriptga rioya",
        anScoreRow2: "Muloqot odobi",
        anScoreRow3: "Muammoni hal qilish",
        anScoreRow4: "Sotuv imkoniyati",
        anScoreTagOk: "Salomlashish bajarildi",
        anScoreTagWarn: "E'tirozga javob berilmadi",
        anStat1: "qo'ng'iroqlar nazorati",
        anStat2: "sifat tekshiruvi xarajati",
        anStat3: "uch tilda tahlil",
        anProblemLabel: "Muammo",
        anProblemTitlePre: "Kundalik qo‘ng‘iroqlarda",
        anProblemTitlePost: "nimalarni o‘tkazib yuborish mumkin",
        anProb1Title: "Operator xatolari",
        anProb1Desc: "Tanlab tinglashda ko'pchilik xato va qo'pol javoblar e'tibordan chetda qoladi.",
        anProb2Title: "Yashirin «sotuvsiz»",
        anProb2Desc: "Mijoz nega sotib olmaganini hech kim tahlil qilmaydi va sabablari yo'qoladi.",
        anProb3Title: "Kim haqiqatan ishlaydi?",
        anProb3Desc: "Operatorlarning real samaradorligini ob'ektiv o'lchash imkoni yo'q.",
        anProb4Title: "Sub'ektiv o'qitish",
        anProb4Desc: "Trening shaxsiy taassurotga asoslanadi, aniq ma'lumotlarga emas.",
        anProb5Title: "Shikoyatlar kech keladi",
        anProb5Desc: "Muammoli qo'ng'iroqlar mijoz ketganidan keyin ma'lum bo'ladi.",
        anProb6Title: "Rahbar ko'rmaydi",
        anProb6Desc: "Boshqaruvda real ko'rsatkichlar emas, faqat umumiy taxminlar bor.",
        anPipeLabel: "Jarayon",
        anPipeTitle: "Yozuvdan tekshirish kerak bo‘lgan masalalar ro‘yxatigacha",
        anPipeSubtitle: "Nima muhimligini tanlang: salomlashish, savolga javob yoki qoidalaringizga rioya qilish.",
        anPipe1Title: "Qo'ng'iroq",
        anPipe1Desc: "Telefoniya yoki yozuvlardan audio avtomatik yuklanadi.",
        anPipe2Title: "Suhbat matni",
        anPipe2Desc: "Yozuv o‘qish mumkin bo‘lgan matnga aylanadi.",
        anPipe3Title: "Muhim qadamlarni tekshirish",
        anPipe3Desc: "Xodim salomlashdimi? Savolga javob berdimi?",
        anPipe4Title: "Xatolarni belgilash",
        anPipe4Desc: "Suhbat qayerda talablaringizga mos kelmaganini ko‘ring.",
        anPipe5Title: "Rahbar uchun hisobot",
        anPipe5Desc: "Belgilangan suhbatlarni ochib, keyingi qadamni tanlang.",
        anResultsLabel: "Natijalar",
        anResultsTitle: "Tanlama nazoratdan — to'liq va o'lchanadigan nazoratga",
        anResult1: "sifat ballining o'sishi",
        anResult2: "shikoyatlarning kamayishi",
        anResult3: "ko'proq tekshirilgan qo'ng'iroqlar",
        anCtaTitle: "Qo'ng'iroqlaringizning haqiqiy holatini ko'ring",
        anCtaSubtitle: "Odatiy yozuvlar va tekshiruv mezonlarini ulashing. Namuna, muddat va pilot doirasini birga kelishamiz.",
        anDeployLabel: "Joylashtirish",
        anDeployTitle: "Cloud yoki On-Premise — sizning serverlaringizda",
        anDeploySubtitle: "Voice Agents kabi Analytics ham to'liq On-Premise ishlashi mumkin. Barcha audio yozuvlar va tahlil sizning ichki tarmog'ingizda qoladi — banklar va davlat tashkilotlari uchun ideal.",
        anDeployCloud: "Syncall Cloud",
        anDeployOnprem: "On-Premise — sizning serveringizda",

        // ===== STT page =====
        sttBadge: "Speech-to-Text API",
        sttHeroTitle: "O'zbek nutqini matnga o'giradigan eng aniq STT",
        sttHeroSubtitle: "Lahjalar, sleng va o'zbek-rus aralash nutqi bilan ishlaydigan nutqni aniqlash API'si. Real qo'ng'iroq yozuvlarida o'rgatilgan.",
        sttHeroCta: "API kalitini olish",
        sttSpec1: "aniqlik (lahjalar bilan)",
        sttSpec2: "kechikish (real-time)",
        sttSpec3: "qo'llab-quvvatlanadigan tillar",
        sttSpec4: "uzluksiz oqim",
        sttCapsLabel: "Imkoniyatlar",
        sttCapsTitle: "Mahalliy nutq uchun yaratilgan",
        sttCap1Title: "Lahjalar va aralash til",
        sttCap1Desc: "O'zbek lahjalari, sleng va bir gap ichida o'zbek-rus almashinuvini tushunadi.",
        sttCap2Title: "Shovqinni to'sish",
        sttCap2Desc: "Ko'cha shovqini, musiqa va fon ovozlarini filtrlab, faqat nutqni ajratadi.",
        sttCap3Title: "So'z darajasidagi vaqt belgilari",
        sttCap3Desc: "Har bir so'z uchun aniqlik va vaqt belgisi — analitika va subtitrlar uchun.",
        sttCap4Title: "Streaming va batch",
        sttCap4Desc: "Real vaqtli oqim yoki katta hajmli yozuvlarni ommaviy qayta ishlash.",
        sttUseLabel: "Qo'llanilishi",
        sttUseTitle: "Jamoalar STT'dan qanday foydalanadi",
        sttUse1Title: "Qo'ng'iroqlar tahlili",
        sttUse1Desc: "Yozuvlarni matnga o'girib, sifat va mavzularni avtomatik tahlil qiling.",
        sttUse2Title: "Real-time subtitr",
        sttUse2Desc: "Jonli qo'ng'iroq va uchrashuvlarga bir zumda transkripsiya qo'shing.",
        sttUse3Title: "Ovozli agentlar",
        sttUse3Desc: "Voice Agents uchun tushunish bosqichi — past kechikish bilan.",
        sttCtaTitle: "Nutqni aniq matnga o'giring",
        sttCtaSubtitle: "Audio yuboring, biz aniqlikni o'z ma'lumotlaringizda ko'rsatamiz. API kaliti va narxlar uchun bog'laning.",
        sttDemoTitle: "STT demosini sinab ko'ring",
        sttDemoSubtitle: "Audio yozing, yuklang yoki namunani tanlang — matnga o'giriladi.",
        sttLangLabel: "Til",
        sttInputLabel: "Audio kiriting",
        sttRecord: "Yozib olish",
        sttStop: "To'xtatish",
        sttUpload: "Fayl yuklash",
        sttSample: "Namuna",
        sttRun: "Matnga o'girish",
        sttRunning: "Qayta ishlanmoqda...",
        sttResultLabel: "Transkripsiya",
        sttConfidence: "ishonch",

        // ===== TTS page =====
        ttsBadge: "Text-to-Speech API",
        ttsHeroTitle: "Inson ovozidan farqsiz tabiiy nutq sintezi",
        ttsHeroSubtitle: "Matnni tabiiy ovozga aylantiring yoki eng yaxshi operatoringiz ovozini klonlang. O'zbek, rus va ingliz tillarida past kechikish bilan.",
        ttsHeroCta: "API kalitini olish",
        ttsSpec1: "sintez kechikishi",
        ttsSpec2: "ovoz klonlash mosligi",
        ttsSpec3: "audio sifati",
        ttsSpec4: "tillar",
        ttsCapsLabel: "Imkoniyatlar",
        ttsCapsTitle: "Brendingiz ovozi bilan gapiring",
        ttsCap1Title: "Ovoz klonlash",
        ttsCap1Desc: "30 daqiqalik toza yozuvdan operatoringizning aniq raqamli ovoz nusxasini yaratadi.",
        ttsCap2Title: "Tabiiy intonatsiya",
        ttsCap2Desc: "Inson nutqiga xos urg'u, pauza va ohang bilan jonli jaranglaydi.",
        ttsCap3Title: "Nutqni boshqarish",
        ttsCap3Desc: "Tezlik, ohang va talaffuzni boshqaring — raqamlar va atamalar to'g'ri o'qiladi.",
        ttsCap4Title: "Past kechikishli streaming",
        ttsCap4Desc: "Real vaqtli dialoglar uchun audio oqim — javob 200ms ichida boshlanadi.",
        ttsUseLabel: "Qo'llanilishi",
        ttsUseTitle: "Jamoalar TTS'dan qanday foydalanadi",
        ttsUse1Title: "Ovozli agentlar",
        ttsUse1Desc: "Voice Agents javoblarini tabiiy ovozda sintez qiladi.",
        ttsUse2Title: "IVR va e'lonlar",
        ttsUse2Desc: "Dinamik IVR menyu va xabarnomalarni real vaqtda yarating.",
        ttsUse3Title: "Kontent ovozi",
        ttsUse3Desc: "Audiogid, ta'lim va marketing kontenti uchun ovoz.",
        ttsCtaTitle: "Brendingizga ovoz bering",
        ttsCtaSubtitle: "Ovozni klonlash va API integratsiyasi uchun biz bilan bog'laning.",
        ttsDemoTitle: "TTS demosini sinab ko'ring",
        ttsDemoSubtitle: "Matn kiriting, ovozni tanlang — nutqqa aylantiramiz.",
        ttsVoiceLabel: "Ovoz",
        ttsVoiceAziza: "Aziza",
        ttsVoiceJahongir: "Jahongir",
        ttsVoiceDmitry: "Dmitriy",
        ttsVoiceEmma: "Emma",
        ttsTextLabel: "Matn",
        ttsUseSample: "Namuna matn",
        ttsRun: "Ovozga aylantirish",
        ttsRunning: "Sintez qilinmoqda...",
        ttsSampleUz: "Assalomu alaykum! Syncall AI bilan bog'langaningiz uchun rahmat. Sizga qanday yordam bera olaman?",
        ttsSampleRu: "Здравствуйте! Спасибо за обращение в Syncall AI. Чем я могу вам помочь?",
        ttsSampleEn: "Hello! Thanks for contacting Syncall AI. How can I help you today?",

        // ===== Chatbots (nav + strip) =====
        navChatbots: "Xabarlarga javoblar",
        pnChatbotsName: "Xabarlarga javob berish",
        pnChatbotsDesc: "Sayt va Telegram’da kompaniyangiz ma’lumotlari asosida ko‘p beriladigan savollarga javob beradi.",
        pnChatbotsStat: "On-Premise · UZ·RU",

        // ===== Chatbots page =====
        cbBadge: "Xabarlarga javoblar",
        cbHeroTitle: "Xodimlar band bo‘lsa ham, mijozlar xabarlariga javob bering.",
        cbHeroSubtitle: "Yordamchi sayt va Telegram’da ko‘p beriladigan savollarga javob beradi. Siz unga kompaniyangiz haqida ma’lumot berasiz.",
        cbHeroCta: "Xabarlar yordamchisini muhokama qilish",
        cbHeroCta2: "Nima qila olishini ko‘rish",
        cbChatOnPrem: "On-Premise server",
        cbChatEncrypted: "Shifrlangan",
        cbChatMsg1: "Salom! Kechagi to'lovim o'tdimi?",
        cbChatMsg2: "Assalomu alaykum! Ha, #5894 to'lovingiz muvaffaqiyatli o'tdi. Yana savol bormi?",
        cbChatMsg3: "Keyingi to'lov qachon?",
        cbChatMsg4: "Keyingi to'lov 30-iyun, summa 1 250 000 so'm. Eslatma yuboraymi?",
        cbChatPlaceholder: "Xabar yozing...",
        cbSpec1: "to'liq sizning serveringizda",
        cbSpec2: "tashqi serverlarga ma'lumot",
        cbSpec3: "tillar (dialektlar bilan)",
        cbSpec4: "uzluksiz ishlash",
        cbWhyLabel: "Nega On-Premise",
        cbWhyTitle: "Chatbot qayerda ishlashini tanlang",
        cbWhySubtitle: "Bulut yoki o‘z serverlaringizni, saqlash, kirish huquqi va messenjer ulanishlarini muhokama qiling.",
        cbDeployCloudTag: "Bulut",
        cbDeployCloudTitle: "Syncall Cloud",
        cbDeployCloud1: "Tez ishga tushirish, infratuzilma talab qilinmaydi",
        cbDeployCloud2: "Avtomatik yangilanish va masshtablash",
        cbDeployCloud3: "Kichik va o'rta bizneslar uchun ideal",
        cbDeployOnpremTag: "Serverlaringizda",
        cbDeployOnpremTitle: "Sizning serverlaringiz",
        cbDeployOnprem1: "Modellar va suhbat yozuvlari qayerda saqlanishini tanlang",
        cbDeployOnprem2: "Arxitekturani xavfsizlik jamoangiz bilan tekshiring",
        cbDeployOnprem3: "To'liq nazorat: modellar, loglar, kirish huquqlari",
        cbCapsLabel: "Imkoniyatlar",
        cbCapsTitle: "Korporativ darajadagi chatbotlar",
        cbCap1Title: "To'liq On-Premise",
        cbCap1Desc: "Chatbotni o‘z infratuzilmangizda joylashtiring. Ulanadigan tashqi tizimlar va xabar kanallarini kelishamiz.",
        cbCap2Title: "Ma'lumotlar xavfsizligi",
        cbCap2Desc: "Ishga tushirishdan oldin kirish huquqi, jurnallar va ma’lumotlarga ishlov berish talablarini belgilang.",
        cbCap3Title: "Ko'p kanalli",
        cbCap3Desc: "Telegram, veb-vidjet, WhatsApp va ilova ichidagi chatlar — yagona tizimdan.",
        cbCap4Title: "CRM va bilimlar bazasi",
        cbCap4Desc: "Sizning hujjatlaringiz va CRM asosida javob beradi, yozuvlarni avtomatik yangilaydi.",
        cbCap5Title: "O‘zbek va rus tillari",
        cbCap5Desc: "Mijozlaringiz iboralari, aralash xabarlari va mahsulot nomlarini sinang.",
        cbCap6Title: "Inson operatorga uzatish",
        cbCap6Desc: "Qaysi so‘rovlarni xodimga berish va suhbat mazmunini qanday ulashishni kelishib oling.",
        cbUseLabel: "Qo'llanilishi",
        cbUseTitle: "Chatbotlar qayerda ishlaydi",
        cbUse1Title: "Qo'llab-quvvatlashni avtomatlashtirish",
        cbUse1Desc: "Takroriy savollarga bilimlar bazangiz asosida, jumladan ish vaqtidan tashqarida javob bering.",
        cbUse2Title: "Lidlarni saralash",
        cbUse2Desc: "Kiruvchi so'rovlarni saralaydi va tayyor lidlarni savdo bo'limiga uzatadi.",
        cbUse3Title: "Ichki helpdesk",
        cbUse3Desc: "Xodimlar uchun HR, IT va ichki jarayonlar bo'yicha xavfsiz yordamchi.",
        cbCtaTitle: "Ma'lumotlaringizni xavfsiz saqlab, avtomatlashtiring",
        cbCtaSubtitle: "On-Premise chatbotni o'z infratuzilmangizda joylashtirish uchun biz bilan bog'laning.",

        // Footer
        footerRights: "Barcha huquqlar himoyalangan",
        contactMethod: "Qanday bog‘lanaylik?",
        contactByPhone: "Telefon",
        contactByEmail: "Email",
        contactOptional: "Tafsilot qo‘shish (ixtiyoriy)",
        contactPilotTitle: "O‘z qo‘ng‘iroqlaringizda sinab ko‘ring",
        contactPilotSubtitle: "Kontakt qoldiring. Kompaniyangiz uchun sinovni kelishish uchun bog‘lanamiz.",
        contactDemoTitle: "Kompaniyangiz vazifasini muhokama qilaylik",
        contactDemoSubtitle: "Kontakt qoldiring. Qo‘ng‘iroqlaringizni muhokama qilib, savollarga javob beramiz va narxni tushuntiramiz.",
        contactProduct: "Qaysi ishda yordam kerak?",
        contactProductVoice: "Qo‘ng‘iroqlarga javob berish",
        contactProductAnalytics: "Xodimlar suhbatlarini tekshirish",
        contactProductChatbots: "Xabarlarga javob berish",
        contactVolumeInvalid: "Musbat qo‘ng‘iroqlar sonini kiriting.",
        studioStripTitle: "Matnni ovozga yoki yozuvni matnga aylantirmoqchimisiz?",
        studioStripBody: "Buni Syncall Studio’da o‘zingiz qilishingiz mumkin.",
        studioStt: "Yozuvdan matnga →",
        studioTts: "Matndan ovozga →",
        liveDemoTitle: "AI bilan o‘zingiz gaplashib ko‘ring",
        liveDemoBody: "Demoni boshlash uchun telefonni tasdiqlash va mikrofonga ruxsat berish kerak.",
        demoListenFor: "Talaffuz, nutq sur’ati va suhbat qanday kechishiga e’tibor bering.",
        demoPlay: "Tinglash",
        demoPause: "Pauza",
        demoTranscript: "Matnini o‘qish",
        pilotLabel: "Bitta vazifadan boshlang",
        pilotTitle: "Syncall’ni qo‘ng‘iroqlaringizda sinang",
        pilotBody: "1 000 tagacha sinov qo‘ng‘irog‘i bilan bepul pilot so‘rang. Avval ssenariy, integratsiyalar va muvaffaqiyat mezonlarini kelishamiz.",
        pilotNote: "Qaror qabul qilishdan oldin tarif birligi, ulanish va telefoniya xarajatlari hamda pilot shartlari ko‘rsatilgan taklif olasiz.",
        pilotPricing: "Narx qanday shakllanadi →",
        viewSolution: "Qanday ishlaydi →",
        customerStoriesTitle: "Mijozlarimizda nima o‘zgaradi",
        customerStoriesLabel: "Mijozlar tajribasi",
        customerBefore: "Syncall’dan oldin",
        customerAfter: "Syncall bilan",
        customerResult: "Natija",
        analyticsExample: "Hisobot namunasi — misol ma’lumotlar",
        analyticsExampleTitle: "Qaysi qo‘ng‘iroqlarni tekshirish kerakligini biling",
        analyticsExampleBody: "Suhbat matnini o‘qing, bajarilmagan qadamlarni toping va jamoangizning keyingi harakatini belgilang.",
        chatbotExample: "Suhbat namunasi",
        heroLanguageNote: "O‘zbek va rus tillarida. Kechayu kunduz.",
        heroTryLive: "Robot bilan gaplashish",
        heroSeeExamples: "U nima qila oladi",
        callWidgetLoading: "Suhbat tayyorlanmoqda…",
        callWidgetScenario: "Suhbat misolini tanlang",
        examplesIntro: "Robotni CRM — mijozlar bazasi va to‘lovlarni hisobga olish tizimiga ulaymiz. U suhbat davomida ma’lumotlarni tekshiradi, ularga asoslanib javob beradi va natijani saqlaydi.",
        exampleLabel: "Misol",
        exampleCustomer: "Mijoz",
        exampleLookupLabel: "Suhbat davomida ma’lumotlarni tekshiradi",
        example1Title: "Sotuv qo‘ng‘iroqlari",
        example1Body: "Ariza qoldirgan mijozlarga qo‘ng‘iroq qiladi, ehtiyojini aniqlaydi va CRM ma’lumotlari asosida taklif tanlaydi. Kelishuvlarni menejer uchun saqlaydi.",
        example1Context: "Ariza qoldirgan mijozga qo‘ng‘iroqdan parcha.",
        example1Question: "Uyga internet kerak, lekin oyiga 150 ming so‘mdan oshmasin.",
        example1Lookup: "CRM: arizadagi manzil. Ulanishni tekshirish: shu manzilda oyiga 120 000 so‘mga 100 Mbit/s mavjud.",
        example1Answer: "Manzilingizda oyiga 120 ming so‘mlik tarif bor. Tezligi — 100 megabit. Rasmiylashtirish uchun menejerimiz qachon bog‘lansa qulay?",
        example1Reply: "Ma’qul. Ertaga soat uchdan keyin.",
        example1Result: "CRMda saqlanadi: tanlangan tarif, 150 000 so‘mgacha byudjet, ertaga 15:00 dan keyin qo‘ng‘iroq qilish.",
        example2Title: "Qarzdorlik bo‘yicha qo‘ng‘iroqlar",
        example2Body: "Qarzdorlik va so‘nggi to‘lovlarni hisob tizimidan tekshiradi. Kechikish sababini aniqlaydi va to‘lov sanasini kelishadi.",
        example2Context: "Mijozning shaxsi tekshirilgandan keyingi suhbatdan parcha.",
        example2Question: "Kecha 150 ming so‘m to‘ladim. Yana qancha qoldi?",
        example2Lookup: "To‘lovlar hisobi: 600 000 so‘m hisoblangan, 150 000 so‘mlik to‘lov tushgan. Qoldiq — 450 000 so‘m.",
        example2Answer: "To‘lovingiz hisobga olingan. 450 ming so‘m qoldi. Qolganini qachon to‘lay olasiz?",
        example2Reply: "Juma kuni, maoshim tushganda.",
        example2Result: "CRMda saqlanadi: juma kuni 450 000 so‘m to‘lash va’dasi. Kechikish sababi — maoshni kutish.",
        example3Title: "Kiruvchi qo‘ng‘iroqlar",
        example3Body: "Mijoz ma’lumotlarini topadi, to‘lov, buyurtma yoki xizmat holatini tekshiradi. Vaziyatni tushuntiradi va CRMda murojaat yaratadi.",
        example3Context: "Abonentning kiruvchi qo‘ng‘irog‘idan parcha.",
        example3Question: "Internet uchun to‘ladim, nega ishlamayapti?",
        example3Lookup: "To‘lovlar hisobi: to‘lov tushgan, balans musbat. CRM: mijoz manzilida nosozlik bor, ta’mirlash soat 18:00 gacha davom etadi.",
        example3Answer: "To‘lovingiz tushgan. Manzilingizdagi nosozlik sabab internet ishlamayapti. Texnik xizmat ma’lumotiga ko‘ra, uni soat oltigacha tuzatish rejalashtirilgan. Murojaat qoldiraymi?",
        example3Reply: "Ha, iltimos.",
        example3Result: "CRMda murojaat yaratiladi: mijoz ma’lumotlari, tekshiruv natijalari va suhbat mazmuni texnik yordamga yuboriladi.",
        pnHomeTitle: "Yozishmalar va suhbatlarni tekshirish uchun ham",
        howCta: "Ulashni muhokama qilish",
        howNote: "1 000 tagacha qo‘ng‘iroq bilan bepul sinovdan boshlash mumkin. Sinovga nimalar kirishini oldindan kelishamiz.",
        navPlainFeatures: "Nima qila oladi",
        navRecordings: "Qo‘ng‘iroq yozuvlari",
        navSetup: "Qanday ulash mumkin",
    },
    ru: {
        // Navbar
        home: "Главная",
        features: "Почему мы",
        howItWorks: "Этапы запуска",
        demo: "Демо",
        faq: "FAQ",
        contactSales: "Связаться",
        creatorStudio: "Студия",

        // Hero
        heroBadge: "Для компаний, которые работают с клиентами по телефону",
        heroTitle: "Робот, который общается с клиентами по телефону.",
        heroSubtitle: "Syncall звонит для продаж, обсуждает задолженность и отвечает на входящие звонки. В разговоре использует данные из систем вашей компании.",
        heroFeature1: "Входящие и исходящие звонки",
        heroFeature2: "Узбекский и русский",
        heroFeature3: "Ваша телефония и CRM",
        tryDemo: "Послушать запись",
        ctaDemo: "Связаться с нами",
        ctaTrial: "Попробовать для своей компании",
        ctaTelegram: "Написать в Telegram",
        navMarketingFeatures: "Что умеет",
        navUseCases: "Примеры",
        navIntegrations: "Телефония и программы",
        navPricing: "Цены",
        navAbout: "О компании",
        navMenu: "Открыть навигацию",
        navClose: "Закрыть навигацию",
        primaryNavigation: "Основная навигация",
        languageSelectorLabel: "Выбор языка",
        switchLightTheme: "Включить светлую тему",
        switchDarkTheme: "Включить тёмную тему",
        skipToContent: "Перейти к основному содержанию",
        loading: "Загрузка…",
        footerProducts: "Продукты",
        footerCompany: "Компания",
        useCaseBanking: "Банки",
        useCaseDebt: "Взыскание задолженности",
        useCaseReminders: "Напоминания о встречах",
        useCaseSurveys: "Опросы",
        useCaseLeads: "Квалификация лидов",
        caseStudies: "Примеры работы",
        contactTitle: "Обсудим задачу вашей компании",
        contactSubtitle: "Оставьте телефон или email. Мы свяжемся с вами и ответим на вопросы.",
        contactName: "Имя",
        contactCompany: "Компания",
        contactEmail: "Email",
        contactPhone: "Телефон",
        contactVolume: "Звонков в месяц (необязательно)",
        contactLanguages: "Нужные языки (необязательно)",
        contactMessage: "Расскажите о задаче (необязательно)",
        contactSubmit: "Отправить заявку",
        contactSubmitting: "Отправляем…",
        contactSuccess: "Спасибо. Мы свяжемся с вами по указанным контактам.",
        contactError: "Не удалось отправить заявку. Попробуйте ещё раз или напишите в Telegram.",
        contactConfigError: "Адрес формы ещё не настроен. Пока напишите нам в Telegram.",
        contactRequired: "Заполните обязательные поля.",
        contactEmailInvalid: "Укажите корректный email.",
        trustTitle: "Блок доверия, готовый для реальных результатов",
        trustPlaceholder: "PLACEHOLDER — нужны реальные данные",
        metricMethodology: "Как мы измеряем показатели",
        metricMethodologyNote: "Показатели измерены в рабочих внедрениях Syncall, а не на синтетических тестах. Итоговые значения зависят от сценария использования.",
        metricResolution: "Решение вопросов ИИ-агентом без перевода на оператора",
        metricCost: "Снижение операционных затрат",
        metricScale: "Звонков в минуту",

        // Talk Bot
        talkBotTitle: "Познакомьтесь с нашим AI голосовым агентом",
        talkBotSubtitle: "Послушайте сами, насколько естественно звучит наш AI",
        talkBotButton: "Послушать демо",

        // Partners
        partnersLabel: "Наши партнёры",

        // Calllog
        calllogTitle: "Послушайте, как это звучит",
        calllogSubtitle: "Две записи на узбекском: робот принимает звонок и звонит сам.",
        callIncoming: "Отвечает на звонок",
        callOutgoing: "Звонит клиенту",

        // Visual Engine Pipeline
        engineTitle: "Технологический Стек Голосового Движка Syncall",
        engineSubtitle: "Автоматизированный цикл обработки звонка: от аудиопотока до генерации ответа бренд войсом",
        engineCard1Title: "1. Двусторонний аудиопоток",
        engineCard1Desc: "Приём входящего или осуществление исходящего звонка. Встроенная технология Voice Isolation мгновенно фильтрует фоновые шумы и музыку.",
        engineCard2Title: "2. Распознавание и Анализ (STT & LLM)",
        engineCard2Desc: "Перевод двуязычной речи (рус/узб) с учётом диалектов, акцентов и разговорного сленга в текст с точностью 95% и распознавание намерений.",
        engineCard3Title: "3. Интеграция с CRM",
        engineCard3Desc: "Безопасное соединение (On-Premise или защищенное облако) с базами данных вашей CRM для проверки статусов и автоматического обновления записей.",
        engineCard4Title: "4. Естественный синтез голоса (TTS)",
        engineCard4Desc: "Генерация ответа за 0.5 секунды цифровым клоном вашего лучшего оператора. Голос звучит абсолютно естественно и дружелюбно.",

        // Features
        featuresTitle: "Какие звонки можно поручить роботу",
        feature1Stat: "1000+ звонков/мин",
        heroLiveAnalysis: "Анализ звонков",
        callWidgetTitle: "Попробуйте поговорить",
        callWidgetSubtitle: "Подтвердите свой номер. Для разговора нужен микрофон.",
        callWidgetCta: "Начать разговор",
        callWidgetTelegramCta: "Подтвердить номер и поговорить",
        callWidgetTelegramVerifying: "Подтверждаем через Telegram",
        callWidgetTelegramVerifyingSub: "В окне Telegram разрешите передать ваш номер телефона, чтобы продолжить.",
        callWidgetDialing: "Подключаем",
        callWidgetConnecting: "Соединяем с AI-агентом",
        callWidgetErrorTitle: "Не удалось подключиться",
        callWidgetErrorSubtitle: "Можно послушать, как робот разговаривает, в записях ниже.",
        callWidgetDemoCta: "Послушать запись",
        callWidgetRetry: "Попробовать снова",
        callWidgetInvalidPhone: "Введите корректный номер",
        callWidgetConsent: "Демо-разговор записывается.",
        callWidgetTelegramConsent: "Telegram подтвердит ваш номер. Демо-разговор записывается.",
        callWidgetQueued: "Вы в очереди",
        callWidgetQueuedSub: "Ваша позиция: ",
        callWidgetMicTitle: "Разрешите доступ к микрофону",
        callWidgetMicSub: "Микрофон нужен для разговора с AI-агентом",
        callWidgetLive: "Идёт разговор",
        callWidgetLiveSub: "Говорите — агент вас слышит",
        callWidgetEndedTitle: "Звонок завершён",
        callWidgetEndedSub: "Спасибо! Попробуйте ещё раз или послушайте демо-звонки",
        callWidgetCancel: "Отменить",
        callWidgetYou: "Вы",
        callWidgetAgent: "Агент",
        callWidgetTranscript: "Расшифровка разговора",
        callWidgetMute: "Выключить микрофон",
        callWidgetUnmute: "Включить микрофон",
        callWidgetLanguage: "Выберите язык",
        callWidgetUnavailable: "Сейчас поговорить не получится",
        callWidgetErrVerify: "Пройдите проверку и попробуйте снова",
        callWidgetErrTelegram: "Не удалось подтвердить номер через Telegram. Попробуйте снова",
        callWidgetErrPhoneMismatch: "Номер Telegram не совпадает с введённым номером",
        callWidgetErrMic: "Для голосового демо нужен доступ к микрофону",
        callWidgetErrConflict: "У вас уже есть активная демо-сессия",
        callWidgetErrLimit: "Вы достигли лимита демо. Попробуйте позже",
        callWidgetErrBusy: "Демо сейчас занято. Попробуйте позже",
        callWidgetErrQueueExpired: "Время ожидания в очереди истекло. Попробуйте снова",
        callWidgetErrWindowExpired: "Окно подключения истекло. Начните заново",
        callWidgetErrOrigin: "Демо недоступно по этому адресу сайта. Попробуйте позже.",
        callWidgetErrGeneric: "Не удалось запустить демо. Попробуйте позже",
        voiceCloneMatch: "99.2% схожесть",
        feature1TagDialect: "Диалекты",
        feature1TagMix: "Микс языков",
        feature1TagSlang: "Сленг",
        feature1Title: "Понять вопрос",
        feature1Desc: "Клиенты говорят на узбекском, русском или смешивают языки. На пилоте проверяем привычные им акценты и выражения.",
        feature2Title: "Ответить по вашей информации",
        feature2Desc: "Агент использует ваши инструкции и базу знаний. Клиент может перебить его, уточнить вопрос или задать новый.",
        feature3Title: "Подключить вашу команду",
        feature3Desc: "Заранее определяем, когда переводить звонок или оставлять запрос на обратную связь. Вопросами вне сценария занимаются сотрудники.",
        feature4Title: "Выбрать голос бренда",
        feature4Desc: "Выберите голос или обсудите клонирование голоса диктора с его согласия.",
        feature5Title: "Сохранить результат в CRM",
        feature5Desc: "Подключаем нужные поля и действия, чтобы сотрудники видели результат звонка и могли продолжить работу с клиентом.",
        featureInterrupted: "Разговор прерван",
        featureNoiseCanceled: "Шум подавлен",
        featureOr: "или",
        featureAutoSync: "Автосинхронизация",
        engineDialingLabel: "Набор номера",
        engineSttMapping: "Сопоставление STT",
        engineCrmSync: "Синхронизация CRM",
        engineSecureSync: "Защищённая синхронизация ядра",
        enginePerformanceTitle: "ПОКАЗАТЕЛИ ПРОИЗВОДИТЕЛЬНОСТИ SYNCALL",
        engineDiagnosticsOnline: "ДИАГНОСТИКА: ОНЛАЙН",

        // Numbers
        numbersLabel: "Syncall AI в цифрах",
        numbersTitle: "Ускорение бизнес-показателей с Syncall AI",
        numbersStat1Value: "80%",
        numbersStat1Label: "Уровень успешного решения вопросов при первом контакте (FCR)",
        numbersStat2Value: "-70%",
        numbersStat2Label: "Снижение расходов на поддержку клиентов",
        numbersStat3Value: "94%",
        numbersStat3Label: "Средний показатель CSAT после внедрения Syncall",
        numbersDesc: "Ощутите силу автоматизации с продвинутыми голосовыми агентами Syncall AI — трансформируйте клиентскую поддержку, снизьте затраты и повысьте удовлетворённость клиентов.",
        getStarted: "Начать",

        // How
        howTitle: "Как подключить",
        howStep1Title: "Расскажите, о чём звонят клиенты",
        howStep1Text: "Пришлите частые вопросы и ответы, которые должны услышать ваши клиенты.",
        howStep2Title: "Поговорите с роботом сами",
        howStep2Text: "Мы подготовим робота. Вы проверите его ответы и скажете, что нужно изменить.",
        howStep3Title: "Подключите к своему номеру",
        howStep3Text: "Мы проверим вашу телефонию и согласуем цену. После этого робот сможет принимать звонки.",
        howStep4Title: "Запускаем и улучшаем",
        howStep4Text: "Начинаем с согласованного сценария. Вместе с командой оцениваем результаты звонков и дорабатываем агента.",

        // FAQ
        faqTitle: "Частые вопросы",
        faqQ1: "Это запись или с ним можно поговорить?",
        faqA1: "Можно поговорить. Робот слушает ваш вопрос и отвечает. Попробуйте разговор в начале этой страницы.",
        faqQ2: "Откуда он знает ответы?",
        faqA2: "Вы даёте информацию о компании: часы работы, услуги, цены и ответы на частые вопросы. Перед запуском вы проверяете, что он отвечает правильно.",
        faqQ3: "А если робот не сможет ответить?",
        faqA3: "До запуска договоримся, что делать в таких случаях. Робот может перевести звонок на человека или принять просьбу перезвонить — в зависимости от вашей телефонии.",
        faqQ4: "Нужно менять номер телефона?",
        faqA4: "Сначала проверим, можно ли подключить робота к вашему номеру и телефонии. Если что-то потребуется изменить, объясним это до начала работы.",
        faqQ5: "На каких языках он говорит?",
        faqA5: "На узбекском, русском и английском. Перед запуском можно проверить, как он понимает речь ваших клиентов и названия ваших товаров или услуг.",
        faqQ6: "Сколько это стоит?",
        faqA6: "Цена зависит от количества и длительности звонков, а также настройки. Стоимость согласуем заранее. Можно запросить бесплатный тест до 1 000 звонков — команда расскажет об условиях.",

        // ===== Product nav (tabs) =====
        navVoiceAgents: "Телефонный робот",
        navAnalytics: "Проверка звонков",
        navStt: "Речь в текст · Студия",
        navTts: "Текст в речь · Студия",

        // ===== Products strip =====
        pnLabel: "Другие возможности Syncall",
        pnTitle: "Помощь со звонками и сообщениями",
        pnSubtitle: "",
        pnKindProduct: "Продукт",
        pnKindApi: "API",
        pnYouAreHere: "Вы здесь",
        pnVoiceName: "Ответы на звонки",
        pnVoiceDesc: "Помощник разговаривает с клиентами по телефону и отвечает на их вопросы.",
        pnVoiceStat: "ответ < 1.5с · 24/7",
        pnAnalyticsName: "Проверка разговоров сотрудников",
        pnAnalyticsDesc: "Находит ошибки и вопросы без ответа в записях звонков. Не нужно прослушивать всё вручную.",
        pnAnalyticsStat: "100% охват",
        pnSttName: "STT",
        pnSttDesc: "API распознавания речи для узбекских диалектов и смешанной речи.",
        pnSttStat: "95% точность",
        pnTtsName: "TTS",
        pnTtsDesc: "API синтеза речи и клонирования голоса, неотличимого от человеческого.",
        pnTtsStat: "< 200мс",

        // ===== Shared demo =====
        demoModeLive: "Live API",
        demoModeSample: "Демо-режим",
        demoMicError: "Не удалось получить доступ к микрофону. Проверьте разрешения.",
        demoApiError: "Запрос не выполнен. Попробуйте ещё раз.",
        demoSampleNote: "Демо показывает образец результата. Для подключения live API свяжитесь с нами.",
        demoCtaSecondary: "Получить доступ к API",

        // ===== Analytics page =====
        anBadge: "Проверка звонков",
        anHeroTitle: "Узнайте, как сотрудники разговаривают с клиентами.",
        anHeroSubtitle: "Syncall проверяет записи звонков, отмечает ошибки и вопросы без ответа. Вы видите, какие разговоры стоит проверить подробнее.",
        anHeroCta: "Проверить наши записи",
        anHeroCta2: "Посмотреть пример отчёта",
        anScoreCardTitle: "Оценка звонка",
        anScoreRow1: "Соблюдение скрипта",
        anScoreRow2: "Культура общения",
        anScoreRow3: "Решение вопроса",
        anScoreRow4: "Потенциал продажи",
        anScoreTagOk: "Приветствие выполнено",
        anScoreTagWarn: "Возражение не отработано",
        anStat1: "контроль звонков",
        anStat2: "стоимость проверки качества",
        anStat3: "анализ на трёх языках",
        anProblemLabel: "Проблема",
        anProblemTitlePre: "Что можно упустить",
        anProblemTitlePost: "в ежедневных звонках",
        anProb1Title: "Ошибки операторов",
        anProb1Desc: "При выборочном прослушивании большинство ошибок и грубостей остаются незамеченными.",
        anProb2Title: "Скрытые «не купил»",
        anProb2Desc: "Никто не разбирает, почему клиент не купил — причины теряются.",
        anProb3Title: "Кто реально работает?",
        anProb3Desc: "Нет объективной метрики реальной эффективности операторов.",
        anProb4Title: "Субъективное обучение",
        anProb4Desc: "Тренинг строится на личных впечатлениях, а не на данных.",
        anProb5Title: "Жалобы приходят поздно",
        anProb5Desc: "О проблемных звонках узнают уже после ухода клиента.",
        anProb6Title: "Руководитель не видит",
        anProb6Desc: "В управлении только общие догадки вместо реальных показателей.",
        anPipeLabel: "Процесс",
        anPipeTitle: "От записи — к списку того, что нужно проверить",
        anPipeSubtitle: "Выберите, что важно: приветствие, ответ на вопрос клиента или соблюдение ваших правил.",
        anPipe1Title: "Звонок",
        anPipe1Desc: "Аудио автоматически загружается из телефонии или записей.",
        anPipe2Title: "Текст разговора",
        anPipe2Desc: "Запись превращается в текст, который можно прочитать.",
        anPipe3Title: "Проверка важных шагов",
        anPipe3Desc: "Поздоровался ли сотрудник? Ответил ли на вопрос?",
        anPipe4Title: "Отметки об ошибках",
        anPipe4Desc: "Видно, где разговор не соответствует вашим требованиям.",
        anPipe5Title: "Отчёт для руководителя",
        anPipe5Desc: "Откройте отмеченные разговоры и решите, что делать дальше.",
        anResultsLabel: "Результаты",
        anResultsTitle: "Из выборочного контроля — в сплошной и измеримый",
        anResult1: "рост балла качества",
        anResult2: "снижение жалоб",
        anResult3: "больше проверенных звонков",
        anCtaTitle: "Увидьте реальную картину ваших звонков",
        anCtaSubtitle: "Поделитесь типичными записями и критериями проверки. Вместе согласуем выборку, сроки и объём пилота.",
        anDeployLabel: "Развёртывание",
        anDeployTitle: "Cloud или On-Premise — на ваших серверах",
        anDeploySubtitle: "Как и Voice Agents, Analytics может работать полностью On-Premise. Все аудиозаписи и анализ остаются в вашей внутренней сети — идеально для банков и госструктур.",
        anDeployCloud: "Syncall Cloud",
        anDeployOnprem: "On-Premise — на вашем сервере",

        // ===== STT page =====
        sttBadge: "Speech-to-Text API",
        sttHeroTitle: "Самое точное распознавание узбекской речи",
        sttHeroSubtitle: "API распознавания речи, которое работает с диалектами, сленгом и узбекско-русским код-свитчингом. Обучено на реальных записях звонков.",
        sttHeroCta: "Получить API-ключ",
        sttSpec1: "точность (с диалектами)",
        sttSpec2: "задержка (real-time)",
        sttSpec3: "поддерживаемые языки",
        sttSpec4: "непрерывный поток",
        sttCapsLabel: "Возможности",
        sttCapsTitle: "Создано для живой речи",
        sttCap1Title: "Диалекты и смешанная речь",
        sttCap1Desc: "Понимает узбекские диалекты, сленг и переключение узб/рус внутри одной фразы.",
        sttCap2Title: "Шумоподавление",
        sttCap2Desc: "Отсекает уличный шум, музыку и фон, выделяя только голос.",
        sttCap3Title: "Тайм-коды на уровне слов",
        sttCap3Desc: "Точность и временная метка для каждого слова — для аналитики и субтитров.",
        sttCap4Title: "Streaming и batch",
        sttCap4Desc: "Поток в реальном времени или массовая обработка больших объёмов записей.",
        sttUseLabel: "Применение",
        sttUseTitle: "Как команды используют STT",
        sttUse1Title: "Аналитика звонков",
        sttUse1Desc: "Переводите записи в текст и автоматически анализируйте качество и темы.",
        sttUse2Title: "Субтитры в реальном времени",
        sttUse2Desc: "Добавляйте мгновенную транскрипцию к живым звонкам и встречам.",
        sttUse3Title: "Голосовые агенты",
        sttUse3Desc: "Этап понимания для Voice Agents с минимальной задержкой.",
        sttCtaTitle: "Превратите речь в точный текст",
        sttCtaSubtitle: "Пришлите аудио — покажем точность на ваших данных. Свяжитесь для API-ключа и цен.",
        sttDemoTitle: "Попробуйте STT-демо",
        sttDemoSubtitle: "Запишите, загрузите аудио или выберите образец — переведём в текст.",
        sttLangLabel: "Язык",
        sttInputLabel: "Аудио на входе",
        sttRecord: "Записать",
        sttStop: "Стоп",
        sttUpload: "Загрузить файл",
        sttSample: "Образец",
        sttRun: "Распознать",
        sttRunning: "Обработка...",
        sttResultLabel: "Транскрипция",
        sttConfidence: "уверенность",

        // ===== TTS page =====
        ttsBadge: "Text-to-Speech API",
        ttsHeroTitle: "Синтез речи, неотличимый от человеческого голоса",
        ttsHeroSubtitle: "Превращайте текст в естественную речь или клонируйте голос вашего лучшего оператора. Узбекский, русский и английский с низкой задержкой.",
        ttsHeroCta: "Получить API-ключ",
        ttsSpec1: "задержка синтеза",
        ttsSpec2: "схожесть клона голоса",
        ttsSpec3: "качество аудио",
        ttsSpec4: "языки",
        ttsCapsLabel: "Возможности",
        ttsCapsTitle: "Говорите голосом вашего бренда",
        ttsCap1Title: "Клонирование голоса",
        ttsCap1Desc: "Создаёт точную цифровую копию голоса оператора из 30 минут чистой записи.",
        ttsCap2Title: "Естественная интонация",
        ttsCap2Desc: "Живое звучание с ударениями, паузами и интонацией, как у человека.",
        ttsCap3Title: "Управление речью",
        ttsCap3Desc: "Контроль скорости, тона и произношения — числа и термины читаются верно.",
        ttsCap4Title: "Streaming с низкой задержкой",
        ttsCap4Desc: "Поток аудио для диалогов в реальном времени — ответ стартует за 200мс.",
        ttsUseLabel: "Применение",
        ttsUseTitle: "Как команды используют TTS",
        ttsUse1Title: "Голосовые агенты",
        ttsUse1Desc: "Синтезирует ответы Voice Agents естественным голосом.",
        ttsUse2Title: "IVR и оповещения",
        ttsUse2Desc: "Создавайте динамические IVR-меню и уведомления в реальном времени.",
        ttsUse3Title: "Озвучка контента",
        ttsUse3Desc: "Голос для аудиогидов, обучения и маркетингового контента.",
        ttsCtaTitle: "Дайте вашему бренду голос",
        ttsCtaSubtitle: "Свяжитесь с нами для клонирования голоса и интеграции API.",
        ttsDemoTitle: "Попробуйте TTS-демо",
        ttsDemoSubtitle: "Введите текст, выберите голос — озвучим.",
        ttsVoiceLabel: "Голос",
        ttsVoiceAziza: "Азиза",
        ttsVoiceJahongir: "Жахонгир",
        ttsVoiceDmitry: "Дмитрий",
        ttsVoiceEmma: "Эмма",
        ttsTextLabel: "Текст",
        ttsUseSample: "Образец текста",
        ttsRun: "Озвучить",
        ttsRunning: "Синтез...",
        ttsSampleUz: "Assalomu alaykum! Syncall AI bilan bog'langaningiz uchun rahmat. Sizga qanday yordam bera olaman?",
        ttsSampleRu: "Здравствуйте! Спасибо за обращение в Syncall AI. Чем я могу вам помочь?",
        ttsSampleEn: "Hello! Thanks for contacting Syncall AI. How can I help you today?",

        // ===== Chatbots (nav + strip) =====
        navChatbots: "Ответы на сообщения",
        pnChatbotsName: "Ответы на сообщения",
        pnChatbotsDesc: "Отвечает на частые вопросы на сайте и в Telegram по информации о вашей компании.",
        pnChatbotsStat: "On-Premise · UZ·RU",

        // ===== Chatbots page =====
        cbBadge: "Ответы на сообщения",
        cbHeroTitle: "Отвечайте клиентам в переписке, даже когда сотрудники заняты.",
        cbHeroSubtitle: "Помощник отвечает на частые вопросы на сайте и в Telegram. Вы даёте ему информацию о своей компании.",
        cbHeroCta: "Обсудить помощника для переписки",
        cbHeroCta2: "Посмотреть возможности",
        cbChatOnPrem: "On-Premise сервер",
        cbChatEncrypted: "Шифрование",
        cbChatMsg1: "Здравствуйте! Прошёл ли мой вчерашний платёж?",
        cbChatMsg2: "Здравствуйте! Да, платёж №5894 успешно прошёл. Чем ещё помочь?",
        cbChatMsg3: "Когда следующий платёж?",
        cbChatMsg4: "Следующий платёж 30 июня, сумма 1 250 000 сум. Прислать напоминание?",
        cbChatPlaceholder: "Напишите сообщение...",
        cbSpec1: "полностью на вашем сервере",
        cbSpec2: "данных на внешние серверы",
        cbSpec3: "языка (с диалектами)",
        cbSpec4: "бесперебойная работа",
        cbWhyLabel: "Почему On-Premise",
        cbWhyTitle: "Выберите, где будет работать чат-бот",
        cbWhySubtitle: "Обсудите облако или свои серверы, включая хранение, доступ и подключения к мессенджерам.",
        cbDeployCloudTag: "Облако",
        cbDeployCloudTitle: "Syncall Cloud",
        cbDeployCloud1: "Быстрый запуск, без своей инфраструктуры",
        cbDeployCloud2: "Автообновления и масштабирование",
        cbDeployCloud3: "Идеально для малого и среднего бизнеса",
        cbDeployOnpremTag: "На ваших серверах",
        cbDeployOnpremTitle: "Ваши серверы",
        cbDeployOnprem1: "Выберите место размещения моделей и записей разговоров",
        cbDeployOnprem2: "Проверьте архитектуру с вашей командой безопасности",
        cbDeployOnprem3: "Полный контроль: модели, логи, права доступа",
        cbCapsLabel: "Возможности",
        cbCapsTitle: "Чат-боты корпоративного уровня",
        cbCap1Title: "Полностью On-Premise",
        cbCap1Desc: "Разместите чат-бота на своей инфраструктуре. Согласуем внешние системы и каналы сообщений, к которым он подключается.",
        cbCap2Title: "Безопасность данных",
        cbCap2Desc: "До запуска определите с командой требования к доступу, журналам и обработке данных.",
        cbCap3Title: "Мультиканальность",
        cbCap3Desc: "Telegram, веб-виджет, WhatsApp и чат внутри приложения — из единой системы.",
        cbCap4Title: "CRM и база знаний",
        cbCap4Desc: "Отвечает на основе ваших документов и CRM, автоматически обновляет записи.",
        cbCap5Title: "Узбекский и русский",
        cbCap5Desc: "Проверьте привычные клиентам выражения, смешанную речь и названия продуктов.",
        cbCap6Title: "Передача оператору",
        cbCap6Desc: "Определите, какие запросы передавать сотрудникам и как сохранять контекст разговора.",
        cbUseLabel: "Применение",
        cbUseTitle: "Где работают чат-боты",
        cbUse1Title: "Автоматизация поддержки",
        cbUse1Desc: "Отвечайте на повторяющиеся вопросы по базе знаний, в том числе вне рабочего времени.",
        cbUse2Title: "Квалификация лидов",
        cbUse2Desc: "Квалифицирует входящие запросы и передаёт готовые лиды в отдел продаж.",
        cbUse3Title: "Внутренний helpdesk",
        cbUse3Desc: "Безопасный помощник для сотрудников по HR, IT и внутренним процессам.",
        cbCtaTitle: "Автоматизируйте, сохраняя данные в безопасности",
        cbCtaSubtitle: "Свяжитесь с нами, чтобы развернуть On-Premise чат-бот в вашей инфраструктуре.",

        // Footer
        footerRights: "Все права защищены",
        contactMethod: "Как с вами связаться?",
        contactByPhone: "Телефон",
        contactByEmail: "Email",
        contactOptional: "Добавить подробности (необязательно)",
        contactPilotTitle: "Попробуйте на своих звонках",
        contactPilotSubtitle: "Оставьте контакты. Мы свяжемся с вами и договоримся о тесте для вашей компании.",
        contactDemoTitle: "Обсудим задачу вашей компании",
        contactDemoSubtitle: "Оставьте контакты. Обсудим ваши звонки, ответим на вопросы и расскажем о стоимости.",
        contactProduct: "С чем нужна помощь?",
        contactProductVoice: "Отвечать на звонки",
        contactProductAnalytics: "Проверять разговоры сотрудников",
        contactProductChatbots: "Отвечать на сообщения",
        contactVolumeInvalid: "Укажите положительное число звонков.",
        studioStripTitle: "Нужно озвучить текст или получить текст из записи?",
        studioStripBody: "Это можно сделать самостоятельно в Syncall Studio.",
        studioStt: "Запись в текст →",
        studioTts: "Текст в голос →",
        liveDemoTitle: "Попробуйте поговорить с AI",
        liveDemoBody: "Для запуска демо потребуются подтверждение телефона и доступ к микрофону.",
        demoListenFor: "Оцените произношение, темп речи и ход разговора.",
        demoPlay: "Слушать",
        demoPause: "Пауза",
        demoTranscript: "Прочитать расшифровку",
        pilotLabel: "Начните с одной задачи",
        pilotTitle: "Проверьте Syncall на ваших звонках",
        pilotBody: "Запросите бесплатный пилот — до 1 000 тестовых звонков. Сначала согласуем сценарий, интеграции и критерии успеха.",
        pilotNote: "До принятия решения вы получите предложение с единицей тарификации, стоимостью подключения и телефонии, а также условиями пилота.",
        pilotPricing: "Как формируется цена →",
        viewSolution: "Как это работает →",
        customerStoriesTitle: "Что меняется у наших клиентов",
        customerStoriesLabel: "Опыт клиентов",
        customerBefore: "До Syncall",
        customerAfter: "Со Syncall",
        customerResult: "Результат",
        analyticsExample: "Пример отчёта — иллюстративные данные",
        analyticsExampleTitle: "Поймите, какие звонки стоит проверить",
        analyticsExampleBody: "Прочитайте расшифровку, найдите пропущенные шаги и решите, что команде делать дальше.",
        chatbotExample: "Пример разговора",
        heroLanguageNote: "На узбекском и русском. Днём и ночью.",
        heroTryLive: "Поговорить с роботом",
        heroSeeExamples: "Что он умеет",
        callWidgetLoading: "Готовим разговор…",
        callWidgetScenario: "Выберите пример разговора",
        examplesIntro: "Подключаем робота к CRM — вашей базе клиентов — и системе учёта платежей. Во время звонка он проверяет данные, отвечает по ним и сохраняет результат разговора.",
        exampleLabel: "Пример",
        exampleCustomer: "Клиент",
        exampleLookupLabel: "Проверяет данные во время звонка",
        example1Title: "Звонки для продаж",
        example1Body: "Звонит по заявкам, уточняет потребности и подбирает предложение по данным из CRM. Сохраняет договорённости для менеджера.",
        example1Context: "Фрагмент исходящего звонка по заявке.",
        example1Question: "Нужен интернет домой, но не дороже 150 тысяч в месяц.",
        example1Lookup: "CRM: адрес из заявки. Проверка подключения: по адресу доступно 100 Мбит/с за 120 000 сум в месяц.",
        example1Answer: "По вашему адресу есть тариф за 120 тысяч сум в месяц. Скорость — 100 мегабит. Когда удобно, чтобы менеджер связался для оформления?",
        example1Reply: "Подходит. Завтра после трёх.",
        example1Result: "В CRM: выбранный тариф, бюджет до 150 000 сум, перезвонить завтра после 15:00.",
        example2Title: "Коллекшн",
        example2Body: "Проверяет задолженность и последние платежи в биллинге — системе учёта оплат. Выясняет причину задержки и договаривается о дате платежа.",
        example2Context: "Фрагмент исходящего звонка после проверки клиента.",
        example2Question: "Я вчера оплатил 150 тысяч. Сколько ещё осталось?",
        example2Lookup: "Биллинг: начислено 600 000 сум, платёж 150 000 сум зачислен. Остаток — 450 000 сум.",
        example2Answer: "Ваш платёж уже учтён. Осталось 450 тысяч сум. Когда сможете оплатить остаток?",
        example2Reply: "В пятницу, когда получу зарплату.",
        example2Result: "В CRM: обещание оплатить 450 000 сум в пятницу, причина задержки — ожидание зарплаты.",
        example3Title: "Входящая линия",
        example3Body: "Находит данные клиента, проверяет оплату, заказ или статус услуги. Объясняет, что произошло, и создаёт обращение в CRM.",
        example3Context: "Фрагмент входящего звонка от абонента.",
        example3Question: "Я оплатил интернет, почему он не работает?",
        example3Lookup: "Биллинг: оплата зачислена, баланс положительный. CRM: авария по адресу клиента, работы до 18:00.",
        example3Answer: "Оплата поступила. Интернет не работает из-за аварии по вашему адресу. По данным техслужбы, её планируют устранить до шести вечера. Оставить обращение?",
        example3Reply: "Да, пожалуйста.",
        example3Result: "В CRM создано обращение: данные клиента, результаты проверки и суть разговора переданы в поддержку.",
        pnHomeTitle: "Для переписки и проверки разговоров",
        howCta: "Обсудить подключение",
        howNote: "Можно начать с бесплатного теста до 1 000 звонков. Что входит в тест, согласуем заранее.",
        navPlainFeatures: "Что умеет",
        navRecordings: "Записи звонков",
        navSetup: "Как подключить",
    },
    en: {
        // Navbar
        home: "Home",
        features: "Why us",
        howItWorks: "Launch",
        demo: "Demo",
        faq: "FAQ",
        contactSales: "Contact",
        creatorStudio: "Studio",

        // Hero
        heroBadge: "For businesses that work with customers by phone",
        heroTitle: "A phone assistant for your customers.",
        heroSubtitle: "Syncall makes sales calls, follows up on overdue payments, and answers incoming calls. It uses data from your business systems during the conversation.",
        heroFeature1: "Incoming & outgoing calls",
        heroFeature2: "Uzbek & Russian",
        heroFeature3: "Your phone system & CRM",
        tryDemo: "Listen to a recording",
        ctaDemo: "Talk to us",
        ctaTrial: "Try it for my business",
        ctaTelegram: "Message us on Telegram",
        navMarketingFeatures: "What it does",
        navUseCases: "Examples",
        navIntegrations: "Phone systems & software",
        navPricing: "Pricing",
        navAbout: "About",
        navMenu: "Open navigation",
        navClose: "Close navigation",
        primaryNavigation: "Primary navigation",
        languageSelectorLabel: "Language selector",
        switchLightTheme: "Switch to light theme",
        switchDarkTheme: "Switch to dark theme",
        skipToContent: "Skip to main content",
        loading: "Loading…",
        footerProducts: "Products",
        footerCompany: "Company",
        useCaseBanking: "Banking",
        useCaseDebt: "Debt collection",
        useCaseReminders: "Appointment reminders",
        useCaseSurveys: "Surveys",
        useCaseLeads: "Lead qualification",
        caseStudies: "Customer examples",
        contactTitle: "Let’s discuss your business",
        contactSubtitle: "Leave your number or email. We’ll contact you to discuss what you need.",
        contactName: "Name",
        contactCompany: "Company",
        contactEmail: "Email",
        contactPhone: "Phone",
        contactVolume: "Monthly calls (optional)",
        contactLanguages: "Languages needed (optional)",
        contactMessage: "Tell us about your task (optional)",
        contactSubmit: "Send request",
        contactSubmitting: "Sending…",
        contactSuccess: "Thank you. We’ll contact you using the details you provided.",
        contactError: "We couldn't send your request. Try again or message us on Telegram.",
        contactConfigError: "The form destination is not configured yet. Please message us on Telegram for now.",
        contactRequired: "Complete the required fields.",
        contactEmailInvalid: "Enter a valid email address.",
        trustTitle: "Trust components ready for real customer proof",
        trustPlaceholder: "PLACEHOLDER — needs real data",
        metricMethodology: "How we measure these figures",
        metricMethodologyNote: "Figures are measured in production Syncall deployments, not synthetic benchmarks. Actual results vary by use case.",
        metricResolution: "Issues resolved by the AI agent without transfer to a human operator",
        metricCost: "Lower operating cost",
        metricScale: "Calls per minute",

        // Talk Bot
        talkBotTitle: "Experience our AI Voice Agent",
        talkBotSubtitle: "Hear for yourself how natural our AI sounds",
        talkBotButton: "Listen to Demo",

        // Partners
        partnersLabel: "Our Partners",

        // Calllog
        calllogTitle: "Hear it on a phone call",
        calllogSubtitle: "Two recordings in Uzbek: answering a call and making a call.",
        callIncoming: "Answering a call",
        callOutgoing: "Making a call",

        // Visual Engine Pipeline
        engineTitle: "Syncall Voice Engine Technology Stack",
        engineSubtitle: "An automated end-to-end call processing system: from bilateral audio stream to branded speech synthesis",
        engineCard1Title: "1. Dual Audio Stream",
        engineCard1Desc: "Receives inbound or performs outbound calls. Integrated Voice Isolation automatically filters out background music and noise.",
        engineCard2Title: "2. Recognition & Analysis (STT & LLM)",
        engineCard2Desc: "Transcribes bilingual speech (Uzbek/Russian) accounting for local dialects and mixed-language slang with 95% accuracy.",
        engineCard3Title: "3. CRM Integration",
        engineCard3Desc: "Secure connection (On-Premise or Private Cloud) with your CRM database to retrieve profiles and instantly update records.",
        engineCard4Title: "4. Human-like Speech Synthesis (TTS)",
        engineCard4Desc: "Generates high-fidelity voice responses under 0.5s cloned from your top agent, creating comfortable and natural customer experiences.",

        // Features
        featuresTitle: "Which calls can it handle?",
        feature1Stat: "1000+ calls/min",
        heroLiveAnalysis: "Live call analysis",
        callWidgetTitle: "Try talking to it",
        callWidgetSubtitle: "Verify your phone number. You’ll need a microphone to talk.",
        callWidgetCta: "Start talking",
        callWidgetTelegramCta: "Verify my number & talk",
        callWidgetTelegramVerifying: "Verifying with Telegram",
        callWidgetTelegramVerifyingSub: "In the Telegram window, allow access to your phone number to continue.",
        callWidgetDialing: "Connecting",
        callWidgetConnecting: "Connecting to the AI agent",
        callWidgetErrorTitle: "Could not connect",
        callWidgetErrorSubtitle: "You can still hear the assistant in the recordings below.",
        callWidgetDemoCta: "Listen to a recording",
        callWidgetRetry: "Try again",
        callWidgetInvalidPhone: "Enter a valid number",
        callWidgetConsent: "This demo conversation is recorded.",
        callWidgetTelegramConsent: "Telegram verifies your number. This demo conversation is recorded.",
        callWidgetQueued: "You are in the queue",
        callWidgetQueuedSub: "Your position: ",
        callWidgetMicTitle: "Allow microphone access",
        callWidgetMicSub: "The microphone is needed to talk to the AI agent",
        callWidgetLive: "Call in progress",
        callWidgetLiveSub: "Speak — the agent can hear you",
        callWidgetEndedTitle: "Call ended",
        callWidgetEndedSub: "Thanks! Try again or listen to the demo calls",
        callWidgetCancel: "Cancel",
        callWidgetYou: "You",
        callWidgetAgent: "Agent",
        callWidgetTranscript: "Conversation transcript",
        callWidgetMute: "Mute microphone",
        callWidgetUnmute: "Unmute microphone",
        callWidgetLanguage: "Choose a language",
        callWidgetUnavailable: "The live conversation is unavailable",
        callWidgetErrVerify: "Please complete verification and try again",
        callWidgetErrTelegram: "Telegram verification did not complete. Please try again",
        callWidgetErrPhoneMismatch: "Your Telegram number does not match the number entered",
        callWidgetErrMic: "Microphone access is required for the voice demo",
        callWidgetErrConflict: "You already have an active demo session",
        callWidgetErrLimit: "You have reached the demo limit. Please try again later",
        callWidgetErrBusy: "The demo is busy right now. Please try again later",
        callWidgetErrQueueExpired: "Your queue reservation expired. Please try again",
        callWidgetErrWindowExpired: "The connection window expired. Please start again",
        callWidgetErrOrigin: "The demo is unavailable at this website address. Please try again later.",
        callWidgetErrGeneric: "The demo could not start. Please try again later",
        voiceCloneMatch: "99.2% match",
        feature1TagDialect: "Dialects",
        feature1TagMix: "Language mix",
        feature1TagSlang: "Slang",
        feature1Title: "Understand the question",
        feature1Desc: "Customers speak in Uzbek or Russian, including mixed-language conversations. Test your customers’ accents and vocabulary during the pilot.",
        feature2Title: "Answer from your information",
        feature2Desc: "The agent follows the workflow and knowledge you provide. Customers can interrupt to clarify or ask another question.",
        feature3Title: "Keep your team in control",
        feature3Desc: "Agree when the AI should transfer a call or request a callback. Your team handles questions outside the automated workflow.",
        feature4Title: "Choose a voice for your brand",
        feature4Desc: "Choose a voice or discuss cloning a speaker’s voice with their permission.",
        feature5Title: "Keep the outcome in your CRM",
        feature5Desc: "Connect the fields and actions your workflow needs so your team can see the call result and follow up.",
        featureInterrupted: "Interrupted",
        featureNoiseCanceled: "Noise canceled",
        featureOr: "or",
        featureAutoSync: "Auto-sync",
        engineDialingLabel: "Dialing",
        engineSttMapping: "STT engine mapping",
        engineCrmSync: "CRM sync",
        engineSecureSync: "Secure core sync",
        enginePerformanceTitle: "SYNCALL PERFORMANCE SPECS",
        engineDiagnosticsOnline: "DIAGNOSTICS: ONLINE",

        // Numbers
        numbersLabel: "Syncall AI in Numbers",
        numbersTitle: "Accelerating Success with Syncall AI",
        numbersStat1Value: "80%",
        numbersStat1Label: "First Contact Resolution (FCR) rate achieved by our AI",
        numbersStat2Value: "-70%",
        numbersStat2Label: "Reduction in customer support operational overhead",
        numbersStat3Value: "94%",
        numbersStat3Label: "Average Customer Satisfaction (CSAT) rating after implementation",
        numbersDesc: "Leverage the power of automation with Syncall AI's advanced voice agents — transform customer support, cut costs, and boost customer satisfaction.",
        getStarted: "Get Started",

        // How
        howTitle: "How to get started",
        howStep1Title: "Tell us what customers ask",
        howStep1Text: "Share your common questions and the answers you want customers to hear.",
        howStep2Title: "Try a few conversations",
        howStep2Text: "We set up the assistant. You talk to it, check its answers, and tell us what to change.",
        howStep3Title: "Connect your phone number",
        howStep3Text: "We check your phone setup and agree the price. Then the assistant can start taking calls.",
        howStep4Title: "Launch and review",
        howStep4Text: "Start with the agreed workflow. Review call outcomes with your team and improve the agent using what you learn.",

        // FAQ
        faqTitle: "Questions you might have",
        faqQ1: "Is it a recording or can I talk to it?",
        faqA1: "You can talk to it. It listens to your question and replies. Try a conversation at the top of this page.",
        faqQ2: "Where does it get its answers?",
        faqA2: "From the information you give us: your opening hours, services, prices, and answers to common questions. You check its replies before launch.",
        faqQ3: "What if it cannot answer a question?",
        faqA3: "We decide this with you before launch. It can transfer the call to a person or take a callback request, depending on your phone setup.",
        faqQ4: "Do I need a new phone number?",
        faqA4: "We first check whether the assistant can work with your current number and phone service. We explain any changes needed before you decide.",
        faqQ5: "Which languages does it speak?",
        faqA5: "Uzbek, Russian, and English. Before launch, you can check how it handles your customers’ speech and your company’s terms.",
        faqQ6: "How much does it cost?",
        faqA6: "The price depends on the number and length of calls, and any setup work. We agree the cost with you first. You can request a free test of up to 1,000 calls; the team will confirm the conditions.",

        // ===== Product nav (tabs) =====
        navVoiceAgents: "Phone assistant",
        navAnalytics: "Call reviews",
        navStt: "Speech to text · Studio",
        navTts: "Text to speech · Studio",

        // ===== Products strip =====
        pnLabel: "More from Syncall",
        pnTitle: "Help with calls and messages",
        pnSubtitle: "",
        pnKindProduct: "Product",
        pnKindApi: "API",
        pnYouAreHere: "You're here",
        pnVoiceName: "Answer phone calls",
        pnVoiceDesc: "An assistant that speaks to customers and answers their questions.",
        pnVoiceStat: "< 1.5s reply · 24/7",
        pnAnalyticsName: "Check staff conversations",
        pnAnalyticsDesc: "Find missed questions and mistakes in call recordings, without listening to each one yourself.",
        pnAnalyticsStat: "100% coverage",
        pnSttName: "STT",
        pnSttDesc: "Speech-to-text API for Uzbek dialects and mixed-language speech.",
        pnSttStat: "95% accuracy",
        pnTtsName: "TTS",
        pnTtsDesc: "Speech synthesis and voice-cloning API, indistinguishable from a human voice.",
        pnTtsStat: "< 200ms",

        // ===== Shared demo =====
        demoModeLive: "Live API",
        demoModeSample: "Demo mode",
        demoMicError: "Couldn't access the microphone. Check your permissions.",
        demoApiError: "Request failed. Please try again.",
        demoSampleNote: "This demo shows a sample result. Contact us to connect the live API.",
        demoCtaSecondary: "Request API access",

        // ===== Analytics page =====
        anBadge: "Call reviews",
        anHeroTitle: "Find out how your team speaks to customers.",
        anHeroSubtitle: "Syncall checks call recordings and points out mistakes and unanswered questions. You can see which conversations need a closer look.",
        anHeroCta: "Try it on our recordings",
        anHeroCta2: "See a sample report",
        anScoreCardTitle: "Call score",
        anScoreRow1: "Script adherence",
        anScoreRow2: "Communication",
        anScoreRow3: "Issue resolution",
        anScoreRow4: "Sales potential",
        anScoreTagOk: "Greeting completed",
        anScoreTagWarn: "Objection not handled",
        anStat1: "of calls controlled",
        anStat2: "cost of quality checks",
        anStat3: "analysis in three languages",
        anProblemLabel: "The problem",
        anProblemTitlePre: "Hear what you might miss",
        anProblemTitlePost: "in everyday calls",
        anProb1Title: "Operator mistakes",
        anProb1Desc: "With sampling, most errors and rude replies go completely unnoticed.",
        anProb2Title: "Hidden \"no sale\"",
        anProb2Desc: "Nobody reviews why a customer didn't buy — the reasons are lost.",
        anProb3Title: "Who actually performs?",
        anProb3Desc: "There's no objective metric for operators' real effectiveness.",
        anProb4Title: "Subjective training",
        anProb4Desc: "Coaching is based on personal impressions, not data.",
        anProb5Title: "Complaints arrive late",
        anProb5Desc: "You learn about problem calls only after the customer is gone.",
        anProb6Title: "Managers can't see",
        anProb6Desc: "Leadership runs on guesses instead of real metrics.",
        anPipeLabel: "The process",
        anPipeTitle: "From a recording to a list of things to check",
        anPipeSubtitle: "Choose what matters: greeting the customer, answering their question, or following your instructions.",
        anPipe1Title: "Call",
        anPipe1Desc: "Audio is loaded automatically from telephony or recordings.",
        anPipe2Title: "Written conversation",
        anPipe2Desc: "The recording becomes text you can read.",
        anPipe3Title: "Check the important steps",
        anPipe3Desc: "Did the employee greet the customer and answer the question?",
        anPipe4Title: "Mark what was missed",
        anPipe4Desc: "See where the conversation did not meet your requirements.",
        anPipe5Title: "Show the manager",
        anPipe5Desc: "Open the marked conversations and decide what to do next.",
        anResultsLabel: "Results",
        anResultsTitle: "From sampled control to full and measurable coverage",
        anResult1: "rise in quality score",
        anResult2: "fewer complaints",
        anResult3: "more calls reviewed",
        anCtaTitle: "See the real picture of your calls",
        anCtaSubtitle: "Share representative recordings and the checks you use today. We’ll agree the sample, timing, and pilot scope together.",
        anDeployLabel: "Deployment",
        anDeployTitle: "Cloud or On-Premise — on your own servers",
        anDeploySubtitle: "Like Voice Agents, Analytics can run fully on-premise. All recordings and analysis stay inside your network — ideal for banks and government organizations.",
        anDeployCloud: "Syncall Cloud",
        anDeployOnprem: "On-Premise — on your server",

        // ===== STT page =====
        sttBadge: "Speech-to-Text API",
        sttHeroTitle: "The most accurate Uzbek speech recognition",
        sttHeroSubtitle: "A speech recognition API that handles dialects, slang, and Uzbek-Russian code-switching. Trained on real call-center recordings.",
        sttHeroCta: "Get an API key",
        sttSpec1: "accuracy (with dialects)",
        sttSpec2: "latency (real-time)",
        sttSpec3: "supported languages",
        sttSpec4: "continuous streaming",
        sttCapsLabel: "Capabilities",
        sttCapsTitle: "Built for real-world speech",
        sttCap1Title: "Dialects & code-switching",
        sttCap1Desc: "Understands Uzbek dialects, slang, and Uzbek-Russian switching within a single sentence.",
        sttCap2Title: "Voice isolation",
        sttCap2Desc: "Strips out street noise, music, and background to capture just the voice.",
        sttCap3Title: "Word-level timestamps",
        sttCap3Desc: "Confidence and a timestamp for every word — for analytics and subtitles.",
        sttCap4Title: "Streaming & batch",
        sttCap4Desc: "Real-time streaming or bulk processing of large recording volumes.",
        sttUseLabel: "Use cases",
        sttUseTitle: "How teams use STT",
        sttUse1Title: "Call analytics",
        sttUse1Desc: "Turn recordings into text and analyze quality and topics automatically.",
        sttUse2Title: "Real-time captions",
        sttUse2Desc: "Add instant transcription to live calls and meetings.",
        sttUse3Title: "Voice agents",
        sttUse3Desc: "The understanding stage for Voice Agents, with minimal latency.",
        sttCtaTitle: "Turn speech into accurate text",
        sttCtaSubtitle: "Send us audio and we'll show accuracy on your own data. Contact us for an API key and pricing.",
        sttDemoTitle: "Try the STT demo",
        sttDemoSubtitle: "Record, upload audio, or pick a sample — we'll transcribe it.",
        sttLangLabel: "Language",
        sttInputLabel: "Audio input",
        sttRecord: "Record",
        sttStop: "Stop",
        sttUpload: "Upload file",
        sttSample: "Sample",
        sttRun: "Transcribe",
        sttRunning: "Processing...",
        sttResultLabel: "Transcript",
        sttConfidence: "confidence",

        // ===== TTS page =====
        ttsBadge: "Text-to-Speech API",
        ttsHeroTitle: "Speech synthesis indistinguishable from a human voice",
        ttsHeroSubtitle: "Turn text into natural speech, or clone your best operator's voice. Uzbek, Russian, and English with low latency.",
        ttsHeroCta: "Get an API key",
        ttsSpec1: "synthesis latency",
        ttsSpec2: "voice-clone similarity",
        ttsSpec3: "audio quality",
        ttsSpec4: "languages",
        ttsCapsLabel: "Capabilities",
        ttsCapsTitle: "Speak in your brand's voice",
        ttsCap1Title: "Voice cloning",
        ttsCap1Desc: "Creates an exact digital copy of your operator's voice from 30 minutes of clean audio.",
        ttsCap2Title: "Natural prosody",
        ttsCap2Desc: "Lifelike delivery with stress, pauses, and intonation like a human speaker.",
        ttsCap3Title: "Speech control",
        ttsCap3Desc: "Control speed, tone, and pronunciation — numbers and terms read correctly.",
        ttsCap4Title: "Low-latency streaming",
        ttsCap4Desc: "Audio streaming for real-time dialogue — the reply starts within 200ms.",
        ttsUseLabel: "Use cases",
        ttsUseTitle: "How teams use TTS",
        ttsUse1Title: "Voice agents",
        ttsUse1Desc: "Synthesizes Voice Agents' replies in a natural voice.",
        ttsUse2Title: "IVR & notifications",
        ttsUse2Desc: "Build dynamic IVR menus and notifications in real time.",
        ttsUse3Title: "Content voiceover",
        ttsUse3Desc: "Voice for audio guides, training, and marketing content.",
        ttsCtaTitle: "Give your brand a voice",
        ttsCtaSubtitle: "Contact us for voice cloning and API integration.",
        ttsDemoTitle: "Try the TTS demo",
        ttsDemoSubtitle: "Enter text, pick a voice — we'll speak it.",
        ttsVoiceLabel: "Voice",
        ttsVoiceAziza: "Aziza",
        ttsVoiceJahongir: "Jahongir",
        ttsVoiceDmitry: "Dmitry",
        ttsVoiceEmma: "Emma",
        ttsTextLabel: "Text",
        ttsUseSample: "Sample text",
        ttsRun: "Speak it",
        ttsRunning: "Synthesizing...",
        ttsSampleUz: "Assalomu alaykum! Syncall AI bilan bog'langaningiz uchun rahmat. Sizga qanday yordam bera olaman?",
        ttsSampleRu: "Здравствуйте! Спасибо за обращение в Syncall AI. Чем я могу вам помочь?",
        ttsSampleEn: "Hello! Thanks for contacting Syncall AI. How can I help you today?",

        // ===== Chatbots (nav + strip) =====
        navChatbots: "Replies to messages",
        pnChatbotsName: "Reply to customer messages",
        pnChatbotsDesc: "Answer common questions on your website and in Telegram, using your business information.",
        pnChatbotsStat: "On-Premise · UZ·RU",

        // ===== Chatbots page =====
        cbBadge: "Replies to messages",
        cbHeroTitle: "Answer customer messages, even when your team is busy.",
        cbHeroSubtitle: "A chat assistant answers common questions on your website and in Telegram. You give it the information about your business.",
        cbHeroCta: "Discuss a chat assistant",
        cbHeroCta2: "See what it does",
        cbChatOnPrem: "On-Premise server",
        cbChatEncrypted: "Encrypted",
        cbChatMsg1: "Hi! Did my payment from yesterday go through?",
        cbChatMsg2: "Hello! Yes, payment #5894 went through successfully. Anything else?",
        cbChatMsg3: "When is the next payment due?",
        cbChatMsg4: "Your next payment is June 30, amount 1,250,000 UZS. Shall I send a reminder?",
        cbChatPlaceholder: "Type a message...",
        cbSpec1: "entirely on your server",
        cbSpec2: "data sent to outside servers",
        cbSpec3: "languages (with dialects)",
        cbSpec4: "always-on operation",
        cbWhyLabel: "Why on-premise",
        cbWhyTitle: "Choose where your chatbot runs",
        cbWhySubtitle: "Discuss cloud hosting or installation on your own servers, including storage, access, and connections to messaging services.",
        cbDeployCloudTag: "Cloud",
        cbDeployCloudTitle: "Syncall Cloud",
        cbDeployCloud1: "Fast launch, no infrastructure required",
        cbDeployCloud2: "Automatic updates and scaling",
        cbDeployCloud3: "Ideal for small and mid-size business",
        cbDeployOnpremTag: "On your servers",
        cbDeployOnpremTitle: "Your own servers",
        cbDeployOnprem1: "Choose where models and conversation records are hosted",
        cbDeployOnprem2: "Review the architecture with your security team",
        cbDeployOnprem3: "Full control: models, logs, access rights",
        cbCapsLabel: "Capabilities",
        cbCapsTitle: "Enterprise-grade chatbots",
        cbCap1Title: "Fully on-premise",
        cbCap1Desc: "Host the chatbot on your infrastructure. We agree which external systems or messaging channels it connects to.",
        cbCap2Title: "Data security",
        cbCap2Desc: "Define access, logging, and data-handling requirements with your team before launch.",
        cbCap3Title: "Multichannel",
        cbCap3Desc: "Telegram, web widget, WhatsApp, and in-app chat — all from one system.",
        cbCap4Title: "CRM & knowledge base",
        cbCap4Desc: "Answers from your own documents and CRM, and updates records automatically.",
        cbCap5Title: "Uzbek and Russian",
        cbCap5Desc: "Test the words, mixed-language messages, and product names your customers use.",
        cbCap6Title: "Human handoff",
        cbCap6Desc: "Agree which requests should go to an employee and how the conversation context is shared.",
        cbUseLabel: "Use cases",
        cbUseTitle: "Where chatbots work",
        cbUse1Title: "Support automation",
        cbUse1Desc: "Answer recurring questions from your knowledge base, including outside office hours.",
        cbUse2Title: "Lead qualification",
        cbUse2Desc: "Qualifies inbound requests and passes ready leads to your sales team.",
        cbUse3Title: "Internal helpdesk",
        cbUse3Desc: "A secure assistant for employees across HR, IT, and internal processes.",
        cbCtaTitle: "Automate while keeping your data secure",
        cbCtaSubtitle: "Contact us to deploy an on-premise chatbot inside your own infrastructure.",

        // Footer
        footerRights: "All rights reserved",
        contactMethod: "How should we contact you?",
        contactByPhone: "Phone",
        contactByEmail: "Email",
        contactOptional: "Tell us more (optional)",
        contactPilotTitle: "Try it with your own calls",
        contactPilotSubtitle: "Leave your contact details. We’ll get in touch to arrange a test for your company.",
        contactDemoTitle: "Let’s discuss your business",
        contactDemoSubtitle: "Tell us how to reach you. We’ll discuss your calls, answer your questions, and explain the cost.",
        contactProduct: "What do you need help with?",
        contactProductVoice: "Answering phone calls",
        contactProductAnalytics: "Checking staff conversations",
        contactProductChatbots: "Replying to messages",
        contactVolumeInvalid: "Enter a positive number of calls.",
        studioStripTitle: "Want to turn text into speech, or audio into text?",
        studioStripBody: "Do it yourself in Syncall Studio.",
        studioStt: "Audio to text →",
        studioTts: "Text to speech →",
        liveDemoTitle: "Try a conversation yourself",
        liveDemoBody: "The live demo requires phone verification and microphone access.",
        demoListenFor: "Listen for pronunciation, pace, and how the conversation flows.",
        demoPlay: "Play",
        demoPause: "Pause",
        demoTranscript: "Read the transcript",
        pilotLabel: "Start with one workflow",
        pilotTitle: "See how Syncall fits your calls",
        pilotBody: "Request a free pilot with up to 1,000 trial calls. We agree the scenario, integrations, and success criteria with you first.",
        pilotNote: "Your proposal will explain the billing unit, any setup or telephony charges, and the pilot conditions before you commit.",
        pilotPricing: "How pricing works →",
        viewSolution: "See how it works →",
        customerStoriesTitle: "What changes for our customers",
        customerStoriesLabel: "Customer experience",
        customerBefore: "Before Syncall",
        customerAfter: "With Syncall",
        customerResult: "Result",
        analyticsExample: "Illustrative report — example data",
        analyticsExampleTitle: "Know which calls need a closer look",
        analyticsExampleBody: "Review a transcript, see which checks were missed, and decide what your team should do next.",
        chatbotExample: "Illustrative conversation",
        heroLanguageNote: "Speaks Uzbek and Russian. Available day and night.",
        heroTryLive: "Talk to the assistant",
        heroSeeExamples: "See what it can do",
        callWidgetLoading: "Getting the conversation ready…",
        callWidgetScenario: "Choose a conversation",
        examplesIntro: "We connect the assistant to your CRM — your customer records — and billing system. During the call, it checks the data, uses it to answer, and saves the outcome.",
        exampleLabel: "Example",
        exampleCustomer: "Customer",
        exampleLookupLabel: "Checks data during the call",
        example1Title: "Sales calls",
        example1Body: "Calls people who have left an enquiry, asks what they need, and finds a suitable offer using CRM data. Saves the details for your sales team.",
        example1Context: "Part of an outbound call following an enquiry.",
        example1Question: "I need home internet, but no more than 150,000 som a month.",
        example1Lookup: "CRM: address from the enquiry. Availability check: 100 Mbps at this address for 120,000 som a month.",
        example1Answer: "There’s a 100-megabit plan at your address for 120,000 som a month. When would you like our team to call to arrange it?",
        example1Reply: "That works. Tomorrow after three.",
        example1Result: "Saved in the CRM: chosen plan, budget up to 150,000 som, callback tomorrow after 3 pm.",
        example2Title: "Debt collection",
        example2Body: "Checks the outstanding balance and recent payments in your billing system. Finds out why payment is late and agrees on a payment date.",
        example2Context: "Part of an outbound call after verifying the customer.",
        example2Question: "I paid 150,000 som yesterday. How much is left?",
        example2Lookup: "Billing: 600,000 som due, payment of 150,000 som received. Remaining balance: 450,000 som.",
        example2Answer: "Your payment has been recorded. There’s 450,000 som left. When will you be able to pay the rest?",
        example2Reply: "On Friday, when I get paid.",
        example2Result: "Saved in the CRM: promise to pay 450,000 som on Friday; reason for delay — waiting for payday.",
        example3Title: "Incoming calls",
        example3Body: "Finds the customer’s details and checks a payment, order, or service status. Explains what happened and creates a support request in the CRM.",
        example3Context: "Part of an incoming call from a subscriber.",
        example3Question: "I paid for my internet. Why isn’t it working?",
        example3Lookup: "Billing: payment received, balance positive. CRM: outage at the customer’s address, repairs scheduled until 6 pm.",
        example3Answer: "Your payment came through. There’s an outage at your address. The technical team expects to fix it by 6 pm. Would you like me to open a support request?",
        example3Reply: "Yes, please.",
        example3Result: "Support request created in the CRM with the customer’s details, checks performed, and a summary of the conversation.",
        pnHomeTitle: "For messages and call reviews, too",
        howCta: "Talk about my business",
        howNote: "You can start with a free test of up to 1,000 calls. We’ll confirm what’s included first.",
        navPlainFeatures: "What it does",
        navRecordings: "Call recordings",
        navSetup: "Getting started",
    }
};

const LANGUAGE_STORAGE_KEY = 'syncall-lang';

const readStoredLanguage = () => {
    try {
        const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
        return translations[stored] ? stored : null;
    } catch {
        return null;
    }
};

// Uzbekistan launch: Russian is the default. An explicit language selection
// and direct /ru or /uz links continue to take precedence.
const detectPreferredLanguage = () => 'ru';

export const LanguageProvider = ({ children }) => {
    const location = useLocation();
    const navigate = useNavigate();
    const language = getLocaleFromPath(location.pathname);

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    // First-load only: honor a remembered explicit choice, otherwise apply the
    // browser-language default. Never fires again during SPA navigation, so the
    // language switcher and direct /ru | /uz links keep working untouched.
    useEffect(() => {
        if (getLocaleFromPath(window.location.pathname) !== 'en') return;
        const target = readStoredLanguage() || detectPreferredLanguage();
        if (target === 'en') return;
        navigate(
            localizePath(
                `${window.location.pathname}${window.location.search}${window.location.hash}`,
                target,
            ),
            { replace: true },
        );
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const setLanguage = useCallback((nextLanguage) => {
        if (!translations[nextLanguage]) return;
        try {
            localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
        } catch {
            // Private mode: the choice just won't persist across visits.
        }
        const destination = localizePath(
            `${location.pathname}${location.search}${location.hash}`,
            nextLanguage,
        );
        navigate(destination);
    }, [location.hash, location.pathname, location.search, navigate]);

    const t = useCallback((key) => {
        return translations[language]?.[key] || translations.en[key] || key;
    }, [language]);

    const localePath = useCallback((path) => localizePath(path, language), [language]);

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            localePath,
            basePath: stripLocalePrefix(location.pathname),
        }}>
            {children}
        </LanguageContext.Provider>
    );
};
